BRKGA for MIP feasibility: dominiqs::GomorySeparator Class Reference
dominiqs::GomorySeparator Class Reference
#include <gomory.h>
Public Member Functions
GomorySeparator ()
virtual ~GomorySeparator ()
virtual void readConfig (dominiqs::XMLConfig &config, const std::string &root)
virtual bool separateGMI (dominiqs::Model &m, const std::vector< double > &x, dominiqs::CutPool &pool)
virtual bool separateGMI (dominiqs::Model &m, const std::vector< double > &x, dominiqs::CutList &cuts)
virtual void setX (dominiqs::Model &m, const std::vector< double > &x)
virtual dominiqs::CutPtr separateOneGMI (dominiqs::Model &m, const dominiqs::numarray< double > &multipliers, bool &violated)
virtual dominiqs::CutPtr separateOneGMI (dominiqs::Model &m, int rowIdx, bool &violated)
int getNumBadVars () const
void refactor (dominiqs::Model &m)
Public Attributes
dominiqs::Chrono watch
std::string name
double minViolation
double maxSupport
double maxDynamism
int maxRank
bool debugOn
bool forceRefactor
int maxGMI
bool onlyViolated
double onlyViolBadThr
dominiqs::Chrono tabRowChrono
dominiqs::Chrono applyChrono
dominiqs::Chrono backChrono
dominiqs::Chrono initChrono
int numImprKCuts
int numBadDynamism
int numTried
Protected Member Functions
virtual bool calculateTableauRow (dominiqs::Model &m, const dominiqs::numarray< double > &multipliers)
virtual bool applyGMI (dominiqs::Model &m)
virtual void backSubstitute (dominiqs::Model &m)
virtual void logStats ()
virtual void printRow (const dominiqs::Model &m)
Protected Attributes
double epsSmallVars
double epsBigVars
int rank
std::vector< double > shiftedRhs
dominiqs::numarray< double > xCoef
dominiqs::numarray< int > xSupport
dominiqs::numarray< int > xUsed
dominiqs::numarray< double > sCoef
dominiqs::numarray< int > sSupport
std::vector< char > xStatus
dominiqs::numarray< double > mult
double beta
std::vector< double > xStar
dominiqs::numarray< double > sStar
int cutCounter
dominiqs::WarmStart ws
dominiqs::numarray< int > badIdx
dominiqs::numarray< double > badVal
dominiqs::numarray< char > badType
int numBadX
int numBad
double badRatio
Detailed Description
Definition at line 28 of file gomory.h.
Constructor & Destructor Documentation
GomorySeparator()
dominiqs::GomorySeparator::GomorySeparator ()
Definition at line 70 of file gomory.cpp.
References dominiqs::bigRange, epsBigVars, and epsSmallVars.
~GomorySeparator()
dominiqs::GomorySeparator::~GomorySeparator () virtual
Definition at line 81 of file gomory.cpp.
References DOMINIQS_DEBUG_LOG, and logStats().
Member Function Documentation
applyGMI()
bool dominiqs::GomorySeparator::applyGMI (dominiqs::Model & m) protected virtual
Apply GMI formula Some care must be taken with variables not at their bounds (basic or free). Depending on the case, it might be impossible to generate the cut!
Definition at line 196 of file gomory.cpp.
References applyChrono, beta, DOMINIQS_DEBUG_LOG, epsBigVars, dominiqs::fractionalPart(), dominiqs::isInteger(), dominiqs::isNegative(), dominiqs::isNull(), dominiqs::Model::rows, sCoef, sSupport, dominiqs::Chrono::start(), dominiqs::Chrono::stop(), xCoef, dominiqs::Model::xLb, xStatus, xSupport, dominiqs::Model::xType, and dominiqs::Model::xUb.
Referenced by separateOneGMI().
backSubstitute()
void dominiqs::GomorySeparator::backSubstitute (dominiqs::Model & m) protected virtual
Back substitute slacks, in order to have a cut in the structural variables space
Definition at line 278 of file gomory.cpp.
References dominiqs::accumulate(), backChrono, beta, DOMINIQS_ASSERT, DOMINIQS_DEBUG_LOG, dominiqs::Model::rhs, dominiqs::Model::rows, sCoef, dominiqs::Model::sense, sSupport, dominiqs::Chrono::start(), dominiqs::Chrono::stop(), and xCoef.
Referenced by separateOneGMI().
calculateTableauRow()
bool dominiqs::GomorySeparator::calculateTableauRow (dominiqs::Model & m, const dominiqs::numarray< double > & multipliers) protected virtual
Calculate a i-th tableau row, combining the rows of the original matrix using the i-th row of B^-1 as multipliers. Very small multipliers are cleaned to zero.
Definition at line 113 of file gomory.cpp.
References badIdx, badRatio, badType, badVal, beta, dominiqs::numarray< T >::clear(), dominiqs::SparseVector::coef(), dominiqs::Model::cols, DOMINIQS_DEBUG_LOG, dominiqs::dotProduct(), epsBigVars, dominiqs::fractionalPart(), dominiqs::GMIcoef(), dominiqs::SparseVector::idx(), dominiqs::integralityViolation(), dominiqs::isNotNull(), dominiqs::lessThan(), max, maxRank, maxSupport, minViolation, numBad, numBadX, dominiqs::Model::numRows, dominiqs::Model::numVars, onlyViolated, onlyViolBadThr, dominiqs::numarray< T >::push_back_unsafe(), rank, dominiqs::numarray< T >::reserve(), dominiqs::numarray< T >::resize(), dominiqs::Model::rows, sCoef, dominiqs::Model::sense, shiftedRhs, dominiqs::SparseVector::size(), dominiqs::numarray< T >::size(), sSupport, dominiqs::Chrono::start(), dominiqs::Chrono::stop(), tabRowChrono, xCoef, xStatus, xSupport, xUsed, and dominiqs::numarray< T >::zero().
Referenced by separateOneGMI().
getNumBadVars()
int dominiqs::GomorySeparator::getNumBadVars () const inline
Definition at line 41 of file gomory.h.
References numBad.
logStats()
void dominiqs::GomorySeparator::logStats () protected virtual
Definition at line 527 of file gomory.cpp.
References applyChrono, backChrono, dominiqs::Logger::endSection(), dominiqs::Chrono::getTotal(), dominiqs::gLog(), initChrono, dominiqs::Logger::logItem(), name, numBadDynamism, numImprKCuts, numTried, dominiqs::Logger::setConsoleEcho(), dominiqs::Logger::startSection(), and tabRowChrono.
Referenced by ~GomorySeparator().
printRow()
void dominiqs::GomorySeparator::printRow (const dominiqs::Model & m) protected virtual
Definition at line 293 of file gomory.cpp.
References beta, dominiqs::isNotNull(), dominiqs::Model::rows, sCoef, sSupport, xCoef, dominiqs::Model::xNames, and xSupport.
readConfig()
void dominiqs::GomorySeparator::readConfig (dominiqs::XMLConfig & config, const std::string & root) virtual
Definition at line 86 of file gomory.cpp.
References dominiqs::FORCE_REFACTOR_DEF, forceRefactor, dominiqs::XMLConfig::get(), dominiqs::gLog(), dominiqs::Logger::logItem(), dominiqs::MAX_DYNAMISM_DEF, dominiqs::MAX_GMI_DEF, dominiqs::MAX_RANK_DEF, dominiqs::MAX_SUPPORT_DEF, maxDynamism, maxGMI, maxRank, maxSupport, dominiqs::MIN_VIOLATION_DEF, minViolation, name, dominiqs::ONLY_VIOL_BAD_DEF, dominiqs::ONLY_VIOLATED_DEF, onlyViolated, and onlyViolBadThr.
refactor()
void dominiqs::GomorySeparator::refactor (dominiqs::Model & m)
Definition at line 542 of file gomory.cpp.
References dominiqs::Model::env, dominiqs::Model::lp, dominiqs::WarmStart::read(), dominiqs::WarmStart::write(), and ws.
Referenced by separateGMI().
separateGMI() [1/2]
bool dominiqs::GomorySeparator::separateGMI (dominiqs::Model & m, const std::vector< double > & x, dominiqs::CutPool & pool) virtual
Definition at line 485 of file gomory.cpp.
References dominiqs::CutPool::push().
separateGMI() [2/2]
bool dominiqs::GomorySeparator::separateGMI (dominiqs::Model & m, const std::vector< double > & x, dominiqs::CutList & cuts) virtual
Definition at line 493 of file gomory.cpp.
References dominiqs::numarray< T >::c_ptr(), CHECKED_CPX_CALL, DOMINIQS_DEBUG_LOG, dominiqs::Model::env, epsSmallVars, forceRefactor, initChrono, dominiqs::integralityViolation(), dominiqs::Model::lp, maxGMI, minViolation, dominiqs::Model::numRows, dominiqs::permShellSort(), refactor(), separateOneGMI(), setX(), dominiqs::Chrono::start(), dominiqs::Chrono::stop(), watch, and dominiqs::Model::xType.
separateOneGMI() [1/2]
dominiqs::CutPtr dominiqs::GomorySeparator::separateOneGMI (dominiqs::Model & m, const dominiqs::numarray< double > & multipliers, bool & violated) virtual
Definition at line 427 of file gomory.cpp.
References applyGMI(), backSubstitute(), beta, calculateTableauRow(), dominiqs::numarray< T >::clear(), cutCounter, DOMINIQS_ASSERT, epsBigVars, dominiqs::isNotNull(), max, maxDynamism, maxSupport, minViolation, numBadDynamism, dominiqs::Model::numRows, numTried, dominiqs::Model::numVars, onlyViolated, rank, dominiqs::numarray< T >::size(), xCoef, xStar, xStatus, and xSupport.
Referenced by separateGMI(), and separateOneGMI().
separateOneGMI() [2/2]
dominiqs::CutPtr dominiqs::GomorySeparator::separateOneGMI (dominiqs::Model & m, int rowIdx, bool & violated) virtual
Definition at line 474 of file gomory.cpp.
References dominiqs::numarray< T >::c_ptr(), CHECKED_CPX_CALL, DOMINIQS_ASSERT, dominiqs::Model::env, dominiqs::Model::lp, mult, dominiqs::Model::numRows, dominiqs::numarray< T >::resize(), and separateOneGMI().
setX()
void dominiqs::GomorySeparator::setX (dominiqs::Model & m, const std::vector< double > & x) virtual
Analyze current LP solution to decide which variables are to be complemented and calculates shifted rhs
Definition at line 314 of file gomory.cpp.
References badIdx, badRatio, badType, badVal, dominiqs::numarray< T >::clear(), dominiqs::SparseVector::coef(), dominiqs::WarmStart::cstat, DOMINIQS_ASSERT_EQUAL, dominiqs::dotProduct(), dominiqs::Model::env, epsSmallVars, dominiqs::greaterThan(), dominiqs::SparseVector::idx(), dominiqs::isPositive(), dominiqs::lessThan(), dominiqs::Model::lp, numBad, numBadX, dominiqs::Model::numRows, dominiqs::Model::numSlacks, dominiqs::Model::numVars, dominiqs::numarray< T >::push_back(), dominiqs::WarmStart::read(), dominiqs::Model::rhs, dominiqs::Model::rows, dominiqs::Model::sense, shiftedRhs, dominiqs::SparseVector::size(), dominiqs::numarray< T >::size(), sStar, ws, dominiqs::Model::xLb, dominiqs::Model::xSimplexType, xStar, xStatus, dominiqs::Model::xType, and dominiqs::Model::xUb.
Referenced by separateGMI().
Member Data Documentation
applyChrono
dominiqs::Chrono dominiqs::GomorySeparator::applyChrono
Definition at line 58 of file gomory.h.
Referenced by applyGMI(), and logStats().
backChrono
dominiqs::Chrono dominiqs::GomorySeparator::backChrono
Definition at line 59 of file gomory.h.
Referenced by backSubstitute(), and logStats().
badIdx
dominiqs::numarray<int> dominiqs::GomorySeparator::badIdx protected
Definition at line 83 of file gomory.h.
Referenced by calculateTableauRow(), and setX().
badRatio
double dominiqs::GomorySeparator::badRatio protected
Definition at line 88 of file gomory.h.
Referenced by calculateTableauRow(), and setX().
badType
dominiqs::numarray<char> dominiqs::GomorySeparator::badType protected
Definition at line 85 of file gomory.h.
Referenced by calculateTableauRow(), and setX().
badVal
dominiqs::numarray<double> dominiqs::GomorySeparator::badVal protected
Definition at line 84 of file gomory.h.
Referenced by calculateTableauRow(), and setX().
beta
double dominiqs::GomorySeparator::beta protected
Definition at line 78 of file gomory.h.
Referenced by applyGMI(), backSubstitute(), calculateTableauRow(), printRow(), and separateOneGMI().
cutCounter
int dominiqs::GomorySeparator::cutCounter protected
Definition at line 81 of file gomory.h.
Referenced by separateOneGMI().
debugOn
bool dominiqs::GomorySeparator::debugOn
Definition at line 51 of file gomory.h.
epsBigVars
double dominiqs::GomorySeparator::epsBigVars protected
Definition at line 67 of file gomory.h.
Referenced by applyGMI(), calculateTableauRow(), GomorySeparator(), and separateOneGMI().
epsSmallVars
double dominiqs::GomorySeparator::epsSmallVars protected
Definition at line 66 of file gomory.h.
Referenced by GomorySeparator(), separateGMI(), and setX().
forceRefactor
bool dominiqs::GomorySeparator::forceRefactor
Definition at line 52 of file gomory.h.
Referenced by readConfig(), and separateGMI().
initChrono
dominiqs::Chrono dominiqs::GomorySeparator::initChrono
Definition at line 60 of file gomory.h.
Referenced by logStats(), and separateGMI().
maxDynamism
double dominiqs::GomorySeparator::maxDynamism
Definition at line 49 of file gomory.h.
Referenced by readConfig(), and separateOneGMI().
maxGMI
int dominiqs::GomorySeparator::maxGMI
Definition at line 53 of file gomory.h.
Referenced by readConfig(), and separateGMI().
maxRank
int dominiqs::GomorySeparator::maxRank
Definition at line 50 of file gomory.h.
Referenced by calculateTableauRow(), and readConfig().
maxSupport
double dominiqs::GomorySeparator::maxSupport
Definition at line 48 of file gomory.h.
Referenced by calculateTableauRow(), readConfig(), and separateOneGMI().
minViolation
double dominiqs::GomorySeparator::minViolation
Definition at line 47 of file gomory.h.
Referenced by calculateTableauRow(), readConfig(), separateGMI(), and separateOneGMI().
mult
dominiqs::numarray<double> dominiqs::GomorySeparator::mult protected
Definition at line 77 of file gomory.h.
Referenced by separateOneGMI().
name
std::string dominiqs::GomorySeparator::name
Definition at line 46 of file gomory.h.
Referenced by logStats(), and readConfig().
numBad
int dominiqs::GomorySeparator::numBad protected
Definition at line 87 of file gomory.h.
Referenced by calculateTableauRow(), getNumBadVars(), and setX().
numBadDynamism
int dominiqs::GomorySeparator::numBadDynamism
Definition at line 62 of file gomory.h.
Referenced by logStats(), and separateOneGMI().
numBadX
int dominiqs::GomorySeparator::numBadX protected
Definition at line 86 of file gomory.h.
Referenced by calculateTableauRow(), and setX().
numImprKCuts
int dominiqs::GomorySeparator::numImprKCuts
Definition at line 61 of file gomory.h.
Referenced by logStats().
numTried
int dominiqs::GomorySeparator::numTried
Definition at line 63 of file gomory.h.
Referenced by logStats(), and separateOneGMI().
onlyViolated
bool dominiqs::GomorySeparator::onlyViolated
Definition at line 54 of file gomory.h.
Referenced by calculateTableauRow(), readConfig(), and separateOneGMI().
onlyViolBadThr
double dominiqs::GomorySeparator::onlyViolBadThr
Definition at line 55 of file gomory.h.
Referenced by calculateTableauRow(), and readConfig().
rank
int dominiqs::GomorySeparator::rank protected
Definition at line 69 of file gomory.h.
Referenced by calculateTableauRow(), and separateOneGMI().
sCoef
dominiqs::numarray<double> dominiqs::GomorySeparator::sCoef protected
Definition at line 74 of file gomory.h.
Referenced by applyGMI(), backSubstitute(), calculateTableauRow(), and printRow().
shiftedRhs
std::vector<double> dominiqs::GomorySeparator::shiftedRhs protected
Definition at line 70 of file gomory.h.
Referenced by calculateTableauRow(), and setX().
sStar
dominiqs::numarray<double> dominiqs::GomorySeparator::sStar protected
Definition at line 80 of file gomory.h.
Referenced by setX().
sSupport
dominiqs::numarray<int> dominiqs::GomorySeparator::sSupport protected
Definition at line 75 of file gomory.h.
Referenced by applyGMI(), backSubstitute(), calculateTableauRow(), and printRow().
tabRowChrono
dominiqs::Chrono dominiqs::GomorySeparator::tabRowChrono
Definition at line 57 of file gomory.h.
Referenced by calculateTableauRow(), and logStats().
watch
dominiqs::Chrono dominiqs::GomorySeparator::watch
Definition at line 44 of file gomory.h.
Referenced by separateGMI().
ws
dominiqs::WarmStart dominiqs::GomorySeparator::ws protected
Definition at line 82 of file gomory.h.
Referenced by refactor(), and setX().
xCoef
dominiqs::numarray<double> dominiqs::GomorySeparator::xCoef protected
Definition at line 71 of file gomory.h.
Referenced by applyGMI(), backSubstitute(), calculateTableauRow(), printRow(), and separateOneGMI().
xStar
std::vector<double> dominiqs::GomorySeparator::xStar protected
Definition at line 79 of file gomory.h.
Referenced by separateOneGMI(), and setX().
xStatus
std::vector<char> dominiqs::GomorySeparator::xStatus protected
Definition at line 76 of file gomory.h.
Referenced by applyGMI(), calculateTableauRow(), separateOneGMI(), and setX().
xSupport
dominiqs::numarray<int> dominiqs::GomorySeparator::xSupport protected
Definition at line 72 of file gomory.h.
Referenced by applyGMI(), calculateTableauRow(), printRow(), and separateOneGMI().
xUsed
dominiqs::numarray<int> dominiqs::GomorySeparator::xUsed protected
Definition at line 73 of file gomory.h.
Referenced by calculateTableauRow().
The documentation for this class was generated from the following files:
FP2/cpxutils/gomory.h
FP2/cpxutils/gomory.cpp