BRKGA for MIP feasibility: LexLessEqualPropAdvisor Class Reference
LexLessEqualPropAdvisor Class Reference
#include <lex_propagator.h>
Public Member Functions
LexLessEqualPropAdvisor (LexLessEqualProp *p, int i)
void fixedUp ()
void fixedDown ()
void tightenLb (double delta, bool decreaseInfCnt, bool propagate)
void tightenUb (double delta, bool decreaseInfCnt, bool propagate)
std::ostream & print (std::ostream &out) const
Public Member Functions inherited from AdvisorI
AdvisorI (Propagator *p, int j)
virtual ~AdvisorI ()
Propagator * getPropagator () const
int getVar () const
Protected Attributes
int idx
Protected Attributes inherited from AdvisorI
Propagator * prop
int var
Additional Inherited Members
Protected Member Functions inherited from AdvisorI
template<class T >
T * getMyProp ()
Detailed Description
Definition at line 44 of file lex_propagator.h.
Constructor & Destructor Documentation
LexLessEqualPropAdvisor()
LexLessEqualPropAdvisor::LexLessEqualPropAdvisor (LexLessEqualProp * p, int i) inline
Definition at line 47 of file lex_propagator.h.
Member Function Documentation
fixedDown()
void LexLessEqualPropAdvisor::fixedDown () virtual
Reimplemented from AdvisorI.
Definition at line 27 of file lex_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::state, and LexLessEqualProp::updateState().
fixedUp()
void LexLessEqualPropAdvisor::fixedUp () virtual
events for binary variables
Reimplemented from AdvisorI.
Definition at line 19 of file lex_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::state, and LexLessEqualProp::updateState().
print()
std::ostream & LexLessEqualPropAdvisor::print (std::ostream & out) const virtual
Reimplemented from AdvisorI.
Definition at line 51 of file lex_propagator.cpp.
tightenLb()
void LexLessEqualPropAdvisor::tightenLb (double delta, bool decreaseInfCnt, bool propagate) virtual
events for other (general integer and continuous) variables
Parameters
delta bound increase (if it was finite) or new value if tightening from infinite
decreaseInfCnt (this flag is true if the previous value for the bound was infinite)
propagate mask to trigger or not constraint propagation
Reimplemented from AdvisorI.
Definition at line 35 of file lex_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::state, and LexLessEqualProp::updateState().
tightenUb()
void LexLessEqualPropAdvisor::tightenUb (double delta, bool decreaseInfCnt, bool propagate) virtual
Reimplemented from AdvisorI.
Definition at line 43 of file lex_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::state, and LexLessEqualProp::updateState().
Member Data Documentation
idx
int LexLessEqualPropAdvisor::idx protected
Definition at line 57 of file lex_propagator.h.
The documentation for this class was generated from the following files:
FP2/propagator/lex_propagator.h
FP2/propagator/lex_propagator.cpp