BRKGA for MIP feasibility: Ranker Class Reference
Ranker Class Reference abstract
Ranker Base Class.
#include <ranking.h>
Public Member Functions
Ranker ()
virtual ~Ranker ()
virtual void readConfig ()
virtual void init (Domain *d, bool ignoreGeneralInt=true)
virtual void ignoreGeneralIntegers (bool flag)
virtual void setCurrentState (const std::vector< double > &x)=0
virtual int next ()=0
Protected Attributes
Domain * domain
std::vector< int > binaries
std::vector< int > gintegers
std::vector< int > integers
int nCalled
Detailed Description
Ranker Base Class.
Definition at line 28 of file ranking.h.
Constructor & Destructor Documentation
Ranker()
Ranker::Ranker () inline
Definition at line 31 of file ranking.h.
~Ranker()
virtual Ranker::~Ranker () inline virtual
Definition at line 32 of file ranking.h.
Member Function Documentation
ignoreGeneralIntegers()
void Ranker::ignoreGeneralIntegers (bool flag) virtual
Reimplemented in RandomRanker, and FractionalityRanker.
Definition at line 48 of file ranking.cpp.
References DOMINIQS_ASSERT.
Referenced by FractionalityRanker::ignoreGeneralIntegers(), and RandomRanker::ignoreGeneralIntegers().
init()
void Ranker::init (Domain * d, bool ignoreGeneralInt = true) virtual
Definition at line 29 of file ranking.cpp.
References Domain::clear(), and DOMINIQS_ASSERT.
next()
virtual int Ranker::next () pure virtual
Implemented in RandomRanker, FractionalityRanker, and LeftToRightRanker.
readConfig()
virtual void Ranker::readConfig () inline virtual
Reimplemented in RandomRanker, and FractionalityRanker.
Definition at line 33 of file ranking.h.
setCurrentState()
virtual void Ranker::setCurrentState (const std::vector< double > & x) pure virtual
Implemented in RandomRanker, FractionalityRanker, and LeftToRightRanker.
Member Data Documentation
binaries
std::vector<int> Ranker::binaries protected
Definition at line 40 of file ranking.h.
domain
Domain* Ranker::domain protected
Definition at line 39 of file ranking.h.
gintegers
std::vector<int> Ranker::gintegers protected
Definition at line 41 of file ranking.h.
integers
std::vector<int> Ranker::integers protected
Definition at line 42 of file ranking.h.
nCalled
int Ranker::nCalled protected
Definition at line 43 of file ranking.h.
The documentation for this class was generated from the following files:
FP2/feaspump/ranking.h
FP2/feaspump/ranking.cpp