BRKGA for MIP feasibility: dominiqs::SparseVector Class Reference
dominiqs::SparseVector Class Reference
#include <maths.h>
Public Types
typedef unsigned int size_type
Public Member Functions
SparseVector ()
SparseVector (const SparseVector &other)
SparseVector & operator= (const SparseVector &other)
~SparseVector () throw ()
void swap (SparseVector &other) throw ()
size_type size () const
size_type capacity () const
void resize (size_type newSize)
bool empty () const
void reserve (size_type n)
void clear ()
void push (int i, double v)
void push_unsafe (int i, double v)
void pop ()
void copy (const int *idx, const double *coef, size_type cnt)
bool operator== (const SparseVector &rhs) const
void gather (const double *in, int n, double eps=defaultEPS)
void scatter (double *out, int n, bool reset=false)
void unscatter (double *out)
int * idx ()
const int * idx () const
double * coef ()
const double * coef () const
Protected Attributes
int * m_idx
double * m_coef
size_type length
size_type alloc
Detailed Description
Sparse Vector Stores a vector in sparse form The internal vectors have 16-bit alignment (SSE2 compatible)
Definition at line 32 of file maths.h.
Member Typedef Documentation
size_type
typedef unsigned int dominiqs::SparseVector::size_type
Definition at line 35 of file maths.h.
Constructor & Destructor Documentation
SparseVector() [1/2]
dominiqs::SparseVector::SparseVector () inline
Definition at line 37 of file maths.h.
SparseVector() [2/2]
dominiqs::SparseVector::SparseVector (const SparseVector & other)
Definition at line 18 of file maths.cpp.
References alloc, DOMINIQS_ASSERT, dominiqs::scoped_ptr_sse2< T >::get(), length, m_coef, m_idx, dominiqs::mallocSSE2(), and dominiqs::scoped_ptr_sse2< T >::release().
~SparseVector()
dominiqs::SparseVector::~SparseVector () throw () inline
Definition at line 42 of file maths.h.
References dominiqs::freeSSE2(), m_coef, and m_idx.
Member Function Documentation
capacity()
size_type dominiqs::SparseVector::capacity () const inline
Definition at line 56 of file maths.h.
References alloc.
Referenced by dominiqs::Cut::memoryUsed().
clear()
void dominiqs::SparseVector::clear () inline
Definition at line 60 of file maths.h.
References length.
Referenced by gather(), dominiqs::getCut(), and dominiqs::getVar().
coef() [1/2]
double* dominiqs::SparseVector::coef () inline
Definition at line 82 of file maths.h.
References m_coef.
Referenced by dominiqs::accumulate(), dominiqs::addCut(), dominiqs::addUserCut(), dominiqs::addVar(), LogicFactory::analyze(), VarBoundFactory::analyze(), CardinalityFactory::analyze(), KnapsackFactory::analyze(), dominiqs::GomorySeparator::calculateTableauRow(), copy(), dominiqs::Cut::digest(), dominiqs::dotProduct(), dominiqs::Cut::dynamism(), dominiqs::getCut(), dominiqs::getVar(), PropagatorRounding::init(), KnapsackProp::KnapsackProp(), LinearProp::LinearProp(), dominiqs::printCut(), dominiqs::GomorySeparator::setX(), dominiqs::FeasibilityPump::stage2(), and dominiqs::FeasibilityPump::stage3().
coef() [2/2]
const double* dominiqs::SparseVector::coef () const inline
Definition at line 83 of file maths.h.
References m_coef.
copy()
void dominiqs::SparseVector::copy (const int * idx, const double * coef, size_type cnt)
Definition at line 87 of file maths.cpp.
References coef(), DOMINIQS_ASSERT, idx(), length, m_coef, m_idx, and resize().
empty()
bool dominiqs::SparseVector::empty () const inline
Definition at line 58 of file maths.h.
References length.
gather()
void dominiqs::SparseVector::gather (const double * in, int n, double eps = defaultEPS)
conversions to/from dense vectors Shrink a dense vector into a sparse one
Definition at line 106 of file maths.cpp.
References clear(), DEF_GATHER_SIZE, dominiqs::isNotNull(), min, push(), push_unsafe(), and reserve().
idx() [1/2]
int* dominiqs::SparseVector::idx () inline
Definition at line 80 of file maths.h.
References m_idx.
Referenced by dominiqs::accumulate(), dominiqs::addCut(), dominiqs::addUserCut(), dominiqs::addVar(), LogicFactory::analyze(), VarBoundFactory::analyze(), CardinalityFactory::analyze(), KnapsackFactory::analyze(), dominiqs::GomorySeparator::calculateTableauRow(), CardinalityProp::CardinalityProp(), copy(), dominiqs::Cut::digest(), dominiqs::dotProduct(), dominiqs::getCut(), dominiqs::getVar(), PropagatorRounding::init(), KnapsackProp::KnapsackProp(), LinearProp::LinearProp(), dominiqs::printCut(), and dominiqs::GomorySeparator::setX().
idx() [2/2]
const int* dominiqs::SparseVector::idx () const inline
Definition at line 81 of file maths.h.
References m_idx.
operator=()
SparseVector & dominiqs::SparseVector::operator= (const SparseVector & other)
Definition at line 43 of file maths.cpp.
References swap().
operator==()
bool dominiqs::SparseVector::operator== (const SparseVector & rhs) const
Compare two sparse vectors for equality ATTENTION: the procedure assumes the indexes to be in increasing order, i.e., sorted!!!
Definition at line 95 of file maths.cpp.
References dominiqs::different(), m_coef, m_idx, and size().
pop()
void dominiqs::SparseVector::pop () inline
Definition at line 73 of file maths.h.
References length.
push()
void dominiqs::SparseVector::push (int i, double v) inline
Definition at line 62 of file maths.h.
References alloc, length, max, push_unsafe(), and reserve().
Referenced by gather(), dominiqs::FeasibilityPump::stage2(), and dominiqs::FeasibilityPump::stage3().
push_unsafe()
void dominiqs::SparseVector::push_unsafe (int i, double v) inline
Definition at line 67 of file maths.h.
References length, m_coef, and m_idx.
Referenced by gather(), and push().
reserve()
void dominiqs::SparseVector::reserve (size_type n)
Definition at line 71 of file maths.cpp.
References alloc, dominiqs::freeSSE2(), length, m_coef, m_idx, and dominiqs::mallocSSE2().
Referenced by gather(), push(), and resize().
resize()
void dominiqs::SparseVector::resize (size_type newSize)
Definition at line 53 of file maths.cpp.
References alloc, dominiqs::freeSSE2(), length, m_coef, m_idx, and reserve().
Referenced by copy(), dominiqs::getCut(), and dominiqs::getVar().
scatter()
void dominiqs::SparseVector::scatter (double * out, int n, bool reset = false)
Expand a sparse vector into a dense one
Definition at line 115 of file maths.cpp.
References m_coef, m_idx, and size().
size()
size_type dominiqs::SparseVector::size () const inline
Definition at line 55 of file maths.h.
References length.
Referenced by dominiqs::accumulate(), dominiqs::addCut(), dominiqs::addUserCut(), dominiqs::addVar(), LogicFactory::analyze(), VarBoundFactory::analyze(), CardinalityFactory::analyze(), KnapsackFactory::analyze(), dominiqs::GomorySeparator::calculateTableauRow(), CardinalityProp::CardinalityProp(), dominiqs::Cut::digest(), dominiqs::dotProduct(), dominiqs::Cut::dynamism(), PropagatorRounding::init(), KnapsackProp::KnapsackProp(), LinearProp::LinearProp(), operator==(), dominiqs::printCut(), scatter(), dominiqs::GomorySeparator::setX(), and unscatter().
swap()
void dominiqs::SparseVector::swap (SparseVector & other) throw () inline
Definition at line 47 of file maths.h.
References alloc, length, m_coef, and m_idx.
Referenced by operator=().
unscatter()
void dominiqs::SparseVector::unscatter (double * out)
Zero out the coefficients of a dense vector corresponding to the support of a sparse vector
Definition at line 122 of file maths.cpp.
References m_idx, and size().
Member Data Documentation
alloc
size_type dominiqs::SparseVector::alloc protected
Definition at line 101 of file maths.h.
Referenced by capacity(), push(), reserve(), resize(), SparseVector(), and swap().
length
size_type dominiqs::SparseVector::length protected
Definition at line 100 of file maths.h.
Referenced by clear(), copy(), empty(), pop(), push(), push_unsafe(), reserve(), resize(), size(), SparseVector(), and swap().
m_coef
double* dominiqs::SparseVector::m_coef protected
Definition at line 99 of file maths.h.
Referenced by coef(), copy(), operator==(), push_unsafe(), reserve(), resize(), scatter(), SparseVector(), swap(), and ~SparseVector().
m_idx
int* dominiqs::SparseVector::m_idx protected
Definition at line 98 of file maths.h.
Referenced by copy(), idx(), operator==(), push_unsafe(), reserve(), resize(), scatter(), SparseVector(), swap(), unscatter(), and ~SparseVector().
The documentation for this class was generated from the following files:
FP2/utils/maths.h
FP2/utils/maths.cpp