BRKGA for MIP feasibility: CardinalityFactory Class Reference
CardinalityFactory Class Reference
#include <linear_propagator.h>
Public Member Functions
PropagatorFactory * clone () const
int getPriority () const
const char * getName () const
Propagator * analyze (Domain *d, dominiqs::Constraint *c)
Public Member Functions inherited from PropagatorFactory
PropagatorFactory ()
virtual ~PropagatorFactory ()
void reset ()
int created () const
int & propCalled ()
int & domainReductions ()
Additional Inherited Members
Protected Attributes inherited from PropagatorFactory
int numCreated
int numPropCalled
int numDomainReductions
Detailed Description
Definition at line 100 of file linear_propagator.h.
Member Function Documentation
analyze()
Propagator * CardinalityFactory::analyze (Domain * d, dominiqs::Constraint * c) virtual
Implements PropagatorFactory.
Definition at line 731 of file linear_propagator.cpp.
References dominiqs::SparseVector::coef(), dominiqs::different(), dominiqs::SparseVector::idx(), PropagatorFactory::numCreated, dominiqs::Constraint::row, dominiqs::SparseVector::size(), and Domain::varType().
clone()
PropagatorFactory * CardinalityFactory::clone () const virtual
Implements PropagatorFactory.
Definition at line 716 of file linear_propagator.cpp.
getName()
const char * CardinalityFactory::getName () const virtual
Implements PropagatorFactory.
Definition at line 726 of file linear_propagator.cpp.
getPriority()
int CardinalityFactory::getPriority () const virtual
Implements PropagatorFactory.
Definition at line 721 of file linear_propagator.cpp.
References CARDINALITY_DEFAULT_PRIORITY.
The documentation for this class was generated from the following files:
FP2/propagator/linear_propagator.h
FP2/propagator/linear_propagator.cpp