BRKGA for MIP feasibility: dominiqs::Logger Class Reference
dominiqs::Logger Class Reference
#include <logger.h>
Public Member Functions
Logger ()
~Logger ()
void open (const std::string &name, const std::string &path="")
void close ()
void flush ()
bool isOpen () const
void setConsoleEcho (bool enable)
void setFileWrite (bool enable)
void startSection (const std::string &name)
template<class T >
void startSection (const std::string &name, const std::string &attrName, const T &attrValue)
void endSection ()
template<class T >
void logItem (const std::string &key, const T &value)
template<class T >
void logBinaryItem (const std::string &key, const std::string &type, const T &value)
void logMsg (const std::string &msg)
Protected Attributes
std::ofstream xml
Serializer s
std::string indent
std::vector< std::string > openSections
bool doWrite
bool doEcho
Detailed Description
Main Logger Class Used to log both binary and text data
Definition at line 39 of file logger.h.
Constructor & Destructor Documentation
Logger()
dominiqs::Logger::Logger () inline
Definition at line 43 of file logger.h.
~Logger()
dominiqs::Logger::~Logger ()
Definition at line 16 of file logger.cpp.
References close().
Member Function Documentation
close()
void dominiqs::Logger::close ()
Definition at line 40 of file logger.cpp.
References DOMINIQS_ASSERT, indent, openSections, and xml.
Referenced by main(), open(), dominiqs::App::run(), and ~Logger().
endSection()
void dominiqs::Logger::endSection ()
Definition at line 67 of file logger.cpp.
References DOMINIQS_ASSERT, doWrite, indent, openSections, and xml.
Referenced by dominiqs::GlobalAutoSection::close(), dominiqs::cpxBB(), dominiqs::FeasibilityPump::foundIncumbent(), dominiqs::GomorySeparator::logStats(), dominiqs::FeasibilityPump::perturbe(), dominiqs::FeasibilityPump::readConfig(), and dominiqs::FeasibilityPump::restart().
flush()
void dominiqs::Logger::flush ()
Definition at line 49 of file logger.cpp.
References xml.
Referenced by dominiqs::infoCB().
isOpen()
bool dominiqs::Logger::isOpen () const inline
Definition at line 49 of file logger.h.
References xml.
logBinaryItem()
template<class T > void dominiqs::Logger::logBinaryItem (const std::string & key, const std::string & type, const T & value) inline
Definition at line 79 of file logger.h.
References DOMINIQS_ASSERT, doWrite, indent, s, dominiqs::Serializer::serialize(), xml, and dominiqs::xmlEscape().
logItem()
template<class T > void dominiqs::Logger::logItem (const std::string & key, const T & value) inline
Definition at line 69 of file logger.h.
References doEcho, DOMINIQS_ASSERT, doWrite, indent, and xml.
Referenced by SimpleRounding::apply(), dominiqs::cpxBB(), dominiqs::FeasibilityPump::foundIncumbent(), dominiqs::infoCB(), dominiqs::FeasibilityPump::init(), dominiqs::GomorySeparator::logStats(), dominiqs::FeasibilityPump::perturbe(), dominiqs::FeasibilityPump::pump(), dominiqs::GomorySeparator::readConfig(), dominiqs::FeasibilityPump::readConfig(), dominiqs::CutPool::readConfig(), dominiqs::FeasibilityPump::restart(), dominiqs::FeasibilityPump::solveInitialLP(), dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
logMsg()
void dominiqs::Logger::logMsg (const std::string & msg)
Definition at line 77 of file logger.cpp.
References doEcho, DOMINIQS_ASSERT, doWrite, indent, xml, and dominiqs::xmlEscape().
Referenced by main(), dominiqs::App::run(), and dominiqs::FeasibilityPump::stage3().
open()
void dominiqs::Logger::open (const std::string & name, const std::string & path = "")
Definition at line 29 of file logger.cpp.
References close(), dominiqs::Path::getPath(), dominiqs::Path::mkdir(), and xml.
Referenced by main(), and dominiqs::App::run().
setConsoleEcho()
void dominiqs::Logger::setConsoleEcho (bool enable) inline
Definition at line 51 of file logger.h.
References doEcho.
Referenced by dominiqs::GomorySeparator::logStats(), main(), dominiqs::FeasibilityPump::pump(), and dominiqs::App::run().
setFileWrite()
void dominiqs::Logger::setFileWrite (bool enable) inline
Definition at line 52 of file logger.h.
References doWrite.
startSection() [1/2]
void dominiqs::Logger::startSection (const std::string & name)
Definition at line 54 of file logger.cpp.
References doEcho, DOMINIQS_ASSERT, doWrite, indent, openSections, and xml.
Referenced by dominiqs::cpxBB(), dominiqs::GlobalAutoSection::GlobalAutoSection(), dominiqs::GomorySeparator::logStats(), and dominiqs::FeasibilityPump::readConfig().
startSection() [2/2]
template<class T > void dominiqs::Logger::startSection (const std::string & name, const std::string & attrName, const T & attrValue) inline
Definition at line 55 of file logger.h.
References doEcho, DOMINIQS_ASSERT, doWrite, indent, openSections, and xml.
Member Data Documentation
doEcho
bool dominiqs::Logger::doEcho protected
Definition at line 99 of file logger.h.
Referenced by logItem(), logMsg(), setConsoleEcho(), and startSection().
doWrite
bool dominiqs::Logger::doWrite protected
Definition at line 98 of file logger.h.
Referenced by endSection(), logBinaryItem(), logItem(), logMsg(), setFileWrite(), and startSection().
indent
std::string dominiqs::Logger::indent protected
Definition at line 96 of file logger.h.
Referenced by close(), endSection(), logBinaryItem(), logItem(), logMsg(), and startSection().
openSections
std::vector<std::string> dominiqs::Logger::openSections protected
Definition at line 97 of file logger.h.
Referenced by close(), endSection(), and startSection().
s
Serializer dominiqs::Logger::s protected
Definition at line 95 of file logger.h.
Referenced by logBinaryItem().
xml
std::ofstream dominiqs::Logger::xml protected
Definition at line 94 of file logger.h.
Referenced by close(), endSection(), flush(), isOpen(), logBinaryItem(), logItem(), logMsg(), open(), and startSection().
The documentation for this class was generated from the following files:
FP2/utils/logger.h
FP2/utils/logger.cpp