BRKGA for MIP feasibility: PropagatorFactory Class Reference
PropagatorFactory Class Reference abstract
#include <propagator.h>
Public Member Functions
PropagatorFactory ()
virtual ~PropagatorFactory ()
virtual PropagatorFactory * clone () const =0
virtual int getPriority () const =0
virtual const char * getName () const =0
virtual Propagator * analyze (Domain *d, dominiqs::Constraint *c)=0
void reset ()
int created () const
int & propCalled ()
int & domainReductions ()
Protected Attributes
int numCreated
int numPropCalled
int numDomainReductions
Detailed Description
PropagatorFactory interface This class analyzes a constraint and, if it detects a given structure, instantiate a specialized constraint propagator
Definition at line 105 of file propagator.h.
Constructor & Destructor Documentation
PropagatorFactory()
PropagatorFactory::PropagatorFactory ()
Definition at line 25 of file propagator.cpp.
~PropagatorFactory()
virtual PropagatorFactory::~PropagatorFactory () inline virtual
Definition at line 109 of file propagator.h.
Member Function Documentation
analyze()
virtual Propagator* PropagatorFactory::analyze (Domain * d, dominiqs::Constraint * c) pure virtual
Implemented in KnapsackFactory, CardinalityFactory, VarBoundFactory, LinearFactory, and LogicFactory.
clone()
virtual PropagatorFactory* PropagatorFactory::clone () const pure virtual
Implemented in KnapsackFactory, CardinalityFactory, VarBoundFactory, LinearFactory, and LogicFactory.
created()
int PropagatorFactory::created () const inline
Definition at line 116 of file propagator.h.
References numCreated.
domainReductions()
int& PropagatorFactory::domainReductions () inline
Definition at line 118 of file propagator.h.
References numDomainReductions.
Referenced by ImpliesProp::propagate(), VarLowerBoundProp::propagate(), LinearProp::propagate(), EquivProp::propagate(), VarUpperBoundProp::propagate(), CardinalityProp::propagate(), and KnapsackProp::propagate().
getName()
virtual const char* PropagatorFactory::getName () const pure virtual
Implemented in KnapsackFactory, CardinalityFactory, VarBoundFactory, LinearFactory, and LogicFactory.
getPriority()
virtual int PropagatorFactory::getPriority () const pure virtual
Implemented in KnapsackFactory, CardinalityFactory, VarBoundFactory, LinearFactory, and LogicFactory.
propCalled()
int& PropagatorFactory::propCalled () inline
Definition at line 117 of file propagator.h.
References numPropCalled.
Referenced by ImpliesProp::propagate(), VarLowerBoundProp::propagate(), LinearProp::propagate(), EquivProp::propagate(), VarUpperBoundProp::propagate(), CardinalityProp::propagate(), and KnapsackProp::propagate().
reset()
void PropagatorFactory::reset ()
Definition at line 27 of file propagator.cpp.
References numCreated, numDomainReductions, and numPropCalled.
Member Data Documentation
numCreated
int PropagatorFactory::numCreated protected
Definition at line 121 of file propagator.h.
Referenced by LinearFactory::analyze(), LogicFactory::analyze(), VarBoundFactory::analyze(), CardinalityFactory::analyze(), KnapsackFactory::analyze(), created(), and reset().
numDomainReductions
int PropagatorFactory::numDomainReductions protected
Definition at line 123 of file propagator.h.
Referenced by domainReductions(), and reset().
numPropCalled
int PropagatorFactory::numPropCalled protected
Definition at line 122 of file propagator.h.
Referenced by propCalled(), and reset().
The documentation for this class was generated from the following files:
FP2/propagator/propagator.h
FP2/propagator/propagator.cpp