BRKGA for MIP feasibility: PropagatorRounding Class Reference
PropagatorRounding Class Reference
#include <transformers.h>
Public Member Functions
PropagatorRounding ()
~PropagatorRounding ()
void readConfig ()
void init (const dominiqs::Model &model, bool ignoreGeneralInt=true)
void ignoreGeneralIntegers (bool flag)
void apply (const std::vector< double > &in, std::vector< double > &out)
void clear ()
Public Member Functions inherited from SimpleRounding
SimpleRounding ()
Public Member Functions inherited from dominiqs::SolutionTransformer
virtual ~SolutionTransformer ()
virtual void newIncumbent (const std::vector< double > &x, double objval)
Public Attributes
Domain domain
StatePtr state
PropagationEngine prop
std::map< int, PropagatorFactoryPtr > factories
RankerPtr ranker
bool filterConstraints
Public Attributes inherited from SimpleRounding
std::vector< int > binaries
std::vector< int > gintegers
std::vector< int > integers
dominiqs::UnitRandGen roundGen
bool randomizedRounding
bool logDetails
Detailed Description
Ranked rounding + constraint propagation
Definition at line 63 of file transformers.h.
Constructor & Destructor Documentation
PropagatorRounding()
PropagatorRounding::PropagatorRounding ()
Definition at line 110 of file transformers.cpp.
~PropagatorRounding()
PropagatorRounding::~PropagatorRounding () inline
Definition at line 67 of file transformers.h.
References clear().
Member Function Documentation
apply()
void PropagatorRounding::apply (const std::vector< double > & in, std::vector< double > & out) virtual
Trasform the vector given as input
Parameters
in and store the result in
out
Reimplemented from SimpleRounding.
Definition at line 218 of file transformers.cpp.
References domain, DOMINIQS_ASSERT, doRound(), PropagationEngine::getLastFixed(), getRoundingThreshold(), dominiqs::greaterEqualThan(), Domain::isVarFixed(), dominiqs::lessEqualThan(), prop, PropagationEngine::propagate(), SimpleRounding::randomizedRounding, ranker, State::restore(), SimpleRounding::roundGen, state, Domain::varLb(), Domain::varType(), and Domain::varUb().
clear()
void PropagatorRounding::clear () virtual
Reimplemented from dominiqs::SolutionTransformer.
Definition at line 246 of file transformers.cpp.
References PropagationEngine::clear(), factories, prop, and state.
Referenced by ~PropagatorRounding().
ignoreGeneralIntegers()
void PropagatorRounding::ignoreGeneralIntegers (bool flag) virtual
Reimplemented from SimpleRounding.
Definition at line 212 of file transformers.cpp.
References SimpleRounding::ignoreGeneralIntegers(), and ranker.
init()
void PropagatorRounding::init (const dominiqs::Model & model, bool ignoreGeneralInt = true) virtual
Read needed information (if any) about the problem (
Parameters
pinfo)
Reimplemented from SimpleRounding.
Definition at line 127 of file transformers.cpp.
References dominiqs::SparseVector::coef(), domain, State::dump(), factories, filterConstraints, dominiqs::SingletonHolder< T >::getInstance(), PropagationEngine::getStateMgr(), dominiqs::greaterThan(), dominiqs::SparseVector::idx(), SimpleRounding::init(), Domain::isVarFixed(), max, min, dominiqs::Model::numRows, dominiqs::Model::numVars, prop, PropagationEngine::pushPropagator(), Domain::pushVar(), ranker, dominiqs::Constraint::row, dominiqs::Model::rows, PropagationEngine::setDomain(), dominiqs::SparseVector::size(), state, Domain::varType(), dominiqs::Model::xLb, dominiqs::Model::xNames, dominiqs::Model::xType, and dominiqs::Model::xUb.
readConfig()
void PropagatorRounding::readConfig () virtual
Reimplemented from SimpleRounding.
Definition at line 114 of file transformers.cpp.
References filterConstraints, dominiqs::gConfig(), dominiqs::XMLConfig::get(), dominiqs::SingletonHolder< T >::getInstance(), LOG_END_SECTION, LOG_ITEM, LOG_START_SECTION, ranker, and SimpleRounding::readConfig().
Member Data Documentation
domain
Domain PropagatorRounding::domain
Definition at line 76 of file transformers.h.
Referenced by apply(), and init().
factories
std::map<int, PropagatorFactoryPtr> PropagatorRounding::factories
Definition at line 79 of file transformers.h.
Referenced by clear(), and init().
filterConstraints
bool PropagatorRounding::filterConstraints
Definition at line 81 of file transformers.h.
Referenced by init(), and readConfig().
prop
PropagationEngine PropagatorRounding::prop
Definition at line 78 of file transformers.h.
Referenced by apply(), clear(), and init().
ranker
RankerPtr PropagatorRounding::ranker
Definition at line 80 of file transformers.h.
Referenced by apply(), ignoreGeneralIntegers(), init(), and readConfig().
state
StatePtr PropagatorRounding::state
Definition at line 77 of file transformers.h.
Referenced by apply(), clear(), and init().
The documentation for this class was generated from the following files:
FP2/feaspump/transformers.h
FP2/feaspump/transformers.cpp