BRKGA for MIP feasibility: ce_andrade::Clusterator Class Reference
ce_andrade::Clusterator Class Reference
Clusterator.
#include <clusterator.hpp>
Public Types
Enumerations
enum Metric {
Metric::L1, Metric::L2, Metric::WEIGHTED_L1, Metric::WEIGHTED_L2,
Metric::SHARED
}
This is the metric used to compute the distances.
enum ClusteringObject { ClusteringObject::VARIABLE, ClusteringObject::CONSTRAINT }
Indicates if the clusterization is done using variables or constraints.
Public Member Functions
Constructor and Destructor
Clusterator ()
Default Constructor.
~Clusterator ()
Destructor.
void buildIncidenceMatrices (const IloNumVarArray &variables, const IloRangeArray &constraints, std::string output_file_preffix=std::string())
std::shared_ptr< ClusterTree > hierarchicalClustering (const ClusteringObject type, const Metric metric)
Returns a binary tree describing the relationship between variables or constraints.
Protected Types
typedef Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor > IncidenceMatrix
A short name for the incidence matrices.
typedef PlainRaggedMatrix< double, IloInt > DistanceMatrix
A short name for distance matrices.
Protected Member Functions
void computeL1Distance (const IncidenceMatrix &matrix)
Compute the L1 norm distance, aka, Manhattan distance. The results are written on Clusterator::distance. THIS METHOD IS VERY TIME CONSUMING.
void computeL2Distance (const IncidenceMatrix &matrix)
Compute the L2 norm distance, aka, Euclidean distance. The results are written on Clusterator::distance. This computation can take a while due to its nature. This method uses the full advantages of Eigen library, using as much cores as available in the system.
Protected Attributes
IncidenceMatrix weighted_incidence_matrix
This matrix holds the constraint coefficients. It can see as the transpose of the original constraint matrix. We store it using column major scheme.
IncidenceMatrix incidence_matrix
The same as weighted_incidence_matrix, but it is a binary matrix indicating which variable belongs to each constraint.
DistanceMatrix variables_distance
This matrix holds the distance of two variables with respect to the number of constraints that they appear together. We assume that variables that not appear together have distance 0.0 within. Variables with maximum of sharings have distance 0.0. In other words, if MAX is the maximum number of sharings over all pairs of variables, the distance between variables a and b is dist(a, b) = 1 - sharing(a, b) / MAX. This matrix is stored in ragged form used old plain C arrays due to the C clustering library.
DistanceMatrix constraints_distance
This matrix holds the distance of two constraints with respect to the number of variables that they share. We assume that constraints that have variable in common have distance 0.0 within. Constraints with maximum of sharings have distance 0.0. In other words, if MAX is the maximum number of sharings over all pairs of constraints, the distance between constraints a and b is dist(a, b) = 1 - sharing(a, b) / MAX. This matrix is stored in ragged form used old plain C arrays due to the C clustering library.
DistanceMatrix metric_distance
This is a symmetric matrix with dimensions of number of variables or constraints depending of the current clustering. This is stored in ragged form used old plain C arrays due to the C clustering library.
IloInt num_vars
Number of variables.
IloInt num_ctrs
Number of constraints.
std::vector< std::string > variable_names
Holds the variable names.
std::vector< std::string > constraint_names
Holds the constraint names.
Private Member Functions
Clusterator (const Clusterator &)=delete
Clusterator & operator= (const Clusterator &)=delete
Detailed Description
Clusterator.
Author
Carlos Eduardo de Andrade ce.an.nosp@m.drad.nosp@m.e@gma.nosp@m.il.c.nosp@m.om
Date
2015
This class is a clustering machine for variables and constraints from a mixed integer programming. It uses hierarchical clustering to build the relationship between the objects. Since this classes uses large matrices to store the distances between objects, it allocate a lot o memory. It is a really good idea dispose an object of this class after use.
Todo:
Implement clustering for constraints.
Implement other types of clusterization.
Definition at line 64 of file clusterator.hpp.
Member Typedef Documentation
DistanceMatrix
typedef PlainRaggedMatrix<double, IloInt> ce_andrade::Clusterator::DistanceMatrix protected
A short name for distance matrices.
Definition at line 164 of file clusterator.hpp.
IncidenceMatrix
typedef Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> ce_andrade::Clusterator::IncidenceMatrix protected
A short name for the incidence matrices.
Type definitions
Definition at line 161 of file clusterator.hpp.
Member Enumeration Documentation
ClusteringObject
enum ce_andrade::Clusterator::ClusteringObject strong
Indicates if the clusterization is done using variables or constraints.
Enumerator
VARIABLE
Do variable clustering.
CONSTRAINT
Do constraint clustering.
Definition at line 105 of file clusterator.hpp.
Metric
enum ce_andrade::Clusterator::Metric strong
This is the metric used to compute the distances.
Enumerator
L1
This is the L1 norm, as known as Manhattan distance. It is computed over the features vectors of each object. If the object is a variable, the feature vector is the incidence vector of the variable, i.e., it indicates to which constraints the variable belongs. If the object is a constraint, the conversely is true.
L2
This is the L2 norm, as known as Euclidean distance. The same observations of L1 hold for L2 too.
WEIGHTED_L1
This is the L1 norm, as known as Manhattan distance. It is computed over the features vectors of each object. If the object is a variable, the feature vector represents the coefficients in the each constraint to which that variable belongs.
WEIGHTED_L2
This is the L2 norm, as known as Euclidean distance. The same observations of WEIGHTED_L1 hold for WEIGHTED_L2 too.
SHARED
This distance/dissimilarity is taken over the number of constraints (variables) that a pair of variables (constraints) have in common. We assume that objects that have nothing in common have distance 1.0. Objects with maximum of sharings have distance 0.0. In other words, if MAX is the maximum number of sharings over all pairs of objects, the distance between objects a and b is dist(a, b) = 1 - sharing(a, b) / MAX.
Definition at line 69 of file clusterator.hpp.
Constructor & Destructor Documentation
Clusterator() [1/2]
ce_andrade::Clusterator::Clusterator ()
Default Constructor.
Definition at line 48 of file clusterator.cpp.
~Clusterator()
ce_andrade::Clusterator::~Clusterator ()
Destructor.
Definition at line 62 of file clusterator.cpp.
Clusterator() [2/2]
ce_andrade::Clusterator::Clusterator (const Clusterator &) private delete
Member Function Documentation
buildIncidenceMatrices()
void ce_andrade::Clusterator::buildIncidenceMatrices (const IloNumVarArray & variables, const IloRangeArray & constraints, std::string output_file_preffix = std::string())
Preprocessing methods Brief Build the incidence matrices from CPLEX objects. These matrices are used as feature matrices to compute the distance/dissimilarity between the variables or constraints according to user choice. This method also computes the shared_contraints_var_distances matrix.
Parameters
variables MIP variables
constraints MIP constraints
output_file_preffix write the matrices on files with this preffix. If empty, the matrices are not written.x
Definition at line 66 of file clusterator.cpp.
References constraint_names, constraints_distance, ce_andrade::EPS, incidence_matrix, num_ctrs, num_vars, ce_andrade::PlainRaggedMatrix< DataType, IndexType >::resize(), variable_names, variables_distance, and weighted_incidence_matrix.
Referenced by main().
computeL1Distance()
void ce_andrade::Clusterator::computeL1Distance (const IncidenceMatrix & matrix) protected
Compute the L1 norm distance, aka, Manhattan distance. The results are written on Clusterator::distance. THIS METHOD IS VERY TIME CONSUMING.
Helper functions
Todo:
Find an algebraic form to compute L1 to used the Eigen parallel machinery.
Parameters
matrix of features to be used to compute the distances.
Definition at line 432 of file clusterator.cpp.
References metric_distance, and ce_andrade::PlainRaggedMatrix< DataType, IndexType >::resize().
Referenced by hierarchicalClustering().
computeL2Distance()
void ce_andrade::Clusterator::computeL2Distance (const IncidenceMatrix & matrix) protected
Compute the L2 norm distance, aka, Euclidean distance. The results are written on Clusterator::distance. This computation can take a while due to its nature. This method uses the full advantages of Eigen library, using as much cores as available in the system.
Parameters
matrix of features to be used to compute the distances.
Definition at line 453 of file clusterator.cpp.
References metric_distance, and ce_andrade::PlainRaggedMatrix< DataType, IndexType >::resize().
Referenced by hierarchicalClustering().
hierarchicalClustering()
std::shared_ptr< ClusterTree > ce_andrade::Clusterator::hierarchicalClustering (const ClusteringObject type, const Metric metric)
Returns a binary tree describing the relationship between variables or constraints.
Clustering methods
Parameters
type which type of object is to be clustered.
metric used to build the distance matrix.
Returns
a tree representing the clustering.
Definition at line 311 of file clusterator.cpp.
References computeL1Distance(), computeL2Distance(), CONSTRAINT, constraint_names, constraints_distance, incidence_matrix, L1, L2, metric_distance, ce_andrade::PlainRaggedMatrix< DataType, IndexType >::rawData(), SHARED, treecluster(), VARIABLE, variable_names, variables_distance, weighted_incidence_matrix, WEIGHTED_L1, and WEIGHTED_L2.
Referenced by main().
operator=()
Clusterator& ce_andrade::Clusterator::operator= (const Clusterator &) private delete
Member Data Documentation
constraint_names
std::vector<std::string> ce_andrade::Clusterator::constraint_names protected
Holds the constraint names.
Definition at line 221 of file clusterator.hpp.
Referenced by buildIncidenceMatrices(), and hierarchicalClustering().
constraints_distance
DistanceMatrix ce_andrade::Clusterator::constraints_distance protected
This matrix holds the distance of two constraints with respect to the number of variables that they share. We assume that constraints that have variable in common have distance 0.0 within. Constraints with maximum of sharings have distance 0.0. In other words, if MAX is the maximum number of sharings over all pairs of constraints, the distance between constraints a and b is dist(a, b) = 1 - sharing(a, b) / MAX. This matrix is stored in ragged form used old plain C arrays due to the C clustering library.
Definition at line 198 of file clusterator.hpp.
Referenced by buildIncidenceMatrices(), and hierarchicalClustering().
incidence_matrix
IncidenceMatrix ce_andrade::Clusterator::incidence_matrix protected
The same as weighted_incidence_matrix, but it is a binary matrix indicating which variable belongs to each constraint.
Definition at line 176 of file clusterator.hpp.
Referenced by buildIncidenceMatrices(), and hierarchicalClustering().
metric_distance
DistanceMatrix ce_andrade::Clusterator::metric_distance protected
This is a symmetric matrix with dimensions of number of variables or constraints depending of the current clustering. This is stored in ragged form used old plain C arrays due to the C clustering library.
Definition at line 203 of file clusterator.hpp.
Referenced by computeL1Distance(), computeL2Distance(), and hierarchicalClustering().
num_ctrs
IloInt ce_andrade::Clusterator::num_ctrs protected
Number of constraints.
Definition at line 212 of file clusterator.hpp.
Referenced by buildIncidenceMatrices().
num_vars
IloInt ce_andrade::Clusterator::num_vars protected
Number of variables.
Dimensions
Definition at line 209 of file clusterator.hpp.
Referenced by buildIncidenceMatrices().
variable_names
std::vector<std::string> ce_andrade::Clusterator::variable_names protected
Holds the variable names.
Other helper structure
Definition at line 218 of file clusterator.hpp.
Referenced by buildIncidenceMatrices(), and hierarchicalClustering().
variables_distance
DistanceMatrix ce_andrade::Clusterator::variables_distance protected
This matrix holds the distance of two variables with respect to the number of constraints that they appear together. We assume that variables that not appear together have distance 0.0 within. Variables with maximum of sharings have distance 0.0. In other words, if MAX is the maximum number of sharings over all pairs of variables, the distance between variables a and b is dist(a, b) = 1 - sharing(a, b) / MAX. This matrix is stored in ragged form used old plain C arrays due to the C clustering library.
Definition at line 187 of file clusterator.hpp.
Referenced by buildIncidenceMatrices(), and hierarchicalClustering().
weighted_incidence_matrix
IncidenceMatrix ce_andrade::Clusterator::weighted_incidence_matrix protected
This matrix holds the constraint coefficients. It can see as the transpose of the original constraint matrix. We store it using column major scheme.
The matrices
Definition at line 172 of file clusterator.hpp.
Referenced by buildIncidenceMatrices(), and hierarchicalClustering().
The documentation for this class was generated from the following files:
clustering/clusterator.hpp
clustering/clusterator.cpp