BRKGA for MIP feasibility: dominiqs::Chrono Class Reference
dominiqs::Chrono Class Reference
#include <chrono.h>
Public Types
enum ClockType { CPU_TIME, WALL_CLOCK }
Public Member Functions
Chrono (bool autoStart=false)
void start ()
void stop ()
void reset ()
ClockType getDefaultType () const
void setDefaultType (ClockType type)
double getPartial () const
double getTotal () const
double getElapsed () const
double getCPUPartial () const
double getCPUTotal () const
double getCPUElapsed () const
double getWallPartial () const
double getWallTotal () const
double getWallElapsed () const
Static Private Member Functions
static void CpuTime (double &user_time, double &sys_time)
static void WallTime (double &time)
Private Attributes
double u_begin
double u_end
double u_total
double s_begin
double s_end
double s_total
double w_begin
double w_end
double w_total
ClockType defaultTime
Detailed Description
Benchmarking class Simulates a simple stopwatch Measures the CPU time used by a process and the wall clock time
Definition at line 22 of file chrono.h.
Member Enumeration Documentation
ClockType
enum dominiqs::Chrono::ClockType
Enumerator
CPU_TIME
WALL_CLOCK
Definition at line 25 of file chrono.h.
Constructor & Destructor Documentation
Chrono()
dominiqs::Chrono::Chrono (bool autoStart = false) inline
default constructor
Definition at line 76 of file chrono.h.
References start().
Member Function Documentation
CpuTime()
void dominiqs::Chrono::CpuTime (double & user_time, double & sys_time) static private
Definition at line 21 of file chrono.cpp.
Referenced by getCPUElapsed(), start(), and stop().
getCPUElapsed()
double dominiqs::Chrono::getCPUElapsed () const inline
Returns
elapsed CPU time in seconds
Definition at line 151 of file chrono.h.
References CpuTime(), s_begin, and u_begin.
Referenced by getElapsed().
getCPUPartial()
double dominiqs::Chrono::getCPUPartial () const inline
Returns
partial elapsed CPU time in seconds
Definition at line 141 of file chrono.h.
References s_begin, s_end, u_begin, and u_end.
Referenced by getPartial().
getCPUTotal()
double dominiqs::Chrono::getCPUTotal () const inline
Returns
total elapsed CPU time in seconds
Definition at line 146 of file chrono.h.
References s_total, and u_total.
Referenced by getTotal().
getDefaultType()
Chrono::ClockType dominiqs::Chrono::getDefaultType () const inline
get/set default clock type
Definition at line 113 of file chrono.h.
References defaultTime.
getElapsed()
double dominiqs::Chrono::getElapsed () const inline
Returns
elapsed time in seconds (according to default type)
Definition at line 135 of file chrono.h.
References CPU_TIME, defaultTime, getCPUElapsed(), and getWallElapsed().
Referenced by dominiqs::FeasibilityPump::foundIncumbent(), dominiqs::FeasibilityPump::solveInitialLP(), dominiqs::FeasibilityPump::stage1(), dominiqs::FeasibilityPump::stage2(), and dominiqs::FeasibilityPump::stage3().
getPartial()
double dominiqs::Chrono::getPartial () const inline
Returns
partial elapsed time in seconds (according to default type)
Definition at line 123 of file chrono.h.
References CPU_TIME, defaultTime, getCPUPartial(), and getWallPartial().
Referenced by dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
getTotal()
double dominiqs::Chrono::getTotal () const inline
Returns
total elapsed time in seconds (according to default type)
Definition at line 129 of file chrono.h.
References CPU_TIME, defaultTime, getCPUTotal(), and getWallTotal().
Referenced by dominiqs::CpxPresolver::exec(), dominiqs::GomorySeparator::logStats(), and dominiqs::FeasibilityPump::pump().
getWallElapsed()
double dominiqs::Chrono::getWallElapsed () const inline
Returns
elapsed wall clock time in seconds
Definition at line 168 of file chrono.h.
References w_begin, and WallTime().
Referenced by getElapsed().
getWallPartial()
double dominiqs::Chrono::getWallPartial () const inline
Returns
partial elapsed wall clock time in seconds
Definition at line 158 of file chrono.h.
References w_begin, and w_end.
Referenced by getPartial().
getWallTotal()
double dominiqs::Chrono::getWallTotal () const inline
Returns
total elapsed wall clock time in seconds
Definition at line 163 of file chrono.h.
References w_total.
Referenced by getTotal().
reset()
void dominiqs::Chrono::reset () inline
reset stopwatch
Definition at line 100 of file chrono.h.
References s_begin, s_end, s_total, u_begin, u_end, u_total, w_begin, w_end, and w_total.
Referenced by dominiqs::FeasibilityPump::reset().
setDefaultType()
void dominiqs::Chrono::setDefaultType (ClockType type) inline
Definition at line 118 of file chrono.h.
References defaultTime.
Referenced by main(), and dominiqs::FeasibilityPump::reset().
start()
void dominiqs::Chrono::start () inline
start stopwatch
Definition at line 85 of file chrono.h.
References CpuTime(), s_begin, u_begin, w_begin, and WallTime().
Referenced by dominiqs::GomorySeparator::applyGMI(), dominiqs::AutoChrono::AutoChrono(), dominiqs::GomorySeparator::backSubstitute(), dominiqs::GomorySeparator::calculateTableauRow(), Chrono(), dominiqs::CpxPresolver::exec(), dominiqs::GlobalAutoChrono::GlobalAutoChrono(), main(), dominiqs::FeasibilityPump::pump(), dominiqs::GomorySeparator::separateGMI(), dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
stop()
void dominiqs::Chrono::stop () inline
stop stopwatch
Definition at line 91 of file chrono.h.
References CpuTime(), s_begin, s_end, s_total, u_begin, u_end, u_total, w_begin, w_end, w_total, and WallTime().
Referenced by dominiqs::GomorySeparator::applyGMI(), dominiqs::GomorySeparator::backSubstitute(), dominiqs::GomorySeparator::calculateTableauRow(), dominiqs::CpxPresolver::exec(), main(), dominiqs::FeasibilityPump::pump(), dominiqs::GomorySeparator::separateGMI(), dominiqs::FeasibilityPump::stage1(), dominiqs::FeasibilityPump::stage2(), dominiqs::AutoChrono::stop(), and dominiqs::GlobalAutoChrono::stop().
WallTime()
void dominiqs::Chrono::WallTime (double & time) static private
Definition at line 34 of file chrono.cpp.
Referenced by getWallElapsed(), start(), and stop().
Member Data Documentation
defaultTime
ClockType dominiqs::Chrono::defaultTime private
Definition at line 73 of file chrono.h.
Referenced by getDefaultType(), getElapsed(), getPartial(), getTotal(), and setDefaultType().
s_begin
double dominiqs::Chrono::s_begin private
Definition at line 64 of file chrono.h.
Referenced by getCPUElapsed(), getCPUPartial(), reset(), start(), and stop().
s_end
double dominiqs::Chrono::s_end private
Definition at line 64 of file chrono.h.
Referenced by getCPUPartial(), reset(), and stop().
s_total
double dominiqs::Chrono::s_total private
Definition at line 64 of file chrono.h.
Referenced by getCPUTotal(), reset(), and stop().
u_begin
double dominiqs::Chrono::u_begin private
Definition at line 62 of file chrono.h.
Referenced by getCPUElapsed(), getCPUPartial(), reset(), start(), and stop().
u_end
double dominiqs::Chrono::u_end private
Definition at line 62 of file chrono.h.
Referenced by getCPUPartial(), reset(), and stop().
u_total
double dominiqs::Chrono::u_total private
Definition at line 62 of file chrono.h.
Referenced by getCPUTotal(), reset(), and stop().
w_begin
double dominiqs::Chrono::w_begin private
Definition at line 69 of file chrono.h.
Referenced by getWallElapsed(), getWallPartial(), reset(), start(), and stop().
w_end
double dominiqs::Chrono::w_end private
Definition at line 69 of file chrono.h.
Referenced by getWallPartial(), reset(), and stop().
w_total
double dominiqs::Chrono::w_total private
Definition at line 69 of file chrono.h.
Referenced by getWallTotal(), reset(), and stop().
The documentation for this class was generated from the following files:
FP2/utils/chrono.h
FP2/utils/chrono.cpp