BRKGA for MIP feasibility: FP2/feaspump/feaspump.cpp File Reference
feaspump.cpp File Reference
Feasibility Pump algorithm Source.
#include <map>
#include <signal.h>
#include <cmath>
#include <numeric>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <algorithm>
#include <boost/assign/std/vector.hpp>
#include <boost/format.hpp>
#include <boost/iterator/transform_iterator.hpp>
#include <utils/asserter.h>
#include <utils/floats.h>
#include <utils/maths.h>
#include <utils/logger.h>
#include <utils/xmlconfig.h>
#include "feaspump.h"
Namespaces
dominiqs
Macros
#define MYLOG(flag, actions) do { if (flag) { actions } } while(false);
#define READ_FROM_CONFIG(what, defValue) what = gConfig().get("FeasibilityPump", #what, defValue)
#define LOG_CONFIG(what) gLog().logItem(#what, what)
Functions
void userSignalBreak (int signum)
static bool isSolutionInteger (const std::vector< int > &integers, const std::vector< double > &x, double eps)
static double solutionFractionality (const std::vector< int > &integers, const std::vector< double > &x)
static int solutionNumFractional (const std::vector< int > &integers, const std::vector< double > &x, double eps)
static double solutionsDistance (const std::vector< int > &integers, const std::vector< double > &x1, const std::vector< double > &x2)
static bool areSolutionsEqual (const std::vector< int > &integers, const std::vector< double > &x1, const std::vector< double > &x2, double eps)
template<class T >
std::ostream & dominiqs::operator<< (std::ostream &out, const std::vector< T > &v)
Variables
int AbortOptimization = 0
static const double dominiqs::DEF_TIME_LIMIT = 7200.0
static const int dominiqs::DEF_S1_ITER_LIMIT = 10000
static const int dominiqs::DEF_ITER_LIMIT = 2000
static const int dominiqs::DEF_S1_MAX_MISSED_DECREASE = 30
static const int dominiqs::DEF_MAX_MISSED_DECREASE = 50
static const int dominiqs::DEF_MAX_RESTARTS = 100
static const int dominiqs::DEF_AVG_FLIPS = 20
static const double dominiqs::DEF_INTEGRALITY_EPS = 1e-6
static const uint64_t dominiqs::DEF_SEED = 120507
static const double dominiqs::DEF_SIGMA_THR = 0.02
static const bool dominiqs::DEF_PERTURBE_FROM_TRANSFORMER_OUTPUT = true
static const double dominiqs::DEF_ALPHA = 0.0
static const double dominiqs::DEF_ALPHA_FACTOR = 0.9
static const double dominiqs::DEF_ALPHA_DIST = 0.005
static const bool dominiqs::DEF_DO_STAGE_3 = true
static const char dominiqs::DEF_FIRST_OPT_METHOD = 'S'
static const int dominiqs::DEF_OPT_ITER_LIMIT = -1
static const char dominiqs::DEF_REOPT_METHOD = 'S'
static const int dominiqs::DEF_REOPT_ITER_LIMIT = -1
static const bool dominiqs::DEF_LOG_PERTURBATION = false
static const bool dominiqs::DEF_LOG_DETAILS = false
static const bool dominiqs::DEF_LOG_ITERATION = false
static const bool dominiqs::DEF_LOG_TIME = false
static const bool dominiqs::DEF_LOG_LP = false
static const int dominiqs::EXTENDED_PRECISION = 4
static const double dominiqs::GEOM_FACTOR = 0.85
static const double dominiqs::BIGM = 1e9
static const double dominiqs::BIGBIGM = 1e15
Detailed Description
Feasibility Pump algorithm Source.
Author
Domenico Salvagnin <dominiqs at="" gmail="" dot="" com>=""> 2008
Definition in file feaspump.cpp.
Macro Definition Documentation
LOG_CONFIG
#define LOG_CONFIG (what) gLog().logItem(#what, what)
Definition at line 37 of file feaspump.cpp.
MYLOG
#define MYLOG (flag, actions) do { if (flag) { actions } } while(false);
Definition at line 35 of file feaspump.cpp.
READ_FROM_CONFIG
#define READ_FROM_CONFIG (what, defValue) what = gConfig().get("FeasibilityPump", #what, defValue)
Definition at line 36 of file feaspump.cpp.
Function Documentation
areSolutionsEqual()
static bool areSolutionsEqual (const std::vector< int > & integers, const std::vector< double > & x1, const std::vector< double > & x2, double eps) static
Definition at line 77 of file feaspump.cpp.
References dominiqs::different().
Referenced by dominiqs::FeasibilityPump::isInCache(), dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
isSolutionInteger()
static bool isSolutionInteger (const std::vector< int > & integers, const std::vector< double > & x, double eps) static
Definition at line 50 of file feaspump.cpp.
References dominiqs::isInteger().
Referenced by dominiqs::FeasibilityPump::stage1(), dominiqs::FeasibilityPump::stage2(), and dominiqs::FeasibilityPump::stage3().
solutionFractionality()
static double solutionFractionality (const std::vector< int > & integers, const std::vector< double > & x) static
Definition at line 56 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
solutionNumFractional()
static int solutionNumFractional (const std::vector< int > & integers, const std::vector< double > & x, double eps) static
Definition at line 63 of file feaspump.cpp.
References dominiqs::isInteger().
Referenced by dominiqs::FeasibilityPump::pump(), dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
solutionsDistance()
static double solutionsDistance (const std::vector< int > & integers, const std::vector< double > & x1, const std::vector< double > & x2) static
Definition at line 70 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
userSignalBreak()
void userSignalBreak (int signum)
Definition at line 45 of file feaspump.cpp.
References AbortOptimization.
Variable Documentation
AbortOptimization
int AbortOptimization = 0
Ctrl-C handling
Definition at line 43 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::pump(), dominiqs::FeasibilityPump::stage1(), dominiqs::FeasibilityPump::stage2(), dominiqs::FeasibilityPump::stage3(), and userSignalBreak().