BRKGA for MIP feasibility: FP2/feaspump/main.cpp File Reference
main.cpp File Reference
Main App.
#include <iostream>
#include <iomanip>
#include <sstream>
#include <fstream>
#include <boost/format.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string/erase.hpp>
#include <utils/args_parser.h>
#include <utils/xmlconfig.h>
#include <utils/config.h>
#include <utils/path.h>
#include <utils/floats.h>
#include <utils/chrono.h>
#include <utils/randgen.h>
#include <utils/logger.h>
#include "feaspump.h"
Classes
struct MyData
struct SlotIncumbent
Macros
#define LOG_START_SECTION(name) gLog().startSection(name)
#define LOG_END_SECTION() gLog().endSection()
#define LOG_ITEM(name, var) gLog().logItem(name, var)
#define LOG_MSG(msg) gLog().logMsg(msg)
#define LOG_CONFIG(what) LOG_ITEM(#what, what)
Functions
Prob presolve (Env env, Prob lp, MyData &data, const std::string &path)
int main (int argc, char const *argv[])
Variables
static const char * FP_VERSION = "2.1"
static const uint64_t DEF_SEED = 120507
Detailed Description
Main App.
Author
Domenico Salvagnin <dominiqs at="" gmail="" dot="" com>=""> 2008
Definition in file main.cpp.
Macro Definition Documentation
LOG_CONFIG
#define LOG_CONFIG (what) LOG_ITEM(#what, what)
Definition at line 37 of file main.cpp.
LOG_END_SECTION
#define LOG_END_SECTION () gLog().endSection()
Definition at line 34 of file main.cpp.
LOG_ITEM
#define LOG_ITEM (name, var) gLog().logItem(name, var)
Definition at line 35 of file main.cpp.
LOG_MSG
#define LOG_MSG (msg) gLog().logMsg(msg)
Definition at line 36 of file main.cpp.
LOG_START_SECTION
#define LOG_START_SECTION (name) gLog().startSection(name)
Definition at line 33 of file main.cpp.
Function Documentation
main()
int main (int argc, char const * argv[])
Definition at line 148 of file main.cpp.
References CHECKED_CPX_CALL, dominiqs::Logger::close(), DECL_ENV, DECL_PROB, DEF_SEED, DOMINIQS_ASSERT, dominiqs::dotProduct(), dominiqs::FeasibilityPump::emitNewIncumbent, dominiqs::FeasibilityPump::finalStage, MyData::firstIt, MyData::firstTime, MyData::firstValue, MyData::foundSolution, FP_VERSION, FREE_ENV, FREE_PROB, dominiqs::gChrono(), dominiqs::gConfig(), dominiqs::generateSeed(), dominiqs::XMLConfig::get(), dominiqs::Path::getBasename(), dominiqs::FeasibilityPump::getSolution(), dominiqs::getVarNames(), GIT_HASH, dominiqs::gLog(), MyData::hasPresolve, dominiqs::FeasibilityPump::init(), dominiqs::ArgsParser::input, dominiqs::isNotNull(), MyData::lastIt, MyData::lastTime, MyData::lastValue, LOG_END_SECTION, LOG_ITEM, LOG_MSG, LOG_START_SECTION, dominiqs::Logger::logMsg(), dominiqs::mergeConfig(), dominiqs::Logger::open(), dominiqs::ArgsParser::parse(), presolve(), dominiqs::FeasibilityPump::pump(), dominiqs::FeasibilityPump::readConfig(), dominiqs::relEqual(), dominiqs::FeasibilityPump::reset(), dominiqs::XMLConfig::set(), dominiqs::Logger::setConsoleEcho(), dominiqs::Chrono::setDefaultType(), dominiqs::Chrono::start(), dominiqs::Chrono::stop(), and dominiqs::FeasibilityPump::totalTime.
presolve()
Prob presolve (Env env, Prob lp, MyData & data, const std::string & path)
Definition at line 82 of file main.cpp.
References CHECKED_CPX_CALL, DECL_PROB, FREE_PROB, MyData::hasPresolve, LOG_END_SECTION, LOG_ITEM, LOG_MSG, LOG_START_SECTION, MyData::objSense, and MyData::offset.
Referenced by main().
Variable Documentation
DEF_SEED
const uint64_t DEF_SEED = 120507 static
Definition at line 146 of file main.cpp.
Referenced by main().
FP_VERSION
const char* FP_VERSION = "2.1" static
Definition at line 145 of file main.cpp.
Referenced by main().