BRKGA for MIP feasibility: test_decoder.cpp File Reference
test_decoder.cpp File Reference
#include "feasibility_pump_decoder.hpp"
#include "mtrand.hpp"
#include "population.hpp"
#include <iostream>
#include <fstream>
#include <iomanip>
#include <stdexcept>
#include <algorithm>
#include <vector>
#include <set>
#include <functional>
#include <boost/timer/timer.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string.hpp>
#include "pragma_diagnostic_ignored_header.hpp"
#include <cstring>
#include <ilcplex/ilocplex.h>
#include "pragma_diagnostic_ignored_footer.hpp"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 56 of file test_decoder.cpp.
References FeasibilityPump_Decoder::ALL, FeasibilityPump_Decoder::AUTOMATIC, FeasibilityPump_Decoder::CONVEX, FeasibilityPump_Decoder::init(), FeasibilityPump_Decoder::OBJECTIVE, MTRand::rand(), and BRKGA_ALG::Population::setFitness().