BRKGA for MIP feasibility: dominiqs::AutoChrono Class Reference
dominiqs::AutoChrono Class Reference
#include <chrono.h>
Public Member Functions
AutoChrono (Chrono *c)
~AutoChrono ()
void stop ()
Private Attributes
Chrono * theChrono
bool pending
Detailed Description
Automatic stopwatch stopper (RAII principle)
Definition at line 185 of file chrono.h.
Constructor & Destructor Documentation
AutoChrono()
dominiqs::AutoChrono::AutoChrono (Chrono * c) inline
Definition at line 188 of file chrono.h.
References DOMINIQS_ASSERT, dominiqs::Chrono::start(), and theChrono.
~AutoChrono()
dominiqs::AutoChrono::~AutoChrono () inline
Definition at line 193 of file chrono.h.
References stop().
Member Function Documentation
stop()
void dominiqs::AutoChrono::stop () inline
Definition at line 194 of file chrono.h.
References pending, dominiqs::Chrono::stop(), and theChrono.
Referenced by ~AutoChrono().
Member Data Documentation
pending
bool dominiqs::AutoChrono::pending private
Definition at line 204 of file chrono.h.
Referenced by stop().
theChrono
Chrono* dominiqs::AutoChrono::theChrono private
Definition at line 203 of file chrono.h.
Referenced by AutoChrono(), and stop().
The documentation for this class was generated from the following file:
FP2/utils/chrono.h