BRKGA for MIP feasibility: dominiqs::WarmStart Class Reference
dominiqs::WarmStart Class Reference
#include <cpxutils.h>
Public Member Functions
void read (CEnv env, CProb lp)
void write (Env env, Prob lp)
Public Attributes
dominiqs::numarray< int > cstat
dominiqs::numarray< int > rstat
Detailed Description
WarmStart management class
Definition at line 107 of file cpxutils.h.
Member Function Documentation
read()
void dominiqs::WarmStart::read (CEnv env, CProb lp)
Definition at line 227 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
Referenced by dominiqs::GomorySeparator::refactor(), and dominiqs::GomorySeparator::setX().
write()
void dominiqs::WarmStart::write (Env env, Prob lp)
Definition at line 236 of file cpxutils.cpp.
References CHECKED_CPX_CALL, and DOMINIQS_ASSERT.
Referenced by dominiqs::GomorySeparator::refactor().
Member Data Documentation
cstat
dominiqs::numarray<int> dominiqs::WarmStart::cstat
Definition at line 113 of file cpxutils.h.
Referenced by dominiqs::GomorySeparator::setX().
rstat
dominiqs::numarray<int> dominiqs::WarmStart::rstat
Definition at line 114 of file cpxutils.h.
The documentation for this class was generated from the following files:
FP2/cpxutils/cpxutils.h
FP2/cpxutils/cpxutils.cpp