BRKGA for MIP feasibility: BRKGA_ALG::Population Class Reference
BRKGA_ALG::Population Class Reference
Encapsulates a population of chromosomes represented by a vector of doubles.
#include <population.hpp>
Public Member Functions
void setType (unsigned chromosome, Chromosome::ChromosomeType type)
void sortFitness (bool maximize)
void setFitness (unsigned i, double f)
Chromosome & getChromosome (unsigned i)
Returns a chromosome.
Allele & operator() (unsigned i, unsigned j)
Direct access to allele j of chromosome i.
Chromosome & operator() (unsigned i)
Direct access to chromosome i.
Default constructors and destructor
Population (const Population &other)
Copy constructor.
Population (unsigned n, unsigned p)
~Population ()
Destructor.
unsigned getN () const
Return the size of each chromosome.
unsigned getP () const
Return the size of the population.
Allele operator() (unsigned i, unsigned j) const
Direct access to allele j of chromosome i.
double getBestFitness () const
Returns the best fitness in this population.
double getFitness (unsigned i) const
Returns the fitness of chromosome i.
const Chromosome & getChromosome (unsigned i) const
Returns i-th best chromosome.
Public Attributes
std::vector< Chromosome > population
Population as vectors of probabilities.
std::vector< std::pair< double, unsigned > > fitness
Fitness (double) of a each chromosome.
Friends
template<class Decoder , class RNG >
class BRKGA
Detailed Description
Encapsulates a population of chromosomes represented by a vector of doubles.
This software is based on the work of Rodrigo Franco Toso, available at https://github.com/rfrancotoso/brkgaAPI. The most parts of the code are from the original work with minor refactoring.
Original note from rtoso: Encapsulates a population of chromosomes represented by a vector of doubles. We don't decode nor deal with random numbers here; instead, we provide private support methods to set the fitness of a specific chromosome as well as access methods to each allele. Note that the BRKGA class must have access to such methods and thus is a friend.
Author
Carlos Eduardo de Andrade ce.an.nosp@m.drad.nosp@m.e@gma.nosp@m.il.c.nosp@m.om
Rodrigo Franco Toso rtoso.nosp@m.@cs..nosp@m.rutge.nosp@m.rs.e.nosp@m.du
Date
2015
Definition at line 58 of file population.hpp.
Constructor & Destructor Documentation
Population() [1/2]
BRKGA_ALG::Population::Population (const Population & other)
Copy constructor.
Definition at line 38 of file population.cpp.
Population() [2/2]
BRKGA_ALG::Population::Population (unsigned n, unsigned p)
Default constructor
Parameters
n size of chromosome
p size of population
Definition at line 43 of file population.cpp.
~Population()
BRKGA_ALG::Population::~Population ()
Destructor.
Definition at line 53 of file population.cpp.
Member Function Documentation
getBestFitness()
double BRKGA_ALG::Population::getBestFitness () const
Returns the best fitness in this population.
Special access methods
These methods REQUIRE fitness to be sorted, and thus a call to sortFitness() beforehand.
Definition at line 63 of file population.cpp.
References getFitness().
getChromosome() [1/2]
const Chromosome & BRKGA_ALG::Population::getChromosome (unsigned i) const
Returns i-th best chromosome.
Definition at line 71 of file population.cpp.
References fitness, and population.
Referenced by FeasibilityPump_Decoder::addCutsFromRoudings(), FeasibilityPump_Decoder::analyzeAndFixVars(), main(), and FeasibilityPump_Decoder::performMIPLocalSearch().
getChromosome() [2/2]
Chromosome & BRKGA_ALG::Population::getChromosome (unsigned i)
Returns a chromosome.
Definition at line 75 of file population.cpp.
References fitness, and population.
getFitness()
double BRKGA_ALG::Population::getFitness (unsigned i) const
Returns the fitness of chromosome i.
Definition at line 67 of file population.cpp.
References fitness.
Referenced by getBestFitness().
getN()
unsigned BRKGA_ALG::Population::getN () const
Return the size of each chromosome.
Simple access methods
Definition at line 55 of file population.cpp.
References population.
Referenced by FeasibilityPump_Decoder::analyzeAndFixVars().
getP()
unsigned BRKGA_ALG::Population::getP () const
Return the size of the population.
Definition at line 59 of file population.cpp.
References population.
Referenced by FeasibilityPump_Decoder::addCutsFromRoudings(), and main().
operator()() [1/3]
Allele BRKGA_ALG::Population::operator() (unsigned i, unsigned j) const
Direct access to allele j of chromosome i.
Definition at line 84 of file population.cpp.
References population.
operator()() [2/3]
Allele & BRKGA_ALG::Population::operator() (unsigned i, unsigned j)
Direct access to allele j of chromosome i.
Definition at line 88 of file population.cpp.
References population.
operator()() [3/3]
Chromosome & BRKGA_ALG::Population::operator() (unsigned i)
Direct access to chromosome i.
Definition at line 92 of file population.cpp.
References population.
setFitness()
void BRKGA_ALG::Population::setFitness (unsigned i, double f)
Sets the fitness of chromosome
Parameters
i index of chromosome
f value
Definition at line 79 of file population.cpp.
References fitness.
Referenced by BRKGA_ALG::BRKGA< Decoder, RNG >::evolution(), and main().
setType()
void BRKGA_ALG::Population::setType (unsigned chromosome, Chromosome::ChromosomeType type)
Set the type of chromosome
Parameters
chromosome index of chromosome
type type of chromosome
Definition at line 103 of file population.cpp.
References population.
Referenced by BRKGA_ALG::BRKGA< Decoder, RNG >::evolution().
sortFitness()
void BRKGA_ALG::Population::sortFitness (bool maximize)
Sorts 'fitness' by its first parameter by predicate template class.
Parameters
maximize if true, sort in non-increasing order.
Definition at line 96 of file population.cpp.
References fitness, and sort().
Referenced by BRKGA_ALG::BRKGA< Decoder, RNG >::evolution().
Friends And Related Function Documentation
BRKGA
template<class Decoder , class RNG > friend class BRKGA friend
Definition at line 60 of file population.hpp.
Member Data Documentation
fitness
std::vector<std::pair<double, unsigned> > BRKGA_ALG::Population::fitness
Fitness (double) of a each chromosome.
Definition at line 118 of file population.hpp.
Referenced by BRKGA_ALG::BRKGA< Decoder, RNG >::evolution(), getChromosome(), getFitness(), BRKGA_ALG::BRKGA< Decoder, RNG >::initialize(), setFitness(), and sortFitness().
population
std::vector<Chromosome> BRKGA_ALG::Population::population
Population as vectors of probabilities.
Definition at line 115 of file population.hpp.
Referenced by BRKGA_ALG::BRKGA< Decoder, RNG >::evolution(), getChromosome(), getN(), getP(), BRKGA_ALG::BRKGA< Decoder, RNG >::initialize(), operator()(), and setType().
The documentation for this class was generated from the following files:
brkga/population.hpp
brkga/population.cpp