BRKGA for MIP feasibility: dominiqs::XmlDoc Class Reference
dominiqs::XmlDoc Class Reference
#include <myxml.h>
Public Member Functions
XmlDoc (xmlDocPtr d=0)
~XmlDoc ()
void read (const std::string &filename)
void write (const std::string &filename) const
XmlNode getRoot ()
XmlNode setRoot (const std::string &name, const AttributeMap &attrs=AttributeMap())
void xpath (const std::string &xpathExpr, std::vector< XmlNode > &res) const
XmlNode xpath (const std::string &xpathExpr) const
Protected Member Functions
void free ()
Protected Attributes
xmlDocPtr doc
Private Member Functions
XmlDoc & operator= (const XmlDoc &rhs)
XmlDoc (const XmlDoc &rhs)
Detailed Description
C++ Wrapper aroung libxml xmlDocPtr Represents an XML document
Definition at line 62 of file myxml.h.
Constructor & Destructor Documentation
XmlDoc() [1/2]
dominiqs::XmlDoc::XmlDoc (xmlDocPtr d = 0) inline
Definition at line 65 of file myxml.h.
~XmlDoc()
dominiqs::XmlDoc::~XmlDoc ()
Definition at line 155 of file myxml.cpp.
References doc, and free().
XmlDoc() [2/2]
dominiqs::XmlDoc::XmlDoc (const XmlDoc & rhs) private
Member Function Documentation
free()
void dominiqs::XmlDoc::free () protected
Definition at line 171 of file myxml.cpp.
References doc.
Referenced by read(), setRoot(), and ~XmlDoc().
getRoot()
XmlNode dominiqs::XmlDoc::getRoot ()
Definition at line 177 of file myxml.cpp.
References doc.
operator=()
XmlDoc& dominiqs::XmlDoc::operator= (const XmlDoc & rhs) private
read()
void dominiqs::XmlDoc::read (const std::string & filename)
Definition at line 160 of file myxml.cpp.
References doc, and free().
Referenced by dominiqs::XMLConfig::load().
setRoot()
XmlNode dominiqs::XmlDoc::setRoot (const std::string & name, const AttributeMap & attrs = AttributeMap())
Definition at line 182 of file myxml.cpp.
References doc, and free().
Referenced by dominiqs::XMLConfig::save().
write()
void dominiqs::XmlDoc::write (const std::string & filename) const
Definition at line 166 of file myxml.cpp.
References doc.
Referenced by dominiqs::XMLConfig::save().
xpath() [1/2]
void dominiqs::XmlDoc::xpath (const std::string & xpathExpr, std::vector< XmlNode > & res) const
Definition at line 198 of file myxml.cpp.
References doc.
Referenced by dominiqs::XMLConfig::load(), and xpath().
xpath() [2/2]
XmlNode dominiqs::XmlDoc::xpath (const std::string & xpathExpr) const
Definition at line 213 of file myxml.cpp.
References xpath().
Member Data Documentation
doc
xmlDocPtr dominiqs::XmlDoc::doc protected
Definition at line 78 of file myxml.h.
Referenced by free(), getRoot(), read(), setRoot(), write(), xpath(), and ~XmlDoc().
The documentation for this class was generated from the following files:
FP2/utils/myxml.h
FP2/utils/myxml.cpp