BRKGA for MIP feasibility: dominiqs::XMLConfig Class Reference
dominiqs::XMLConfig Class Reference
#include <xmlconfig.h>
Public Member Functions
template<>
std::string get (const std::string &cat, const std::string &entry, const std::string &defValue) const
template<>
void set (const std::string &cat, const std::string &entry, const std::string &value)
bool load (const std::string &fileName, bool merge=true)
void save (const std::string &fileName) const
template<typename T >
T get (const std::string &cat, const std::string &entry, const T &defValue) const
template<typename T >
void set (const std::string &cat, const std::string &entry, const T &value)
Private Types
typedef std::map< std::string, XMLCategoryPtr > XMLCategoryMap
Private Member Functions
std::string getAsString (const std::string &cat, const std::string &entry, const std::string &defValue) const
void setAsString (const std::string &cat, const std::string &entry, const std::string &value)
Private Attributes
XMLCategoryMap categories
Detailed Description
Config File Reader/Writer
Definition at line 41 of file xmlconfig.h.
Member Typedef Documentation
XMLCategoryMap
typedef std::map<std::string, XMLCategoryPtr> dominiqs::XMLConfig::XMLCategoryMap private
Definition at line 71 of file xmlconfig.h.
Member Function Documentation
get() [1/2]
template<typename T > T dominiqs::XMLConfig::get (const std::string & cat, const std::string & entry, const T & defValue) const inline
typed wrapper around get/set
Definition at line 61 of file xmlconfig.h.
References getAsString().
Referenced by main(), dominiqs::App::parseArgsAndConfig(), dominiqs::GomorySeparator::readConfig(), dominiqs::FeasibilityPump::readConfig(), dominiqs::CPXApp::readConfig(), SimpleRounding::readConfig(), PropagatorRounding::readConfig(), FractionalityRanker::readConfig(), RandomRanker::readConfig(), dominiqs::CutPool::readConfig(), and dominiqs::App::run().
get() [2/2]
std::string dominiqs::XMLConfig::get (const std::string & cat, const std::string & entry, const std::string & defValue) const
template specialization of get/set for std::string
Definition at line 101 of file xmlconfig.cpp.
References getAsString().
getAsString()
std::string dominiqs::XMLConfig::getAsString (const std::string & cat, const std::string & entry, const std::string & defValue) const private
std::string get/set Get the value of a parameter
Parameters
Definition at line 83 of file xmlconfig.cpp.
References categories.
Referenced by get().
load()
bool dominiqs::XMLConfig::load (const std::string & fileName, bool merge = true)
File I/O Load Config from an XML file
Parameters
fileName file to load
merge merges with current contents if set to true, replaces otherwise
Definition at line 36 of file xmlconfig.cpp.
References categories, dominiqs::XmlNode::data(), DOMINIQS_ASSERT, dominiqs::XmlNode::firstChild(), dominiqs::XmlNode::isNull(), dominiqs::XmlNode::name(), dominiqs::XmlNode::next(), dominiqs::XmlDoc::read(), and dominiqs::XmlDoc::xpath().
Referenced by dominiqs::mergeConfig().
save()
void dominiqs::XMLConfig::save (const std::string & fileName) const
Save configuration to an XML file
Parameters
fileName file to save
Definition at line 65 of file xmlconfig.cpp.
References dominiqs::XmlNode::addChild(), categories, dominiqs::XmlNode::name(), dominiqs::XmlDoc::setRoot(), and dominiqs::XmlDoc::write().
set() [1/2]
template<typename T > void dominiqs::XMLConfig::set (const std::string & cat, const std::string & entry, const T & value) inline
Definition at line 65 of file xmlconfig.h.
References setAsString().
Referenced by main(), dominiqs::mergeConfig(), and dominiqs::App::run().
set() [2/2]
void dominiqs::XMLConfig::set (const std::string & cat, const std::string & entry, const std::string & value)
Definition at line 106 of file xmlconfig.cpp.
References setAsString().
setAsString()
void dominiqs::XMLConfig::setAsString (const std::string & cat, const std::string & entry, const std::string & value) private
Set the value of a parameter. Will create one if it does not exists yet
Parameters
Definition at line 90 of file xmlconfig.cpp.
References categories, and DOMINIQS_ASSERT.
Referenced by set().
Member Data Documentation
categories
XMLCategoryMap dominiqs::XMLConfig::categories private
Definition at line 72 of file xmlconfig.h.
Referenced by getAsString(), load(), save(), and setAsString().
The documentation for this class was generated from the following files:
FP2/utils/xmlconfig.h
FP2/utils/xmlconfig.cpp