BRKGA for MIP feasibility: dominiqs::UnitRandGen Class Reference
dominiqs::UnitRandGen Class Reference
#include <randgen.h>
Public Member Functions
UnitRandGen (uint64_t _seed=0)
void setSeed (uint64_t _seed)
double getFloat ()
void warmUp ()
Protected Attributes
boost::rand48 rnd
double span
Static Protected Attributes
static const int WARMUP_TRIES = 1000
Detailed Description
Basic Random numbers generator class Generates a floating number in the range [0,1) with uniform distribution
Definition at line 37 of file randgen.h.
Constructor & Destructor Documentation
UnitRandGen()
dominiqs::UnitRandGen::UnitRandGen (uint64_t _seed = 0) inline
default constructor
Parameters
_seed (uses generateSeed!)
Definition at line 44 of file randgen.h.
References rnd, and span.
Member Function Documentation
getFloat()
double dominiqs::UnitRandGen::getFloat () inline
Returns
a random floating point value in the specified range
Definition at line 54 of file randgen.h.
References rnd, and span.
Referenced by getRoundingThreshold(), dominiqs::STLRandGen::operator()(), dominiqs::FeasibilityPump::perturbe(), and dominiqs::FeasibilityPump::restart().
setSeed()
void dominiqs::UnitRandGen::setSeed (uint64_t _seed) inline
Seed the generator
Parameters
_seed if 0 use the current time, otherwise the supplied seed
Definition at line 52 of file randgen.h.
References dominiqs::generateSeed(), and rnd.
Referenced by dominiqs::FeasibilityPump::readConfig(), and SimpleRounding::readConfig().
warmUp()
void dominiqs::UnitRandGen::warmUp () inline
call the generator a few times to discard first values
Definition at line 56 of file randgen.h.
References rnd, and WARMUP_TRIES.
Referenced by dominiqs::FeasibilityPump::readConfig(), and SimpleRounding::readConfig().
Member Data Documentation
rnd
boost::rand48 dominiqs::UnitRandGen::rnd protected
Definition at line 58 of file randgen.h.
Referenced by getFloat(), dominiqs::RandGen::getFloat(), setSeed(), UnitRandGen(), and warmUp().
span
double dominiqs::UnitRandGen::span protected
Definition at line 59 of file randgen.h.
Referenced by getFloat(), dominiqs::RandGen::getFloat(), and UnitRandGen().
WARMUP_TRIES
const int dominiqs::UnitRandGen::WARMUP_TRIES = 1000 static protected
Definition at line 60 of file randgen.h.
Referenced by warmUp().
The documentation for this class was generated from the following file:
FP2/utils/randgen.h