BRKGA for MIP feasibility: dominiqs::Serializer Class Reference
dominiqs::Serializer Class Reference
#include <serialization.h>
Public Member Functions
template<class T >
void serialize (const T &value, std::ostream &out)
template<class T >
void serialize (const std::vector< T > &value, std::ostream &out)
template<class T >
void serialize (const T *value, size_t n, std::ostream &out)
Protected Attributes
std::string buffer
Detailed Description
Class used to serialize binary data to text files, using base64 encoding Specialize the serialize method to support custom types The class provides the buffer to write to (if needed) Beware. You need this only for binary serialization!
Definition at line 26 of file serialization.h.
Member Function Documentation
serialize() [1/3]
template<class T > void dominiqs::Serializer::serialize (const T & value, std::ostream & out) inline
Serialize a binary element
Template Parameters
T element type
Parameters
value element to serialize
out output stream
Definition at line 36 of file serialization.h.
References dominiqs::b64_encode(), and buffer.
Referenced by dominiqs::Logger::logBinaryItem().
serialize() [2/3]
template<class T > void dominiqs::Serializer::serialize (const std::vector< T > & value, std::ostream & out) inline
Serialize a std::vector of elements
Template Parameters
T vector value type
Parameters
value vector of elements to serialize
out output stream
Definition at line 48 of file serialization.h.
References dominiqs::b64_encode(), and buffer.
serialize() [3/3]
template<class T > void dominiqs::Serializer::serialize (const T * value, size_t n, std::ostream & out) inline
Serialize a C array of elements
Template Parameters
T element type
Parameters
value C array to serialize
n array size
out output stream
Definition at line 63 of file serialization.h.
References dominiqs::b64_encode(), and buffer.
Member Data Documentation
buffer
std::string dominiqs::Serializer::buffer protected
Definition at line 71 of file serialization.h.
Referenced by serialize().
The documentation for this class was generated from the following file:
FP2/utils/serialization.h