BRKGA for MIP feasibility: LexLessEqualProp Class Reference
LexLessEqualProp Class Reference
#include <lex_propagator.h>
Public Member Functions
LexLessEqualProp (ActiveDomain *d, const std::string &_name, const std::vector< int > &_x, const std::vector< int > &_y)
const char * getTypeName () const
void propagate ()
StatePtr getStateMgr ()
std::ostream & print (std::ostream &out) const
Public Member Functions inherited from Propagator
Propagator (Domain *d, PropagatorFactory *fact=0)
virtual ~Propagator ()
virtual void createAdvisors (std::list< AdvisorI * > &advisors)
void setName (const std::string &n)
const std::string & getName () const
int getID () const
void setID (int _id)
int getPriority () const
void setPriority (int p)
Domain * getDomain () const
void setPending ()
bool pending () const
PropagatorState getState () const
bool failed () const
Protected Member Functions
bool fixedEqual (int i) const
bool checkLex (int i) const
void updateState (int i)
void increaseAlpha ()
void decreaseBeta ()
Protected Member Functions inherited from Propagator
virtual void updateState ()
Protected Attributes
int alpha
int beta
int n
std::vector< int > x
std::vector< int > y
Protected Attributes inherited from Propagator
Domain * domain
PropagatorFactory * factory
int id
int priority
bool dirty
PropagatorState state
std::string name
Friends
class LexLessEqualPropAdvisor
class LexLessEqualPropState
Detailed Description
Propagator for x <=_lex y where x and y are vector of the same length n
Definition at line 19 of file lex_propagator.h.
Constructor & Destructor Documentation
LexLessEqualProp()
LexLessEqualProp::LexLessEqualProp (ActiveDomain * d, const std::string & _name, const std::vector< int > & _x, const std::vector< int > & _y)
Definition at line 84 of file lex_propagator.cpp.
References alpha, beta, checkLex(), CSTATE_ENTAILED, CSTATE_INFEAS, Propagator::domain, DOMINIQS_ASSERT, dominiqs::equal(), fixedEqual(), dominiqs::greaterThan(), LexLessEqualPropAdvisor, n, Propagator::name, Propagator::state, Domain::varLb(), Domain::varType(), Domain::varUb(), x, and y.
Member Function Documentation
checkLex()
bool LexLessEqualProp::checkLex (int i) const protected
Definition at line 210 of file lex_propagator.cpp.
References Propagator::domain, dominiqs::lessEqualThan(), dominiqs::lessThan(), n, Domain::varLb(), Domain::varUb(), x, and y.
Referenced by LexLessEqualProp(), and updateState().
decreaseBeta()
void LexLessEqualProp::decreaseBeta () protected
Definition at line 195 of file lex_propagator.cpp.
References alpha, beta, Propagator::domain, dominiqs::equal(), Domain::varLb(), Domain::varUb(), x, and y.
Referenced by updateState().
fixedEqual()
bool LexLessEqualProp::fixedEqual (int i) const protected
Definition at line 205 of file lex_propagator.cpp.
References Propagator::domain, Domain::isVarFixed(), Domain::varLb(), x, and y.
Referenced by increaseAlpha(), and LexLessEqualProp().
getStateMgr()
StatePtr LexLessEqualProp::getStateMgr () virtual
Reimplemented from Propagator.
Definition at line 200 of file lex_propagator.cpp.
References LexLessEqualPropState.
getTypeName()
const char* LexLessEqualProp::getTypeName () const inline
Definition at line 23 of file lex_propagator.h.
increaseAlpha()
void LexLessEqualProp::increaseAlpha () protected
Definition at line 189 of file lex_propagator.cpp.
References alpha, beta, fixedEqual(), and n.
Referenced by updateState().
print()
std::ostream & LexLessEqualProp::print (std::ostream & out) const virtual
Reimplemented from Propagator.
Definition at line 245 of file lex_propagator.cpp.
References alpha, beta, n, Propagator::name, PropagatorStateName, and Propagator::state.
propagate()
void LexLessEqualProp::propagate () virtual
Do a one-pass propagation of the constraint
Implements Propagator.
Definition at line 135 of file lex_propagator.cpp.
References alpha, beta, CSTATE_INFEAS, CSTATE_UNKNOWN, Propagator::dirty, Propagator::domain, Domain::fixBinDown(), Domain::fixBinUp(), dominiqs::greaterEqualThan(), dominiqs::greaterThan(), dominiqs::lessEqualThan(), dominiqs::lessThan(), Propagator::state, Domain::tightenLb(), Domain::tightenUb(), Domain::varLb(), Domain::varType(), Domain::varUb(), x, and y.
updateState()
void LexLessEqualProp::updateState (int i) protected
Definition at line 216 of file lex_propagator.cpp.
References alpha, beta, checkLex(), CSTATE_ENTAILED, CSTATE_INFEAS, decreaseBeta(), Propagator::domain, DOMINIQS_ASSERT, dominiqs::equal(), dominiqs::greaterThan(), increaseAlpha(), n, Propagator::state, Domain::varLb(), Domain::varUb(), x, and y.
Referenced by LexLessEqualPropAdvisor::fixedDown(), LexLessEqualPropAdvisor::fixedUp(), LexLessEqualPropAdvisor::tightenLb(), and LexLessEqualPropAdvisor::tightenUb().
Friends And Related Function Documentation
LexLessEqualPropAdvisor
friend class LexLessEqualPropAdvisor friend
Definition at line 29 of file lex_propagator.h.
Referenced by LexLessEqualProp().
LexLessEqualPropState
friend class LexLessEqualPropState friend
Definition at line 30 of file lex_propagator.h.
Referenced by getStateMgr().
Member Data Documentation
alpha
int LexLessEqualProp::alpha protected
Definition at line 31 of file lex_propagator.h.
Referenced by decreaseBeta(), increaseAlpha(), LexLessEqualProp(), print(), propagate(), and updateState().
beta
int LexLessEqualProp::beta protected
Definition at line 32 of file lex_propagator.h.
Referenced by decreaseBeta(), increaseAlpha(), LexLessEqualProp(), print(), propagate(), and updateState().
n
int LexLessEqualProp::n protected
Definition at line 33 of file lex_propagator.h.
Referenced by checkLex(), increaseAlpha(), LexLessEqualProp(), print(), and updateState().
x
std::vector<int> LexLessEqualProp::x protected
Definition at line 34 of file lex_propagator.h.
Referenced by checkLex(), decreaseBeta(), fixedEqual(), LexLessEqualProp(), propagate(), and updateState().
y
std::vector<int> LexLessEqualProp::y protected
Definition at line 35 of file lex_propagator.h.
Referenced by checkLex(), decreaseBeta(), fixedEqual(), LexLessEqualProp(), propagate(), and updateState().
The documentation for this class was generated from the following files:
FP2/propagator/lex_propagator.h
FP2/propagator/lex_propagator.cpp