BRKGA for MIP feasibility: dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP > Class Template Reference
dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP > Class Template Reference
#include <pq.h>
Public Types
typedef IndexByP::const_iterator const_iterator
Public Member Functions
const_iterator begin () const
const_iterator end () const
int size () const
void clear ()
void push (const T &t)
T pop ()
void erase (const ID &id)
Private Types
typedef boost::multi_index_container< T, boost::multi_index::indexed_by< boost::multi_index::hashed_unique< ExtractID >, boost::multi_index::ordered_non_unique< ExtractP, CompareP > > > Container
typedef Container::template nth_index< 0 >::type IndexByID
typedef Container::template nth_index< 1 >::type IndexByP
Private Attributes
Container c
Detailed Description
template<class T, class ID, class ExtractID, class P, class ExtractP, class CompareP>
class dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >
Template Class implementing an highly customizable priority queue. It stores objects of type T both by ID and by priority P.
Parameters
T data type stored in the container - usually a (smart) pointer to something
ID ID type
ExtractID functor type to extract id from objects (key extractor). Must define result_type (=ID)
P priority type
ExtractP functor type to extract priorities from objects (key extractor). Must define result_type (=P)
CompareP functor type to compare priorities
Definition at line 32 of file pq.h.
Member Typedef Documentation
const_iterator
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > typedef IndexByP::const_iterator dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::const_iterator
Definition at line 47 of file pq.h.
Container
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > typedef boost::multi_index_container< T, boost::multi_index::indexed_by< boost::multi_index::hashed_unique< ExtractID >, boost::multi_index::ordered_non_unique< ExtractP, CompareP > > > dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::Container private
Definition at line 41 of file pq.h.
IndexByID
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > typedef Container::template nth_index<0>::type dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::IndexByID private
Definition at line 42 of file pq.h.
IndexByP
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > typedef Container::template nth_index<1>::type dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::IndexByP private
Definition at line 43 of file pq.h.
Member Function Documentation
begin()
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > const_iterator dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::begin () const inline
Definition at line 48 of file pq.h.
References dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::begin(), and dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::c.
Referenced by dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::begin(), and dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::pop().
clear()
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > void dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::clear () inline
Definition at line 52 of file pq.h.
References dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::c.
end()
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > const_iterator dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::end () const inline
Definition at line 49 of file pq.h.
References dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::c, and dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::end().
Referenced by dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::end(), and dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::pop().
erase()
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > void dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::erase (const ID & id) inline
Definition at line 65 of file pq.h.
References dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::c.
Referenced by dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::pop().
pop()
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > T dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::pop () inline
Definition at line 56 of file pq.h.
References dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::begin(), dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::c, DOMINIQS_ASSERT, dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::end(), and dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::erase().
push()
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > void dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::push (const T & t) inline
Definition at line 54 of file pq.h.
References dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::c.
size()
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > int dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::size () const inline
Definition at line 51 of file pq.h.
References dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::c.
Member Data Documentation
c
template<class T , class ID , class ExtractID , class P , class ExtractP , class CompareP > Container dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::c private
Definition at line 44 of file pq.h.
Referenced by dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::begin(), dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::clear(), dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::end(), dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::erase(), dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::pop(), dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::push(), and dominiqs::PriorityQueue< T, ID, ExtractID, P, ExtractP, CompareP >::size().
The documentation for this class was generated from the following file:
FP2/utils/pq.h