BRKGA for MIP feasibility: ExecutionStopper Class Reference
ExecutionStopper Class Reference
ExecutionStopper class.
#include <execution_stopper.hpp>
Public Types
Enumerations
enum TimeType { TimeType::WALL, TimeType::CPU }
Defines with time use to stop.
Static Public Member Functions
Public interface
static void init (boost::timer::nanosecond_type max_time, TimeType type=TimeType::WALL)
static void timerStart ()
Start the timer.
static void timerStop ()
Stop the timer.
static void timerResume ()
Resume the timer.
static bool mustStop ()
Indicates if we must stop.
static boost::timer::cpu_times elapsed ()
Returns the elapsed time.
Static Protected Member Functions
Internals
static ExecutionStopper & instance ()
Get a reference for an instance.
Ctr-C handler
static void userSignalBreak (int signum)
Function used to emit the STOP signal.
Protected Attributes
Data members
boost::timer::nanosecond_type max_time
The maximum time.
TimeType time_type
The type of the time to be used to stop.
boost::timer::cpu_timer timer
The timer.
void(* previousHandler)(int)
Holds a pointer to the previous Ctrl-C handler.
bool initialized
Indicates if the initialization method was called.
bool stopsign
Indicates if a STOP signal was emitted.
Private Member Functions
Private methods to avoid creation and copy
ExecutionStopper ()
ExecutionStopper (const ExecutionStopper &)=delete
~ExecutionStopper ()
ExecutionStopper & operator= (const ExecutionStopper &)=delete
Detailed Description
ExecutionStopper class.
Author
Carlos Eduardo de Andrade ce.an.nosp@m.drad.nosp@m.e@gma.nosp@m.il.c.nosp@m.om
Date
2015
This class is a singleton used during the algorithm execution to stop by time or user interference. It holds a timer that be controlled from external calls. It also overwrite the Ctrl-C signal handling to allow a softer finish of the algorithm.
Definition at line 46 of file execution_stopper.hpp.
Member Enumeration Documentation
TimeType
enum ExecutionStopper::TimeType strong
Defines with time use to stop.
Enumerator
WALL
This is the regular wall clock time.
CPU
This is the CPU/user time.
Definition at line 51 of file execution_stopper.hpp.
Constructor & Destructor Documentation
ExecutionStopper() [1/2]
ExecutionStopper::ExecutionStopper () private
Definition at line 39 of file execution_stopper.cpp.
ExecutionStopper() [2/2]
ExecutionStopper::ExecutionStopper (const ExecutionStopper &) private delete
~ExecutionStopper()
ExecutionStopper::~ExecutionStopper () private
Definition at line 48 of file execution_stopper.cpp.
Member Function Documentation
elapsed()
boost::timer::cpu_times ExecutionStopper::elapsed () static
Returns the elapsed time.
Definition at line 71 of file execution_stopper.cpp.
References instance(), and timer.
init()
void ExecutionStopper::init (boost::timer::nanosecond_type max_time, TimeType type = TimeType::WALL) static
Initialize the singleton. Must be call before any other method.
Parameters
max_time the maximum time in seconds.
type of the time to be considered.
Definition at line 77 of file execution_stopper.cpp.
References instance(), and userSignalBreak().
Referenced by main().
instance()
ExecutionStopper & ExecutionStopper::instance () static protected
Get a reference for an instance.
Definition at line 52 of file execution_stopper.cpp.
Referenced by elapsed(), init(), mustStop(), timerResume(), timerStart(), timerStop(), and userSignalBreak().
mustStop()
bool ExecutionStopper::mustStop () static
Indicates if we must stop.
Definition at line 87 of file execution_stopper.cpp.
References instance(), and WALL.
Referenced by ILOINCUMBENTCALLBACK0(), ILOMIPINFOCALLBACK0(), main(), FeasibilityPump_Decoder::objectiveFeasibilityPump(), and FeasibilityPump_Decoder::performMIPLocalSearch().
operator=()
ExecutionStopper& ExecutionStopper::operator= (const ExecutionStopper &) private delete
timerResume()
void ExecutionStopper::timerResume () static
Resume the timer.
Definition at line 67 of file execution_stopper.cpp.
References instance(), and timer.
Referenced by main().
timerStart()
void ExecutionStopper::timerStart () static
Start the timer.
Definition at line 59 of file execution_stopper.cpp.
References instance(), and timer.
Referenced by main().
timerStop()
void ExecutionStopper::timerStop () static
Stop the timer.
Definition at line 63 of file execution_stopper.cpp.
References instance(), and timer.
Referenced by main().
userSignalBreak()
void ExecutionStopper::userSignalBreak (int signum) static protected
Function used to emit the STOP signal.
Definition at line 96 of file execution_stopper.cpp.
References instance(), previousHandler, and stopsign.
Referenced by init().
Member Data Documentation
initialized
bool ExecutionStopper::initialized protected
Indicates if the initialization method was called.
Definition at line 120 of file execution_stopper.hpp.
max_time
boost::timer::nanosecond_type ExecutionStopper::max_time protected
The maximum time.
Definition at line 108 of file execution_stopper.hpp.
previousHandler
void(* ExecutionStopper::previousHandler) (int) protected
Holds a pointer to the previous Ctrl-C handler.
Definition at line 117 of file execution_stopper.hpp.
Referenced by userSignalBreak().
stopsign
bool ExecutionStopper::stopsign protected
Indicates if a STOP signal was emitted.
Definition at line 123 of file execution_stopper.hpp.
Referenced by userSignalBreak().
time_type
TimeType ExecutionStopper::time_type protected
The type of the time to be used to stop.
Definition at line 111 of file execution_stopper.hpp.
timer
boost::timer::cpu_timer ExecutionStopper::timer protected
The timer.
Definition at line 114 of file execution_stopper.hpp.
Referenced by elapsed(), timerResume(), timerStart(), and timerStop().
The documentation for this class was generated from the following files:
include/execution_stopper.hpp
utils/execution_stopper.cpp