BRKGA for MIP feasibility: dominiqs::ProbInfo Class Reference
dominiqs::ProbInfo Class Reference
#include <cpxutils.h>
Public Member Functions
ProbInfo ()
void clear ()
void read (CEnv env, CProb lp)
Prob write (CEnv env)
VarPtr getVarByName (const std::string &name) const
ConstraintPtr getConstraintByName (const std::string &name) const
void push (VarPtr v)
void push (ConstraintPtr c)
Public Attributes
Data
unsigned int numVars
unsigned int numBinVars
unsigned int numIntVars
unsigned int numContVars
unsigned int numConstrs
unsigned int numNz
std::vector< ConstraintPtr > constraints
std::vector< VarPtr > vars
int obj_sense
Detailed Description
ProbInfo class This class provides efficient access to all the problem data in both row and column major
Definition at line 179 of file cpxutils.h.
Constructor & Destructor Documentation
ProbInfo()
dominiqs::ProbInfo::ProbInfo ()
Definition at line 327 of file cpxutils.cpp.
Member Function Documentation
clear()
void dominiqs::ProbInfo::clear ()
Definition at line 365 of file cpxutils.cpp.
getConstraintByName()
ConstraintPtr dominiqs::ProbInfo::getConstraintByName (const std::string & name) const
Definition at line 341 of file cpxutils.cpp.
getVarByName()
VarPtr dominiqs::ProbInfo::getVarByName (const std::string & name) const
Definition at line 332 of file cpxutils.cpp.
push() [1/2]
void dominiqs::ProbInfo::push (VarPtr v)
Definition at line 350 of file cpxutils.cpp.
push() [2/2]
void dominiqs::ProbInfo::push (ConstraintPtr c)
Definition at line 359 of file cpxutils.cpp.
read()
void dominiqs::ProbInfo::read (CEnv env, CProb lp)
Definition at line 378 of file cpxutils.cpp.
References CHECKED_CPX_CALL, DOMINIQS_ASSERT, dominiqs::getConstrNames(), dominiqs::getVar(), and dominiqs::getVarNames().
write()
Prob dominiqs::ProbInfo::write (CEnv env)
Definition at line 435 of file cpxutils.cpp.
References dominiqs::addCut(), dominiqs::addEmptyVar(), and DECL_PROB.
Member Data Documentation
constraints
std::vector<ConstraintPtr> dominiqs::ProbInfo::constraints
Definition at line 194 of file cpxutils.h.
numBinVars
unsigned int dominiqs::ProbInfo::numBinVars
Definition at line 188 of file cpxutils.h.
numConstrs
unsigned int dominiqs::ProbInfo::numConstrs
Definition at line 191 of file cpxutils.h.
numContVars
unsigned int dominiqs::ProbInfo::numContVars
Definition at line 190 of file cpxutils.h.
numIntVars
unsigned int dominiqs::ProbInfo::numIntVars
Definition at line 189 of file cpxutils.h.
numNz
unsigned int dominiqs::ProbInfo::numNz
Definition at line 192 of file cpxutils.h.
numVars
unsigned int dominiqs::ProbInfo::numVars
Definition at line 187 of file cpxutils.h.
obj_sense
int dominiqs::ProbInfo::obj_sense
Definition at line 196 of file cpxutils.h.
vars
std::vector<VarPtr> dominiqs::ProbInfo::vars
Definition at line 195 of file cpxutils.h.
The documentation for this class was generated from the following files:
FP2/cpxutils/cpxutils.h
FP2/cpxutils/cpxutils.cpp