BRKGA for MIP feasibility: dominiqs::XmlNode Class Reference
dominiqs::XmlNode Class Reference
#include <myxml.h>
Public Member Functions
XmlNode (xmlNodePtr n=0)
bool isNull () const
std::string name () const
std::string attr (const std::string &name) const
std::string data () const
XmlNode parent () const
XmlNode firstChild () const
XmlNode next () const
XmlNode prev () const
XmlNode next (int skip) const
XmlNode prev (int skip) const
XmlNode operator[] (const std::string &name) const
XmlNode operator[] (int idx) const
void set (const std::string &content, bool checkSpecialChars=false)
void unlink ()
XmlNode addChild (const std::string &name, const AttributeMap &attrs=AttributeMap())
XmlNode addChild (const std::string &name, const std::string &content, const AttributeMap &attrs=AttributeMap())
Protected Attributes
xmlNodePtr node
Detailed Description
C++ Wrapper aroung libxml xmlNodePtr Can be used as iterator and navigate through the DOM tree
Definition at line 30 of file myxml.h.
Constructor & Destructor Documentation
XmlNode()
dominiqs::XmlNode::XmlNode (xmlNodePtr n = 0) inline
Definition at line 33 of file myxml.h.
Referenced by addChild(), firstChild(), next(), operator[](), parent(), and prev().
Member Function Documentation
addChild() [1/2]
XmlNode dominiqs::XmlNode::addChild (const std::string & name, const AttributeMap & attrs = AttributeMap())
Definition at line 119 of file myxml.cpp.
References name(), node, and XmlNode().
Referenced by dominiqs::XMLConfig::save().
addChild() [2/2]
XmlNode dominiqs::XmlNode::addChild (const std::string & name, const std::string & content, const AttributeMap & attrs = AttributeMap())
Definition at line 132 of file myxml.cpp.
References name(), node, and XmlNode().
attr()
std::string dominiqs::XmlNode::attr (const std::string & name) const
Definition at line 26 of file myxml.cpp.
References data(), name(), and node.
data()
std::string dominiqs::XmlNode::data () const
Definition at line 33 of file myxml.cpp.
References node.
Referenced by attr(), dominiqs::getBase64Content(), dominiqs::getTextContent(), dominiqs::XMLConfig::load(), and set().
firstChild()
XmlNode dominiqs::XmlNode::firstChild () const
Definition at line 45 of file myxml.cpp.
References node, and XmlNode().
Referenced by dominiqs::XMLConfig::load(), and operator[]().
isNull()
bool dominiqs::XmlNode::isNull () const inline
Definition at line 34 of file myxml.h.
References node.
Referenced by dominiqs::getBase64Content(), dominiqs::getTextContent(), dominiqs::XMLConfig::load(), and operator[]().
name()
std::string dominiqs::XmlNode::name () const
Definition at line 20 of file myxml.cpp.
References node.
Referenced by addChild(), attr(), dominiqs::XMLConfig::load(), operator[](), and dominiqs::XMLConfig::save().
next() [1/2]
XmlNode dominiqs::XmlNode::next () const
Definition at line 53 of file myxml.cpp.
References node, and XmlNode().
Referenced by dominiqs::XMLConfig::load(), and operator[]().
next() [2/2]
XmlNode dominiqs::XmlNode::next (int skip) const
Definition at line 69 of file myxml.cpp.
References DOMINIQS_ASSERT, node, and XmlNode().
operator[]() [1/2]
XmlNode dominiqs::XmlNode::operator[] (const std::string & name) const
Definition at line 89 of file myxml.cpp.
References firstChild(), isNull(), name(), next(), and XmlNode().
operator[]() [2/2]
XmlNode dominiqs::XmlNode::operator[] (int idx) const
Definition at line 100 of file myxml.cpp.
References firstChild(), and next().
parent()
XmlNode dominiqs::XmlNode::parent () const
Definition at line 40 of file myxml.cpp.
References node, and XmlNode().
prev() [1/2]
XmlNode dominiqs::XmlNode::prev () const
Definition at line 61 of file myxml.cpp.
References node, and XmlNode().
prev() [2/2]
XmlNode dominiqs::XmlNode::prev (int skip) const
Definition at line 79 of file myxml.cpp.
References DOMINIQS_ASSERT, node, and XmlNode().
set()
void dominiqs::XmlNode::set (const std::string & content, bool checkSpecialChars = false)
Definition at line 107 of file myxml.cpp.
References data(), and node.
unlink()
void dominiqs::XmlNode::unlink ()
Definition at line 145 of file myxml.cpp.
References node.
Member Data Documentation
node
xmlNodePtr dominiqs::XmlNode::node protected
Definition at line 54 of file myxml.h.
Referenced by addChild(), attr(), data(), firstChild(), isNull(), name(), next(), parent(), prev(), set(), and unlink().
The documentation for this class was generated from the following files:
FP2/utils/myxml.h
FP2/utils/myxml.cpp