BRKGA for MIP feasibility: Domain Class Reference
Domain Class Reference
#include <domain.h>
Public Member Functions
~Domain ()
virtual void pushVar (const std::string &name, char t, double l, double u)
virtual void clear ()
StatePtr getStateMgr ()
unsigned int size () const
std::string varName (int j) const
double varLb (int j) const
double varUb (int j) const
bool isVarFixed (int j) const
char varType (int j) const
void fixBinUp (int j)
void fixBinDown (int j)
void tightenLb (int j, double newValue)
void tightenUb (int j, double newValue)
Public Attributes
boost::function< void(int)> emitFixedBinUp
boost::function< void(int)> emitFixedBinDown
boost::function< void(int, double, double)> emitTightenedLb
boost::function< void(int, double, double)> emitTightenedUb
Protected Attributes
std::vector< std::string > names
dominiqs::numarray< double > lb
dominiqs::numarray< double > ub
dominiqs::numarray< bool > fixed
dominiqs::numarray< char > type
Friends
class DomainState
Detailed Description
Stores the domains of a set of variables and their info
Definition at line 32 of file domain.h.
Constructor & Destructor Documentation
~Domain()
Domain::~Domain () inline
Definition at line 35 of file domain.h.
References clear().
Member Function Documentation
clear()
void Domain::clear () virtual
Definition at line 27 of file domain.cpp.
Referenced by Ranker::init(), and ~Domain().
fixBinDown()
void Domain::fixBinDown (int j) inline
Definition at line 64 of file domain.h.
References DOMINIQS_ASSERT, emitFixedBinDown, dominiqs::equal(), fixed, lb, type, and ub.
Referenced by LexLessEqualProp::propagate(), ImpliesProp::propagate(), LinearProp::propagate(), EquivProp::propagate(), CardinalityProp::propagate(), and KnapsackProp::propagate().
fixBinUp()
void Domain::fixBinUp (int j) inline
Definition at line 56 of file domain.h.
References DOMINIQS_ASSERT, emitFixedBinUp, dominiqs::equal(), fixed, lb, type, and ub.
Referenced by LexLessEqualProp::propagate(), ImpliesProp::propagate(), LinearProp::propagate(), EquivProp::propagate(), CardinalityProp::propagate(), and KnapsackProp::propagate().
getStateMgr()
StatePtr Domain::getStateMgr ()
Definition at line 22 of file domain.cpp.
isVarFixed()
bool Domain::isVarFixed (int j) const inline
Definition at line 51 of file domain.h.
References fixed.
Referenced by PropagatorRounding::apply(), LexLessEqualProp::fixedEqual(), ImpliesProp::ImpliesProp(), PropagatorRounding::init(), LinearProp::propagate(), EquivProp::propagate(), CardinalityProp::propagate(), KnapsackProp::propagate(), and EquivProp::updateState().
pushVar()
void Domain::pushVar (const std::string & name, char t, double l, double u) virtual
Add a variable to the domain
Parameters
name variable name
t variable type
l variable lower bound
u variable upper bound
Definition at line 13 of file domain.cpp.
References dominiqs::equal().
Referenced by PropagatorRounding::init().
size()
unsigned int Domain::size () const inline
Definition at line 47 of file domain.h.
References names.
tightenLb()
void Domain::tightenLb (int j, double newValue) inline
Definition at line 72 of file domain.h.
References DOMINIQS_ASSERT, emitTightenedLb, fixed, dominiqs::greaterThan(), dominiqs::isNull(), lb, min, type, and ub.
Referenced by LexLessEqualProp::propagate(), VarLowerBoundProp::propagate(), LinearProp::propagate(), and KnapsackProp::propagate().
tightenUb()
void Domain::tightenUb (int j, double newValue) inline
Definition at line 84 of file domain.h.
References DOMINIQS_ASSERT, emitTightenedUb, fixed, dominiqs::isNull(), lb, dominiqs::lessThan(), max, type, and ub.
Referenced by LexLessEqualProp::propagate(), LinearProp::propagate(), VarUpperBoundProp::propagate(), and KnapsackProp::propagate().
varLb()
double Domain::varLb (int j) const inline
Definition at line 49 of file domain.h.
References lb.
Referenced by KnapsackFactory::analyze(), PropagatorRounding::apply(), CardinalityProp::CardinalityProp(), LexLessEqualProp::checkLex(), LexLessEqualProp::decreaseBeta(), LexLessEqualProp::fixedEqual(), ImpliesProp::ImpliesProp(), KnapsackProp::KnapsackProp(), LexLessEqualProp::LexLessEqualProp(), LinearProp::LinearProp(), LexLessEqualProp::propagate(), VarLowerBoundProp::propagate(), LinearProp::propagate(), EquivProp::propagate(), VarUpperBoundProp::propagate(), KnapsackProp::propagate(), VarLowerBoundPropAdvisor::tightenLb(), VarUpperBoundPropAdvisor::tightenLb(), LexLessEqualProp::updateState(), EquivProp::updateState(), and VarLowerBoundProp::VarLowerBoundProp().
varName()
std::string Domain::varName (int j) const inline
Definition at line 48 of file domain.h.
References names.
Referenced by ImpliesProp::print(), VarLowerBoundProp::print(), EquivProp::print(), and VarUpperBoundProp::print().
varType()
char Domain::varType (int j) const inline
Definition at line 52 of file domain.h.
References type.
Referenced by LogicFactory::analyze(), VarBoundFactory::analyze(), CardinalityFactory::analyze(), PropagatorRounding::apply(), PropagatorRounding::init(), KnapsackProp::KnapsackProp(), LexLessEqualProp::LexLessEqualProp(), LinearProp::LinearProp(), LexLessEqualProp::propagate(), VarLowerBoundProp::propagate(), LinearProp::propagate(), VarUpperBoundProp::propagate(), and KnapsackProp::propagate().
varUb()
double Domain::varUb (int j) const inline
Definition at line 50 of file domain.h.
References ub.
Referenced by KnapsackFactory::analyze(), PropagatorRounding::apply(), CardinalityProp::CardinalityProp(), LexLessEqualProp::checkLex(), LexLessEqualProp::decreaseBeta(), KnapsackProp::KnapsackProp(), LexLessEqualProp::LexLessEqualProp(), LinearProp::LinearProp(), LexLessEqualProp::propagate(), LinearProp::propagate(), VarUpperBoundProp::propagate(), KnapsackProp::propagate(), VarLowerBoundPropAdvisor::tightenUb(), VarUpperBoundPropAdvisor::tightenUb(), LexLessEqualProp::updateState(), and VarUpperBoundProp::VarUpperBoundProp().
Friends And Related Function Documentation
DomainState
friend class DomainState friend
Definition at line 106 of file domain.h.
Member Data Documentation
emitFixedBinDown
boost::function<void (int)> Domain::emitFixedBinDown
Definition at line 100 of file domain.h.
Referenced by fixBinDown().
emitFixedBinUp
boost::function<void (int)> Domain::emitFixedBinUp
Definition at line 99 of file domain.h.
Referenced by fixBinUp(), and PropagationEngine::setDomain().
emitTightenedLb
boost::function<void (int, double, double)> Domain::emitTightenedLb
Definition at line 101 of file domain.h.
Referenced by tightenLb().
emitTightenedUb
boost::function<void (int, double, double)> Domain::emitTightenedUb
Definition at line 102 of file domain.h.
Referenced by tightenUb().
fixed
dominiqs::numarray<bool> Domain::fixed protected
Definition at line 110 of file domain.h.
Referenced by fixBinDown(), fixBinUp(), isVarFixed(), tightenLb(), and tightenUb().
lb
dominiqs::numarray<double> Domain::lb protected
Definition at line 108 of file domain.h.
Referenced by fixBinDown(), fixBinUp(), tightenLb(), tightenUb(), and varLb().
names
std::vector<std::string> Domain::names protected
Definition at line 107 of file domain.h.
Referenced by size(), and varName().
type
dominiqs::numarray<char> Domain::type protected
Definition at line 111 of file domain.h.
Referenced by fixBinDown(), fixBinUp(), tightenLb(), tightenUb(), and varType().
ub
dominiqs::numarray<double> Domain::ub protected
Definition at line 109 of file domain.h.
Referenced by fixBinDown(), fixBinUp(), tightenLb(), tightenUb(), and varUb().
The documentation for this class was generated from the following files:
FP2/propagator/domain.h
FP2/propagator/domain.cpp