BRKGA for MIP feasibility: dominiqs::IniParserContext Class Reference
dominiqs::IniParserContext Class Reference
Public Member Functions
IniParserContext (IniFile *_data)
void addCategory (iterator_t first, iterator_t last) const
void addEntry (iterator_t first, iterator_t last) const
void addValue (iterator_t first, iterator_t last) const
Protected Attributes
IniFile * data
std::string currentCat
std::string currentEntry
Detailed Description
Definition at line 31 of file ini_spirit.cpp.
Constructor & Destructor Documentation
IniParserContext()
dominiqs::IniParserContext::IniParserContext (IniFile * _data)
Definition at line 44 of file ini_spirit.cpp.
Member Function Documentation
addCategory()
void dominiqs::IniParserContext::addCategory (iterator_t first, iterator_t last) const
Definition at line 46 of file ini_spirit.cpp.
References dominiqs::IniFile::addCategory(), currentCat, and data.
Referenced by dominiqs::IniFile::load().
addEntry()
void dominiqs::IniParserContext::addEntry (iterator_t first, iterator_t last) const
Definition at line 53 of file ini_spirit.cpp.
References dominiqs::IniFile::addCategory(), currentCat, currentEntry, data, and dominiqs::IniFile::getCategory().
Referenced by dominiqs::IniFile::load().
addValue()
void dominiqs::IniParserContext::addValue (iterator_t first, iterator_t last) const
Definition at line 64 of file ini_spirit.cpp.
References currentCat, currentEntry, data, and dominiqs::IniFile::set().
Referenced by dominiqs::IniFile::load().
Member Data Documentation
currentCat
std::string dominiqs::IniParserContext::currentCat mutable protected
Definition at line 40 of file ini_spirit.cpp.
Referenced by addCategory(), addEntry(), and addValue().
currentEntry
std::string dominiqs::IniParserContext::currentEntry mutable protected
Definition at line 41 of file ini_spirit.cpp.
Referenced by addEntry(), and addValue().
data
IniFile* dominiqs::IniParserContext::data protected
Definition at line 39 of file ini_spirit.cpp.
Referenced by addCategory(), addEntry(), and addValue().
The documentation for this class was generated from the following file:
FP2/utils/ini_spirit.cpp