BRKGA for MIP feasibility: FractionalityRanker Class Reference
FractionalityRanker Class Reference
Rank variables in order of increasing fractionality always preferring binary variables to general integer ones.
#include <ranking.h>
Public Member Functions
void readConfig ()
void ignoreGeneralIntegers (bool flag)
void setCurrentState (const std::vector< double > &x)
int next ()
Public Member Functions inherited from Ranker
Ranker ()
virtual ~Ranker ()
virtual void init (Domain *d, bool ignoreGeneralInt=true)
Protected Types
typedef std::pair< double, int > Score
Protected Attributes
bool reverse
double rankNoise
int noiseAfter
dominiqs::STLRandGen rnd
std::vector< Score > scores
std::vector< int > perm
unsigned int nextItr
Protected Attributes inherited from Ranker
Domain * domain
std::vector< int > binaries
std::vector< int > gintegers
std::vector< int > integers
int nCalled
Detailed Description
Rank variables in order of increasing fractionality always preferring binary variables to general integer ones.
Definition at line 69 of file ranking.h.
Member Typedef Documentation
Score
typedef std::pair<double, int> FractionalityRanker::Score protected
Definition at line 83 of file ranking.h.
Member Function Documentation
ignoreGeneralIntegers()
void FractionalityRanker::ignoreGeneralIntegers (bool flag) virtual
Reimplemented from Ranker.
Definition at line 97 of file ranking.cpp.
References Ranker::ignoreGeneralIntegers().
next()
int FractionalityRanker::next () virtual
Implements Ranker.
Definition at line 134 of file ranking.cpp.
readConfig()
void FractionalityRanker::readConfig () virtual
Reimplemented from Ranker.
Definition at line 82 of file ranking.cpp.
References FRAC_RANKER_NOISE_AFTER_DEF, FRAC_RANKER_RANK_NOISE_DEF, FRAC_RANKER_REVERSE_DEF, dominiqs::gConfig(), dominiqs::XMLConfig::get(), LOG_CONFIG, LOG_END_SECTION, LOG_START_SECTION, and READ_FROM_CONFIG.
setCurrentState()
void FractionalityRanker::setCurrentState (const std::vector< double > & x) virtual
Implements Ranker.
Definition at line 105 of file ranking.cpp.
References dominiqs::integralityViolation(), dominiqs::isNotNull(), and dominiqs::permShellSort().
Member Data Documentation
nextItr
unsigned int FractionalityRanker::nextItr protected
Definition at line 86 of file ranking.h.
noiseAfter
int FractionalityRanker::noiseAfter protected
Definition at line 80 of file ranking.h.
perm
std::vector<int> FractionalityRanker::perm protected
Definition at line 85 of file ranking.h.
rankNoise
double FractionalityRanker::rankNoise protected
Definition at line 79 of file ranking.h.
reverse
bool FractionalityRanker::reverse protected
Definition at line 78 of file ranking.h.
rnd
dominiqs::STLRandGen FractionalityRanker::rnd protected
Definition at line 81 of file ranking.h.
scores
std::vector<Score> FractionalityRanker::scores protected
Definition at line 84 of file ranking.h.
The documentation for this class was generated from the following files:
FP2/feaspump/ranking.h
FP2/feaspump/ranking.cpp