BRKGA for MIP feasibility: dominiqs::GlobalAutoSection Class Reference
dominiqs::GlobalAutoSection Class Reference
#include <logger.h>
Public Member Functions
GlobalAutoSection (const std::string &name)
template<class T >
GlobalAutoSection (const std::string &name, const std::string &attrName, const T &attrValue)
~GlobalAutoSection ()
void close ()
Private Attributes
bool pending
Detailed Description
Automatic Section Closer (RAII principle) for the global stopewatch
Definition at line 147 of file logger.h.
Constructor & Destructor Documentation
GlobalAutoSection() [1/2]
dominiqs::GlobalAutoSection::GlobalAutoSection (const std::string & name) inline
Definition at line 150 of file logger.h.
References dominiqs::gLog(), and dominiqs::Logger::startSection().
GlobalAutoSection() [2/2]
template<class T > dominiqs::GlobalAutoSection::GlobalAutoSection (const std::string & name, const std::string & attrName, const T & attrValue) inline
Definition at line 156 of file logger.h.
References dominiqs::gLog(), and dominiqs::Logger::startSection().
~GlobalAutoSection()
dominiqs::GlobalAutoSection::~GlobalAutoSection ()
Definition at line 108 of file logger.cpp.
References close().
Member Function Documentation
close()
void dominiqs::GlobalAutoSection::close () inline
Definition at line 162 of file logger.h.
References dominiqs::Logger::endSection(), dominiqs::gLog(), and pending.
Referenced by dominiqs::infoCB(), and ~GlobalAutoSection().
Member Data Documentation
pending
bool dominiqs::GlobalAutoSection::pending private
Definition at line 171 of file logger.h.
Referenced by close().
The documentation for this class was generated from the following files:
FP2/utils/logger.h
FP2/utils/logger.cpp