BRKGA for MIP feasibility: SimpleRounding Class Reference
SimpleRounding Class Reference
#include <transformers.h>
Public Member Functions
SimpleRounding ()
void readConfig ()
void init (const dominiqs::Model &model, bool ignoreGeneralInt=true)
void ignoreGeneralIntegers (bool flag)
void apply (const std::vector< double > &in, std::vector< double > &out)
Public Member Functions inherited from dominiqs::SolutionTransformer
virtual ~SolutionTransformer ()
virtual void newIncumbent (const std::vector< double > &x, double objval)
virtual void clear ()
Public Attributes
std::vector< int > binaries
std::vector< int > gintegers
std::vector< int > integers
dominiqs::UnitRandGen roundGen
bool randomizedRounding
bool logDetails
Detailed Description
Standard frac -> int transformer: performs a simple rounding rounding
Definition at line 41 of file transformers.h.
Constructor & Destructor Documentation
SimpleRounding()
SimpleRounding::SimpleRounding ()
Definition at line 44 of file transformers.cpp.
Member Function Documentation
apply()
void SimpleRounding::apply (const std::vector< double > & in, std::vector< double > & out) virtual
Trasform the vector given as input
Parameters
in and store the result in
out
Implements dominiqs::SolutionTransformer.
Reimplemented in PropagatorRounding.
Definition at line 92 of file transformers.cpp.
References doRound(), getRoundingThreshold(), dominiqs::gLog(), dominiqs::greaterThan(), integers, dominiqs::lessThan(), logDetails, dominiqs::Logger::logItem(), MYLOG, randomizedRounding, and roundGen.
ignoreGeneralIntegers()
void SimpleRounding::ignoreGeneralIntegers (bool flag) virtual
Reimplemented from dominiqs::SolutionTransformer.
Reimplemented in PropagatorRounding.
Definition at line 79 of file transformers.cpp.
References binaries, DOMINIQS_ASSERT, gintegers, and integers.
Referenced by PropagatorRounding::ignoreGeneralIntegers(), and init().
init()
void SimpleRounding::init (const dominiqs::Model & model, bool ignoreGeneralInt = true) virtual
Read needed information (if any) about the problem (
Parameters
pinfo)
Reimplemented from dominiqs::SolutionTransformer.
Reimplemented in PropagatorRounding.
Definition at line 62 of file transformers.cpp.
References binaries, dominiqs::different(), gintegers, ignoreGeneralIntegers(), integers, dominiqs::Model::numVars, dominiqs::Model::xLb, dominiqs::Model::xType, and dominiqs::Model::xUb.
Referenced by PropagatorRounding::init().
readConfig()
void SimpleRounding::readConfig () virtual
Reimplemented from dominiqs::SolutionTransformer.
Reimplemented in PropagatorRounding.
Definition at line 48 of file transformers.cpp.
References DEF_LOG_DETAILS, DEF_SEED, dominiqs::gConfig(), dominiqs::XMLConfig::get(), LOG_CONFIG, LOG_END_SECTION, LOG_START_SECTION, logDetails, randomizedRounding, READ_FROM_CONFIG, roundGen, dominiqs::UnitRandGen::setSeed(), and dominiqs::UnitRandGen::warmUp().
Referenced by PropagatorRounding::readConfig().
Member Data Documentation
binaries
std::vector<int> SimpleRounding::binaries
Definition at line 51 of file transformers.h.
Referenced by ignoreGeneralIntegers(), and init().
gintegers
std::vector<int> SimpleRounding::gintegers
Definition at line 52 of file transformers.h.
Referenced by ignoreGeneralIntegers(), and init().
integers
std::vector<int> SimpleRounding::integers
Definition at line 53 of file transformers.h.
Referenced by apply(), ignoreGeneralIntegers(), and init().
logDetails
bool SimpleRounding::logDetails
Definition at line 56 of file transformers.h.
Referenced by apply(), and readConfig().
randomizedRounding
bool SimpleRounding::randomizedRounding
Definition at line 55 of file transformers.h.
Referenced by apply(), PropagatorRounding::apply(), and readConfig().
roundGen
dominiqs::UnitRandGen SimpleRounding::roundGen
Definition at line 54 of file transformers.h.
Referenced by apply(), PropagatorRounding::apply(), and readConfig().
The documentation for this class was generated from the following files:
FP2/feaspump/transformers.h
FP2/feaspump/transformers.cpp