BRKGA for MIP feasibility: RandomRanker Class Reference
RandomRanker Class Reference
Rank variables randomly.
#include <ranking.h>
Public Member Functions
void readConfig ()
void ignoreGeneralIntegers (bool flag)
void setCurrentState (const std::vector< double > &x)
int next ()
Public Member Functions inherited from Ranker
Ranker ()
virtual ~Ranker ()
virtual void init (Domain *d, bool ignoreGeneralInt=true)
Protected Attributes
dominiqs::STLRandGen rnd
std::vector< int > perm
unsigned int nextItr
Protected Attributes inherited from Ranker
Domain * domain
std::vector< int > binaries
std::vector< int > gintegers
std::vector< int > integers
int nCalled
Detailed Description
Rank variables randomly.
Definition at line 93 of file ranking.h.
Member Function Documentation
ignoreGeneralIntegers()
void RandomRanker::ignoreGeneralIntegers (bool flag) virtual
Reimplemented from Ranker.
Definition at line 150 of file ranking.cpp.
References Ranker::ignoreGeneralIntegers().
next()
int RandomRanker::next () virtual
Implements Ranker.
Definition at line 165 of file ranking.cpp.
readConfig()
void RandomRanker::readConfig () virtual
Reimplemented from Ranker.
Definition at line 143 of file ranking.cpp.
References dominiqs::gConfig(), and dominiqs::XMLConfig::get().
setCurrentState()
void RandomRanker::setCurrentState (const std::vector< double > & x) virtual
Implements Ranker.
Definition at line 157 of file ranking.cpp.
References dominiqs::iota().
Member Data Documentation
nextItr
unsigned int RandomRanker::nextItr protected
Definition at line 104 of file ranking.h.
perm
std::vector<int> RandomRanker::perm protected
Definition at line 103 of file ranking.h.
rnd
dominiqs::STLRandGen RandomRanker::rnd protected
Definition at line 102 of file ranking.h.
The documentation for this class was generated from the following files:
FP2/feaspump/ranking.h
FP2/feaspump/ranking.cpp