BRKGA for MIP feasibility: EquivAdvisor Class Reference
EquivAdvisor Class Reference
Public Member Functions
EquivAdvisor (EquivProp *p, int j)
void fixedUp ()
void fixedDown ()
std::ostream & print (std::ostream &out) const
Public Member Functions inherited from AdvisorI
AdvisorI (Propagator *p, int j)
virtual ~AdvisorI ()
Propagator * getPropagator () const
int getVar () const
virtual void tightenLb (double delta, bool decreaseInfCnt, bool propagate)
virtual void tightenUb (double delta, bool decreaseInfCnt, bool propagate)
Additional Inherited Members
Protected Member Functions inherited from AdvisorI
template<class T >
T * getMyProp ()
Protected Attributes inherited from AdvisorI
Propagator * prop
int var
Detailed Description
Definition at line 170 of file logic_propagator.cpp.
Constructor & Destructor Documentation
EquivAdvisor()
EquivAdvisor::EquivAdvisor (EquivProp * p, int j) inline
Definition at line 173 of file logic_propagator.cpp.
Member Function Documentation
fixedDown()
void EquivAdvisor::fixedDown () inline virtual
Reimplemented from AdvisorI.
Definition at line 182 of file logic_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::getState(), AdvisorI::prop, Propagator::state, and EquivProp::updateState().
fixedUp()
void EquivAdvisor::fixedUp () inline virtual
events for binary variables
Reimplemented from AdvisorI.
Definition at line 175 of file logic_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::getState(), AdvisorI::prop, Propagator::state, and EquivProp::updateState().
print()
std::ostream& EquivAdvisor::print (std::ostream & out) const inline virtual
Reimplemented from AdvisorI.
Definition at line 190 of file logic_propagator.cpp.
References Propagator::getName(), and AdvisorI::prop.
The documentation for this class was generated from the following file:
FP2/propagator/logic_propagator.cpp