BRKGA for MIP feasibility: EquivProp Class Reference
EquivProp Class Reference
#include <logic_propagator.h>
Public Member Functions
EquivProp (Domain *d, PropagatorFactory *fact, const std::string &_name, int xIdx, int yIdx)
void createAdvisors (std::list< AdvisorI * > &advisors)
void propagate ()
StatePtr getStateMgr ()
std::ostream & print (std::ostream &out) const
Public Member Functions inherited from Propagator
Propagator (Domain *d, PropagatorFactory *fact=0)
virtual ~Propagator ()
void setName (const std::string &n)
const std::string & getName () const
int getID () const
void setID (int _id)
int getPriority () const
void setPriority (int p)
Domain * getDomain () const
void setPending ()
bool pending () const
PropagatorState getState () const
bool failed () const
Protected Member Functions
void updateState ()
Protected Attributes
int firstIdx
int secondIdx
Protected Attributes inherited from Propagator
Domain * domain
PropagatorFactory * factory
int id
int priority
bool dirty
PropagatorState state
std::string name
Friends
class EquivAdvisor
class EquivPropState
Detailed Description
Propagator for Equivalence constraint: x <-> y
Definition at line 42 of file logic_propagator.h.
Constructor & Destructor Documentation
EquivProp()
EquivProp::EquivProp (Domain * d, PropagatorFactory * fact, const std::string & _name, int xIdx, int yIdx)
Definition at line 218 of file logic_propagator.cpp.
References Propagator::domain, DOMINIQS_ASSERT, Propagator::name, and updateState().
Member Function Documentation
createAdvisors()
void EquivProp::createAdvisors (std::list< AdvisorI * > & advisors) virtual
Create the advisors needed to effectively propagate and return them
Reimplemented from Propagator.
Definition at line 225 of file logic_propagator.cpp.
References EquivAdvisor, firstIdx, and secondIdx.
getStateMgr()
StatePtr EquivProp::getStateMgr () virtual
Reimplemented from Propagator.
Definition at line 255 of file logic_propagator.cpp.
References EquivPropState.
print()
std::ostream & EquivProp::print (std::ostream & out) const virtual
Reimplemented from Propagator.
Definition at line 260 of file logic_propagator.cpp.
References Propagator::domain, firstIdx, Propagator::name, PropagatorStateName, secondIdx, Propagator::state, and Domain::varName().
propagate()
void EquivProp::propagate () virtual
Do a one-pass propagation of the constraint
Implements Propagator.
Definition at line 231 of file logic_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::domain, PropagatorFactory::domainReductions(), Propagator::factory, firstIdx, Domain::fixBinDown(), Domain::fixBinUp(), dominiqs::isNull(), Domain::isVarFixed(), PropagatorFactory::propCalled(), secondIdx, Propagator::state, and Domain::varLb().
updateState()
void EquivProp::updateState () protected virtual
Reimplemented from Propagator.
Definition at line 266 of file logic_propagator.cpp.
References CSTATE_ENTAILED, CSTATE_INFEAS, CSTATE_UNKNOWN, Propagator::domain, dominiqs::equal(), firstIdx, Domain::isVarFixed(), secondIdx, Propagator::state, and Domain::varLb().
Referenced by EquivProp(), EquivAdvisor::fixedDown(), and EquivAdvisor::fixedUp().
Friends And Related Function Documentation
EquivAdvisor
friend class EquivAdvisor friend
Definition at line 53 of file logic_propagator.h.
Referenced by createAdvisors().
EquivPropState
friend class EquivPropState friend
Definition at line 54 of file logic_propagator.h.
Referenced by getStateMgr().
Member Data Documentation
firstIdx
int EquivProp::firstIdx protected
Definition at line 55 of file logic_propagator.h.
Referenced by createAdvisors(), print(), propagate(), and updateState().
secondIdx
int EquivProp::secondIdx protected
Definition at line 56 of file logic_propagator.h.
Referenced by createAdvisors(), print(), propagate(), and updateState().
The documentation for this class was generated from the following files:
FP2/propagator/logic_propagator.h
FP2/propagator/logic_propagator.cpp