BRKGA for MIP feasibility: dominiqs::scoped_ptr_sse2< T > Class Template Reference
dominiqs::scoped_ptr_sse2< T > Class Template Reference
#include <machine_utils.h>
Public Types
typedef T element_type
Public Member Functions
scoped_ptr_sse2 (T *p=0) throw ()
~scoped_ptr_sse2 () throw ()
T & operator * () const throw ()
T * operator-> () const throw ()
T * get () const throw ()
T * release () throw ()
Private Member Functions
scoped_ptr_sse2 (const scoped_ptr_sse2 &other)
scoped_ptr_sse2 & operator= (const scoped_ptr_sse2 &other)
Private Attributes
T * ptr
Detailed Description
template<class T>
class dominiqs::scoped_ptr_sse2< T >
Simple scoped_ptr to automatically deallocate memory allocated with mallocSSE2 scoped_ptr_sse2 is NOT copyable Users can retake ownership of allocated memory by calling release()
Definition at line 73 of file machine_utils.h.
Member Typedef Documentation
element_type
template<class T> typedef T dominiqs::scoped_ptr_sse2< T >::element_type
Definition at line 76 of file machine_utils.h.
Constructor & Destructor Documentation
scoped_ptr_sse2() [1/2]
template<class T> dominiqs::scoped_ptr_sse2< T >::scoped_ptr_sse2 (T * p = 0) throw () inline explicit
Definition at line 77 of file machine_utils.h.
~scoped_ptr_sse2()
template<class T> dominiqs::scoped_ptr_sse2< T >::~scoped_ptr_sse2 () throw () inline
Definition at line 78 of file machine_utils.h.
References dominiqs::freeSSE2(), and dominiqs::scoped_ptr_sse2< T >::ptr.
scoped_ptr_sse2() [2/2]
template<class T> dominiqs::scoped_ptr_sse2< T >::scoped_ptr_sse2 (const scoped_ptr_sse2< T > & other) private
Member Function Documentation
get()
template<class T> T* dominiqs::scoped_ptr_sse2< T >::get () const throw () inline
Definition at line 82 of file machine_utils.h.
References dominiqs::scoped_ptr_sse2< T >::ptr.
Referenced by dominiqs::SparseVector::SparseVector().
operator *()
template<class T> T& dominiqs::scoped_ptr_sse2< T >::operator * () const throw () inline
Definition at line 80 of file machine_utils.h.
References dominiqs::scoped_ptr_sse2< T >::ptr.
operator->()
template<class T> T* dominiqs::scoped_ptr_sse2< T >::operator-> () const throw () inline
Definition at line 81 of file machine_utils.h.
References dominiqs::scoped_ptr_sse2< T >::ptr.
operator=()
template<class T> scoped_ptr_sse2& dominiqs::scoped_ptr_sse2< T >::operator= (const scoped_ptr_sse2< T > & other) private
release()
template<class T> T* dominiqs::scoped_ptr_sse2< T >::release () throw () inline
Definition at line 83 of file machine_utils.h.
References dominiqs::scoped_ptr_sse2< T >::ptr.
Referenced by dominiqs::SparseVector::SparseVector().
Member Data Documentation
ptr
template<class T> T* dominiqs::scoped_ptr_sse2< T >::ptr private
Definition at line 90 of file machine_utils.h.
Referenced by dominiqs::scoped_ptr_sse2< T >::get(), dominiqs::scoped_ptr_sse2< T >::operator *(), dominiqs::scoped_ptr_sse2< T >::operator->(), dominiqs::scoped_ptr_sse2< T >::release(), and dominiqs::scoped_ptr_sse2< T >::~scoped_ptr_sse2().
The documentation for this class was generated from the following file:
FP2/utils/machine_utils.h