BRKGA for MIP feasibility: dominiqs::GlobalAutoChrono Class Reference
dominiqs::GlobalAutoChrono Class Reference
#include <chrono.h>
Public Member Functions
GlobalAutoChrono ()
~GlobalAutoChrono ()
void stop ()
Private Attributes
bool pending
Detailed Description
Automatic global stopwatch stopper (RAII principle)
Definition at line 211 of file chrono.h.
Constructor & Destructor Documentation
GlobalAutoChrono()
dominiqs::GlobalAutoChrono::GlobalAutoChrono () inline
Definition at line 214 of file chrono.h.
References dominiqs::gChrono(), and dominiqs::Chrono::start().
~GlobalAutoChrono()
dominiqs::GlobalAutoChrono::~GlobalAutoChrono () inline
Definition at line 215 of file chrono.h.
References stop().
Member Function Documentation
stop()
void dominiqs::GlobalAutoChrono::stop () inline
Definition at line 216 of file chrono.h.
References dominiqs::gChrono(), pending, and dominiqs::Chrono::stop().
Referenced by ~GlobalAutoChrono().
Member Data Documentation
pending
bool dominiqs::GlobalAutoChrono::pending private
Definition at line 225 of file chrono.h.
Referenced by stop().
The documentation for this class was generated from the following file:
FP2/utils/chrono.h