BRKGA for MIP feasibility: dominiqs::IterationDisplay Class Reference
dominiqs::IterationDisplay Class Reference
#include <it_display.h>
Classes
class Column
class Fmt
class SimpleFmt
class SimpleFmt< double >
Public Types
typedef boost::shared_ptr< Fmt > FmtPtr
Public Member Functions
IterationDisplay ()
bool addColumn (const std::string &name, int p=0, int w=10, bool v=true, const std::string &d="-")
void removeColumn (const std::string &name)
void setVisible (const std::string &name, bool visible)
void printHeader (std::ostream &out)
bool needHeader (int k) const
void resetIteration ()
void markIteration ()
bool needPrint (int k) const
void set (const std::string &name, FmtPtr data)
void printIteration (std::ostream &out)
Public Attributes
int headerInterval
int iterationInterval
Protected Types
typedef std::map< int, Column * > ColumnMap
typedef std::map< std::string, FmtPtr > ItMap
Protected Attributes
ColumnMap columns
ItMap current
bool marked
Detailed Description
Class for printing table-like iteration logs to the terminal
Definition at line 24 of file it_display.h.
Member Typedef Documentation
ColumnMap
typedef std::map<int, Column*> dominiqs::IterationDisplay::ColumnMap protected
Definition at line 74 of file it_display.h.
FmtPtr
typedef boost::shared_ptr<Fmt> dominiqs::IterationDisplay::FmtPtr
Definition at line 34 of file it_display.h.
ItMap
typedef std::map<std::string, FmtPtr> dominiqs::IterationDisplay::ItMap protected
Definition at line 76 of file it_display.h.
Constructor & Destructor Documentation
IterationDisplay()
dominiqs::IterationDisplay::IterationDisplay () inline
Definition at line 50 of file it_display.h.
Member Function Documentation
addColumn()
bool dominiqs::IterationDisplay::addColumn (const std::string & name, int p = 0, int w = 10, bool v = true, const std::string & d = "-")
Definition at line 13 of file it_display.cpp.
References columns.
Referenced by dominiqs::FeasibilityPump::pump().
markIteration()
void dominiqs::IterationDisplay::markIteration () inline
Definition at line 57 of file it_display.h.
References marked.
needHeader()
bool dominiqs::IterationDisplay::needHeader (int k) const inline
Definition at line 55 of file it_display.h.
References headerInterval.
Referenced by dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
needPrint()
bool dominiqs::IterationDisplay::needPrint (int k) const inline
Definition at line 58 of file it_display.h.
References iterationInterval, and marked.
Referenced by dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
printHeader()
void dominiqs::IterationDisplay::printHeader (std::ostream & out)
Definition at line 46 of file it_display.cpp.
References columns.
Referenced by dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
printIteration()
void dominiqs::IterationDisplay::printIteration (std::ostream & out)
Definition at line 70 of file it_display.cpp.
References columns, and current.
Referenced by dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
removeColumn()
void dominiqs::IterationDisplay::removeColumn (const std::string & name)
Definition at line 23 of file it_display.cpp.
References columns.
resetIteration()
void dominiqs::IterationDisplay::resetIteration ()
Definition at line 64 of file it_display.cpp.
References current, and marked.
Referenced by dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
set()
void dominiqs::IterationDisplay::set (const std::string & name, FmtPtr data)
Definition at line 59 of file it_display.cpp.
References current.
Referenced by dominiqs::FeasibilityPump::perturbe(), dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
setVisible()
void dominiqs::IterationDisplay::setVisible (const std::string & name, bool visible)
Definition at line 38 of file it_display.cpp.
References columns.
Member Data Documentation
columns
ColumnMap dominiqs::IterationDisplay::columns protected
Definition at line 75 of file it_display.h.
Referenced by addColumn(), printHeader(), printIteration(), removeColumn(), and setVisible().
current
ItMap dominiqs::IterationDisplay::current protected
Definition at line 77 of file it_display.h.
Referenced by printIteration(), resetIteration(), and set().
headerInterval
int dominiqs::IterationDisplay::headerInterval
Definition at line 61 of file it_display.h.
Referenced by needHeader(), and dominiqs::FeasibilityPump::readConfig().
iterationInterval
int dominiqs::IterationDisplay::iterationInterval
Definition at line 62 of file it_display.h.
Referenced by needPrint(), and dominiqs::FeasibilityPump::readConfig().
marked
bool dominiqs::IterationDisplay::marked protected
Definition at line 78 of file it_display.h.
Referenced by markIteration(), needPrint(), and resetIteration().
The documentation for this class was generated from the following files:
FP2/utils/it_display.h
FP2/utils/it_display.cpp