BRKGA for MIP feasibility: dominiqs::App Class Reference
dominiqs::App Class Reference abstract
Provides a basic commmand-line application logic.
#include <app.h>
Public Member Functions
App ()
virtual ~App ()
void addShortcut (const std::string &shortName, const std::string &fullName)
add a shortcut to the shortcut map for command line configuration overrides
void addExtension (const std::string &ext)
add the extension of a type of input files
bool parseArgsAndConfig (int argc, char const *argv[])
parse command line arguments and config files
virtual void readConfig ()
read config params: to be implemented in derived classes
int run ()
application overall logic
Protected Member Functions
virtual bool checkUsage ()=0
check if required command line parameters are there MUST be implemented in derived classes
virtual void startup ()
additional startup work to be implemented in derived classes (optional)
virtual void exec ()=0
all custom application logic is here MUST be implemented in derived classes
virtual void shutdown ()
additional shutdown work to be implemented in derived classes (optional)
Protected Attributes
ArgsParser args
uint64_t seed
std::string outputDir
ShortcutMap shortcuts
std::vector< std::string > extensions
Private Attributes
bool parseDone
Detailed Description
Provides a basic commmand-line application logic.
The purpose of this class is to centralize common stuff such as:
Ctrl-C handling
parsing command line options / config files
open/close global logger
exception handling (main try/catch block)
Users must derived from this class to implement custom behaviour. In particular, derived classes MUST implement:
checkUsage()
exec()
Derived classes MAY also override:
readConfig()
startup() / shutdown()
Definition at line 43 of file app.h.
Constructor & Destructor Documentation
App()
dominiqs::App::App ()
Definition at line 26 of file app.cpp.
References addShortcut().
~App()
virtual dominiqs::App::~App () inline virtual
destructor
Definition at line 48 of file app.h.
Member Function Documentation
addExtension()
void dominiqs::App::addExtension (const std::string & ext)
add the extension of a type of input files
Definition at line 36 of file app.cpp.
References extensions.
Referenced by dominiqs::CPXApp::CPXApp().
addShortcut()
void dominiqs::App::addShortcut (const std::string & shortName, const std::string & fullName)
add a shortcut to the shortcut map for command line configuration overrides
Definition at line 31 of file app.cpp.
References shortcuts.
Referenced by App().
checkUsage()
virtual bool dominiqs::App::checkUsage () protected pure virtual
check if required command line parameters are there MUST be implemented in derived classes
Returns
true if successful, false otherwise
Referenced by parseArgsAndConfig().
exec()
virtual void dominiqs::App::exec () protected pure virtual
all custom application logic is here MUST be implemented in derived classes
Referenced by run().
parseArgsAndConfig()
bool dominiqs::App::parseArgsAndConfig (int argc, char const * argv[])
parse command line arguments and config files
Parameters
argc number of command line arguments (including program name)
argv vector of command line arguments
Returns
true if successful, false otherwise
Definition at line 41 of file app.cpp.
References args, checkUsage(), dominiqs::gConfig(), dominiqs::XMLConfig::get(), dominiqs::mergeConfig(), dominiqs::ArgsParser::parse(), parseDone, seed, and shortcuts.
readConfig()
virtual void dominiqs::App::readConfig () inline virtual
read config params: to be implemented in derived classes
Reimplemented in dominiqs::CPXApp.
Definition at line 68 of file app.h.
Referenced by run().
run()
int dominiqs::App::run ()
application overall logic
DO NOT to override in derived classes: derive exec() instead!!!
Returns
0 if successful, -1 otherwise
Definition at line 54 of file app.cpp.
References args, dominiqs::Logger::close(), exec(), extensions, dominiqs::gConfig(), dominiqs::XMLConfig::get(), dominiqs::getProbName(), dominiqs::gLog(), dominiqs::ArgsParser::input, dominiqs::Logger::logMsg(), dominiqs::Logger::open(), outputDir, parseDone, readConfig(), dominiqs::XMLConfig::set(), dominiqs::Logger::setConsoleEcho(), shutdown(), startup(), dominiqs::UserBreak, and dominiqs::userSignalBreak().
shutdown()
virtual void dominiqs::App::shutdown () inline protected virtual
additional shutdown work to be implemented in derived classes (optional)
Reimplemented in dominiqs::CPXApp.
Definition at line 97 of file app.h.
Referenced by run().
startup()
virtual void dominiqs::App::startup () inline protected virtual
additional startup work to be implemented in derived classes (optional)
Reimplemented in dominiqs::CPXApp.
Definition at line 87 of file app.h.
Referenced by run().
Member Data Documentation
args
ArgsParser dominiqs::App::args protected
Definition at line 99 of file app.h.
Referenced by parseArgsAndConfig(), dominiqs::CPXApp::readConfig(), run(), and dominiqs::CPXApp::startup().
extensions
std::vector<std::string> dominiqs::App::extensions protected
Definition at line 103 of file app.h.
Referenced by addExtension(), dominiqs::CPXApp::readConfig(), and run().
outputDir
std::string dominiqs::App::outputDir protected
Definition at line 101 of file app.h.
Referenced by run(), and dominiqs::CPXApp::startup().
parseDone
bool dominiqs::App::parseDone private
Definition at line 105 of file app.h.
Referenced by parseArgsAndConfig(), and run().
seed
uint64_t dominiqs::App::seed protected
Definition at line 100 of file app.h.
Referenced by parseArgsAndConfig().
shortcuts
ShortcutMap dominiqs::App::shortcuts protected
Definition at line 102 of file app.h.
Referenced by addShortcut(), and parseArgsAndConfig().
The documentation for this class was generated from the following files:
FP2/utils/app.h
FP2/utils/app.cpp