BRKGA for MIP feasibility: KnapsackProp Class Reference
KnapsackProp Class Reference
This is a propagator for the knapsack constraint: lhs <= a^T x <= rhs, a,lhs,rhs > 0, 0 <= l <= x <= u.
#include <linear_propagator.h>
Public Member Functions
KnapsackProp (Domain *d, PropagatorFactory *fact, dominiqs::Constraint *c)
void createAdvisors (std::list< AdvisorI * > &advisors)
void propagate ()
StatePtr getStateMgr ()
std::ostream & print (std::ostream &out) const
Public Member Functions inherited from Propagator
Propagator (Domain *d, PropagatorFactory *fact=0)
virtual ~Propagator ()
void setName (const std::string &n)
const std::string & getName () const
int getID () const
void setID (int _id)
int getPriority () const
void setPriority (int p)
Domain * getDomain () const
void setPending ()
bool pending () const
PropagatorState getState () const
bool failed () const
Protected Member Functions
void updateState ()
Protected Attributes
double lhs
double rhs
double minAct
double maxAct
std::vector< int > posBinIdx
std::vector< double > posBinCoef
unsigned int lastPosBin
std::vector< int > posIdx
std::vector< double > posCoef
unsigned int lastPos
double maxActDelta
Protected Attributes inherited from Propagator
Domain * domain
PropagatorFactory * factory
int id
int priority
bool dirty
PropagatorState state
std::string name
Friends
class KnapsackAdvisor
class KnapsackPropState
Detailed Description
This is a propagator for the knapsack constraint: lhs <= a^T x <= rhs, a,lhs,rhs > 0, 0 <= l <= x <= u.
Definition at line 114 of file linear_propagator.h.
Constructor & Destructor Documentation
KnapsackProp()
KnapsackProp::KnapsackProp (Domain * d, PropagatorFactory * fact, dominiqs::Constraint * c)
Definition at line 828 of file linear_propagator.cpp.
References dominiqs::SparseVector::coef(), Propagator::domain, DOMINIQS_ASSERT, dominiqs::SparseVector::idx(), INFBOUND, dominiqs::isNull(), KNAPSACK_DEFAULT_PRIORITY, lastPos, lastPosBin, lhs, maxAct, maxActDelta, minAct, Propagator::name, dominiqs::Constraint::name, posBinCoef, posBinIdx, posCoef, posIdx, dominiqs::Constraint::rhs, rhs, dominiqs::Constraint::row, dominiqs::Constraint::sense, Propagator::setPriority(), dominiqs::SparseVector::size(), updateState(), Domain::varLb(), Domain::varType(), and Domain::varUb().
Member Function Documentation
createAdvisors()
void KnapsackProp::createAdvisors (std::list< AdvisorI * > & advisors) virtual
Create the advisors needed to effectively propagate and return them
Reimplemented from Propagator.
Definition at line 883 of file linear_propagator.cpp.
References KnapsackAdvisor, lastPos, lastPosBin, posBinCoef, posBinIdx, posCoef, and posIdx.
getStateMgr()
StatePtr KnapsackProp::getStateMgr () virtual
Reimplemented from Propagator.
Definition at line 1007 of file linear_propagator.cpp.
References KnapsackPropState.
print()
std::ostream & KnapsackProp::print (std::ostream & out) const virtual
Reimplemented from Propagator.
Definition at line 1012 of file linear_propagator.cpp.
References dominiqs::greaterThan(), INFBOUND, dominiqs::lessThan(), lhs, maxAct, minAct, Propagator::name, PropagatorStateName, rhs, and Propagator::state.
propagate()
void KnapsackProp::propagate () virtual
Do a one-pass propagation of the constraint
Implements Propagator.
Definition at line 919 of file linear_propagator.cpp.
References dominiqs::ceilEps(), CSTATE_UNKNOWN, Propagator::dirty, Propagator::domain, PropagatorFactory::domainReductions(), Propagator::factory, Domain::fixBinDown(), Domain::fixBinUp(), dominiqs::floorEps(), dominiqs::greaterThan(), INFBOUND, Domain::isVarFixed(), lastPos, lastPosBin, dominiqs::lessEqualThan(), dominiqs::lessThan(), lhs, maxAct, maxActDelta, min, minAct, posBinCoef, posBinIdx, posCoef, posIdx, PropagatorFactory::propCalled(), rhs, Propagator::state, Domain::tightenLb(), Domain::tightenUb(), updateState(), Domain::varLb(), Domain::varType(), and Domain::varUb().
updateState()
void KnapsackProp::updateState () protected virtual
Reimplemented from Propagator.
Definition at line 902 of file linear_propagator.cpp.
References CSTATE_ENTAILED, CSTATE_INFEAS, CSTATE_UNKNOWN, Propagator::dirty, dominiqs::greaterEqualThan(), dominiqs::greaterThan(), dominiqs::lessEqualThan(), dominiqs::lessThan(), lhs, maxAct, minAct, rhs, and Propagator::state.
Referenced by KnapsackProp(), and propagate().
Friends And Related Function Documentation
KnapsackAdvisor
friend class KnapsackAdvisor friend
Definition at line 124 of file linear_propagator.h.
Referenced by createAdvisors().
KnapsackPropState
friend class KnapsackPropState friend
Definition at line 125 of file linear_propagator.h.
Referenced by getStateMgr().
Member Data Documentation
lastPos
unsigned int KnapsackProp::lastPos protected
Definition at line 135 of file linear_propagator.h.
Referenced by createAdvisors(), KnapsackProp(), and propagate().
lastPosBin
unsigned int KnapsackProp::lastPosBin protected
Definition at line 132 of file linear_propagator.h.
Referenced by createAdvisors(), KnapsackProp(), and propagate().
lhs
double KnapsackProp::lhs protected
Definition at line 126 of file linear_propagator.h.
Referenced by KnapsackAdvisor::fixedDown(), KnapsackProp(), print(), propagate(), KnapsackAdvisor::tightenUb(), and updateState().
maxAct
double KnapsackProp::maxAct protected
Definition at line 129 of file linear_propagator.h.
Referenced by KnapsackPropState::dump(), KnapsackAdvisor::fixedDown(), KnapsackProp(), print(), propagate(), KnapsackPropState::restore(), KnapsackAdvisor::tightenUb(), and updateState().
maxActDelta
double KnapsackProp::maxActDelta protected
Definition at line 137 of file linear_propagator.h.
Referenced by KnapsackProp(), propagate(), and KnapsackPropState::restore().
minAct
double KnapsackProp::minAct protected
Definition at line 128 of file linear_propagator.h.
Referenced by KnapsackPropState::dump(), KnapsackAdvisor::fixedUp(), KnapsackProp(), print(), propagate(), KnapsackPropState::restore(), KnapsackAdvisor::tightenLb(), and updateState().
posBinCoef
std::vector<double> KnapsackProp::posBinCoef protected
Definition at line 131 of file linear_propagator.h.
Referenced by createAdvisors(), KnapsackProp(), and propagate().
posBinIdx
std::vector<int> KnapsackProp::posBinIdx protected
Definition at line 130 of file linear_propagator.h.
Referenced by createAdvisors(), KnapsackProp(), and propagate().
posCoef
std::vector<double> KnapsackProp::posCoef protected
Definition at line 134 of file linear_propagator.h.
Referenced by createAdvisors(), KnapsackProp(), and propagate().
posIdx
std::vector<int> KnapsackProp::posIdx protected
Definition at line 133 of file linear_propagator.h.
Referenced by createAdvisors(), KnapsackProp(), and propagate().
rhs
double KnapsackProp::rhs protected
Definition at line 127 of file linear_propagator.h.
Referenced by KnapsackAdvisor::fixedUp(), KnapsackProp(), print(), propagate(), KnapsackAdvisor::tightenLb(), and updateState().
The documentation for this class was generated from the following files:
FP2/propagator/linear_propagator.h
FP2/propagator/linear_propagator.cpp