BRKGA for MIP feasibility: dominiqs::IterationDisplay::SimpleFmt< T > Class Template Reference
dominiqs::IterationDisplay::SimpleFmt< T > Class Template Reference
#include <it_display.h>
Public Member Functions
SimpleFmt (const T &v)
SimpleFmt * clone () const
std::ostream & print (std::ostream &out, int width)
Public Member Functions inherited from dominiqs::IterationDisplay::Fmt
virtual ~Fmt ()
Protected Attributes
T value
Detailed Description
template<typename T>
class dominiqs::IterationDisplay::SimpleFmt< T >
Definition at line 36 of file it_display.h.
Constructor & Destructor Documentation
SimpleFmt()
template<typename T > dominiqs::IterationDisplay::SimpleFmt< T >::SimpleFmt (const T & v) inline
Definition at line 39 of file it_display.h.
Referenced by dominiqs::IterationDisplay::SimpleFmt< T >::clone(), and dominiqs::IterationDisplay::SimpleFmt< double >::clone().
Member Function Documentation
clone()
template<typename T > SimpleFmt* dominiqs::IterationDisplay::SimpleFmt< T >::clone () const inline
Definition at line 40 of file it_display.h.
References dominiqs::IterationDisplay::SimpleFmt< T >::SimpleFmt().
print()
template<typename T > std::ostream& dominiqs::IterationDisplay::SimpleFmt< T >::print (std::ostream & out, int width) inline virtual
Reimplemented from dominiqs::IterationDisplay::Fmt.
Definition at line 41 of file it_display.h.
References dominiqs::IterationDisplay::SimpleFmt< T >::value.
Member Data Documentation
value
template<typename T > T dominiqs::IterationDisplay::SimpleFmt< T >::value protected
Definition at line 47 of file it_display.h.
Referenced by dominiqs::IterationDisplay::SimpleFmt< T >::print(), and dominiqs::IterationDisplay::SimpleFmt< double >::print().
The documentation for this class was generated from the following file:
FP2/utils/it_display.h