BRKGA for MIP feasibility: KnapsackFactory Class Reference
KnapsackFactory Class Reference
#include <linear_propagator.h>
Public Member Functions
PropagatorFactory * clone () const
int getPriority () const
const char * getName () const
Propagator * analyze (Domain *d, dominiqs::Constraint *c)
Public Member Functions inherited from PropagatorFactory
PropagatorFactory ()
virtual ~PropagatorFactory ()
void reset ()
int created () const
int & propCalled ()
int & domainReductions ()
Additional Inherited Members
Protected Attributes inherited from PropagatorFactory
int numCreated
int numPropCalled
int numDomainReductions
Detailed Description
Definition at line 142 of file linear_propagator.h.
Member Function Documentation
analyze()
Propagator * KnapsackFactory::analyze (Domain * d, dominiqs::Constraint * c) virtual
Implements PropagatorFactory.
Definition at line 1037 of file linear_propagator.cpp.
References dominiqs::SparseVector::coef(), dominiqs::SparseVector::idx(), INFBOUND, dominiqs::isNegative(), dominiqs::lessThan(), PropagatorFactory::numCreated, dominiqs::Constraint::row, dominiqs::SparseVector::size(), Domain::varLb(), and Domain::varUb().
clone()
PropagatorFactory * KnapsackFactory::clone () const virtual
Implements PropagatorFactory.
Definition at line 1022 of file linear_propagator.cpp.
getName()
const char * KnapsackFactory::getName () const virtual
Implements PropagatorFactory.
Definition at line 1032 of file linear_propagator.cpp.
getPriority()
int KnapsackFactory::getPriority () const virtual
Implements PropagatorFactory.
Definition at line 1027 of file linear_propagator.cpp.
References KNAPSACK_DEFAULT_PRIORITY.
The documentation for this class was generated from the following files:
FP2/propagator/linear_propagator.h
FP2/propagator/linear_propagator.cpp