BRKGA for MIP feasibility: clustering/c_clustering_library/cluster.c File Reference
cluster.c File Reference
#include <time.h>
#include <stdlib.h>
#include <math.h>
#include <float.h>
#include <limits.h>
#include <string.h>
#include "cluster.h"
Functions
double mean (int n, double x[])
double median (int n, double x[])
static int compare (const void *a, const void *b)
void sort (int n, const double data[], int index[])
static double * getrank (int n, double data[])
static int makedatamask (int nrows, int ncols, double ***pdata, int ***pmask)
static void freedatamask (int n, double **data, int **mask)
static double find_closest_pair (int n, double **distmatrix, int *ip, int *jp)
static int svd (int m, int n, double **u, double w[], double **vt)
int pca (int nrows, int ncolumns, double **u, double **v, double *w)
static double euclid (int n, double **data1, double **data2, int **mask1, int **mask2, const double weight[], int index1, int index2, int transpose)
static double cityblock (int n, double **data1, double **data2, int **mask1, int **mask2, const double weight[], int index1, int index2, int transpose)
static double correlation (int n, double **data1, double **data2, int **mask1, int **mask2, const double weight[], int index1, int index2, int transpose)
static double acorrelation (int n, double **data1, double **data2, int **mask1, int **mask2, const double weight[], int index1, int index2, int transpose)
static double ucorrelation (int n, double **data1, double **data2, int **mask1, int **mask2, const double weight[], int index1, int index2, int transpose)
static double uacorrelation (int n, double **data1, double **data2, int **mask1, int **mask2, const double weight[], int index1, int index2, int transpose)
static double spearman (int n, double **data1, double **data2, int **mask1, int **mask2, const double weight[], int index1, int index2, int transpose)
static double kendall (int n, double **data1, double **data2, int **mask1, int **mask2, const double weight[], int index1, int index2, int transpose)
static double uniform (void)
static int binomial (int n, double p)
static void randomassign (int nclusters, int nelements, int clusterid[])
static void getclustermeans (int nclusters, int nrows, int ncolumns, double **data, int **mask, int clusterid[], double **cdata, int **cmask, int transpose)
static void getclustermedians (int nclusters, int nrows, int ncolumns, double **data, int **mask, int clusterid[], double **cdata, int **cmask, int transpose, double cache[])
int getclustercentroids (int nclusters, int nrows, int ncolumns, double **data, int **mask, int clusterid[], double **cdata, int **cmask, int transpose, char method)
void getclustermedoids (int nclusters, int nelements, double **distance, int clusterid[], int centroids[], double errors[])
static int kmeans (int nclusters, int nrows, int ncolumns, double **data, int **mask, double weight[], int transpose, int npass, char dist, double **cdata, int **cmask, int clusterid[], double *error, int tclusterid[], int counts[], int mapping[])
static int kmedians (int nclusters, int nrows, int ncolumns, double **data, int **mask, double weight[], int transpose, int npass, char dist, double **cdata, int **cmask, int clusterid[], double *error, int tclusterid[], int counts[], int mapping[], double cache[])
void kcluster (int nclusters, int nrows, int ncolumns, double **data, int **mask, double weight[], int transpose, int npass, char method, char dist, int clusterid[], double *error, int *ifound)
void kmedoids (int nclusters, int nelements, double **distmatrix, int npass, int clusterid[], double *error, int *ifound)
double ** distancematrix (int nrows, int ncolumns, double **data, int **mask, double weights[], char dist, int transpose)
double * calculate_weights (int nrows, int ncolumns, double **data, int **mask, double weights[], int transpose, char dist, double cutoff, double exponent)
void cuttree (int nelements, Node *tree, int nclusters, int clusterid[])
static Node * pclcluster (int nrows, int ncolumns, double **data, int **mask, double weight[], double **distmatrix, char dist, int transpose)
static int nodecompare (const void *a, const void *b)
static Node * pslcluster (int nrows, int ncolumns, double **data, int **mask, double weight[], double **distmatrix, char dist, int transpose)
static Node * pmlcluster (int nelements, double **distmatrix)
static Node * palcluster (int nelements, double **distmatrix)
Node * treecluster (int nrows, int ncolumns, double **data, int **mask, double weight[], int transpose, char dist, char method, double **distmatrix)
static void somworker (int nrows, int ncolumns, double **data, int **mask, const double weights[], int transpose, int nxgrid, int nygrid, double inittau, double ***celldata, int niter, char dist)
static void somassign (int nrows, int ncolumns, double **data, int **mask, const double weights[], int transpose, int nxgrid, int nygrid, double ***celldata, char dist, int clusterid[][2])
void somcluster (int nrows, int ncolumns, double **data, int **mask, const double weight[], int transpose, int nxgrid, int nygrid, double inittau, int niter, char dist, double ***celldata, int clusterid[][2])
double clusterdistance (int nrows, int ncolumns, double **data, int **mask, double weight[], int n1, int n2, int index1[], int index2[], char dist, char method, int transpose)
Variables
static const double * sortdata = NULL
static double(*)(int, double **, double **, int **, int **, const double[], int, int, int) setmetric (char dist)
Function Documentation
acorrelation()
static double acorrelation (int n, double ** data1, double ** data2, int ** mask1, int ** mask2, const double weight[], int index1, int index2, int transpose) static
Definition at line 1193 of file cluster.c.
binomial()
static int binomial (int n, double p) static
Definition at line 1801 of file cluster.c.
References uniform().
Referenced by randomassign().
calculate_weights()
double* calculate_weights (int nrows, int ncolumns, double ** data, int ** mask, double weights[], int transpose, char dist, double cutoff, double exponent)
Definition at line 3016 of file cluster.c.
References setmetric.
cityblock()
static double cityblock (int n, double ** data1, double ** data2, int ** mask1, int ** mask2, const double weight[], int index1, int index2, int transpose) static
Definition at line 1017 of file cluster.c.
clusterdistance()
double clusterdistance (int nrows, int ncolumns, double ** data, int ** mask, double weight[], int n1, int n2, int index1[], int index2[], char dist, char method, int transpose)
Definition at line 4245 of file cluster.c.
References median(), and setmetric.
compare()
static int compare (const void * a, const void * b) static
Definition at line 173 of file cluster.c.
References sortdata.
Referenced by sort().
correlation()
static double correlation (int n, double ** data1, double ** data2, int ** mask1, int ** mask2, const double weight[], int index1, int index2, int transpose) static
Definition at line 1093 of file cluster.c.
cuttree()
void cuttree (int nelements, Node * tree, int nclusters, int clusterid[])
Definition at line 3118 of file cluster.c.
References Node::left, and Node::right.
distancematrix()
double** distancematrix (int nrows, int ncolumns, double ** data, int ** mask, double weights[], char dist, int transpose)
Definition at line 2914 of file cluster.c.
References setmetric.
Referenced by treecluster().
euclid()
static double euclid (int n, double ** data1, double ** data2, int ** mask1, int ** mask2, const double weight[], int index1, int index2, int transpose) static
Definition at line 942 of file cluster.c.
find_closest_pair()
static double find_closest_pair (int n, double ** distmatrix, int * ip, int * jp) static
Definition at line 294 of file cluster.c.
Referenced by palcluster(), pclcluster(), and pmlcluster().
freedatamask()
static void freedatamask (int n, double ** data, int ** mask) static
Definition at line 281 of file cluster.c.
Referenced by kcluster().
getclustercentroids()
int getclustercentroids (int nclusters, int nrows, int ncolumns, double ** data, int ** mask, int clusterid[], double ** cdata, int ** cmask, int transpose, char method)
Definition at line 2218 of file cluster.c.
References getclustermeans(), and getclustermedians().
getclustermeans()
static void getclustermeans (int nclusters, int nrows, int ncolumns, double ** data, int ** mask, int clusterid[], double ** cdata, int ** cmask, int transpose) static
Definition at line 2001 of file cluster.c.
Referenced by getclustercentroids(), and kmeans().
getclustermedians()
static void getclustermedians (int nclusters, int nrows, int ncolumns, double ** data, int ** mask, int clusterid[], double ** cdata, int ** cmask, int transpose, double cache[]) static
Definition at line 2111 of file cluster.c.
References median().
Referenced by getclustercentroids(), and kmedians().
getclustermedoids()
void getclustermedoids (int nclusters, int nelements, double ** distance, int clusterid[], int centroids[], double errors[])
Definition at line 2306 of file cluster.c.
Referenced by kmedoids().
getrank()
static double* getrank (int n, double data[]) static
Definition at line 201 of file cluster.c.
References sort().
Referenced by spearman().
kcluster()
void kcluster (int nclusters, int nrows, int ncolumns, double ** data, int ** mask, double weight[], int transpose, int npass, char method, char dist, int clusterid[], double * error, int * ifound)
Definition at line 2572 of file cluster.c.
References freedatamask(), kmeans(), kmedians(), and makedatamask().
kendall()
static double kendall (int n, double ** data1, double ** data2, int ** mask1, int ** mask2, const double weight[], int index1, int index2, int transpose) static
Definition at line 1610 of file cluster.c.
kmeans()
static int kmeans (int nclusters, int nrows, int ncolumns, double ** data, int ** mask, double weight[], int transpose, int npass, char dist, double ** cdata, int ** cmask, int clusterid[], double * error, int tclusterid[], int counts[], int mapping[]) static
Definition at line 2363 of file cluster.c.
References getclustermeans(), randomassign(), and setmetric.
Referenced by kcluster().
kmedians()
static int kmedians (int nclusters, int nrows, int ncolumns, double ** data, int ** mask, double weight[], int transpose, int npass, char dist, double ** cdata, int ** cmask, int clusterid[], double * error, int tclusterid[], int counts[], int mapping[], double cache[]) static
Definition at line 2468 of file cluster.c.
References getclustermedians(), randomassign(), and setmetric.
Referenced by kcluster().
kmedoids()
void kmedoids (int nclusters, int nelements, double ** distmatrix, int npass, int clusterid[], double * error, int * ifound)
Definition at line 2738 of file cluster.c.
References getclustermedoids(), and randomassign().
makedatamask()
static int makedatamask (int nrows, int ncols, double *** pdata, int *** pmask) static
Definition at line 241 of file cluster.c.
Referenced by kcluster(), and pclcluster().
mean()
double mean (int n, double x[])
Definition at line 62 of file cluster.c.
Referenced by MTRand::randNorm().
median()
double median (int n, double x[])
Definition at line 72 of file cluster.c.
References max, and min.
Referenced by clusterdistance(), and getclustermedians().
nodecompare()
static int nodecompare (const void * a, const void * b) static
Definition at line 3354 of file cluster.c.
References Node::distance.
Referenced by pslcluster().
palcluster()
static Node* palcluster (int nelements, double ** distmatrix) static
Definition at line 3621 of file cluster.c.
References Node::distance, find_closest_pair(), Node::left, and Node::right.
Referenced by treecluster().
pca()
int pca (int nrows, int ncolumns, double ** u, double ** v, double * w)
Definition at line 817 of file cluster.c.
References sort(), and svd().
pclcluster()
static Node* pclcluster (int nrows, int ncolumns, double ** data, int ** mask, double weight[], double ** distmatrix, char dist, int transpose) static
Definition at line 3191 of file cluster.c.
References Node::distance, find_closest_pair(), Node::left, makedatamask(), Node::right, and setmetric.
Referenced by treecluster().
pmlcluster()
static Node* pmlcluster (int nelements, double ** distmatrix) static
Definition at line 3545 of file cluster.c.
References Node::distance, find_closest_pair(), Node::left, max, and Node::right.
Referenced by treecluster().
pslcluster()
static Node* pslcluster (int nrows, int ncolumns, double ** data, int ** mask, double weight[], double ** distmatrix, char dist, int transpose) static
Definition at line 3368 of file cluster.c.
References Node::distance, Node::left, nodecompare(), Node::right, and setmetric.
Referenced by treecluster().
randomassign()
static void randomassign (int nclusters, int nelements, int clusterid[]) static
Definition at line 1944 of file cluster.c.
References binomial(), and uniform().
Referenced by kmeans(), kmedians(), and kmedoids().
somassign()
static void somassign (int nrows, int ncolumns, double ** data, int ** mask, const double weights[], int transpose, int nxgrid, int nygrid, double *** celldata, char dist, int clusterid[][2]) static
Definition at line 4048 of file cluster.c.
References setmetric.
Referenced by somcluster().
somcluster()
void somcluster (int nrows, int ncolumns, double ** data, int ** mask, const double weight[], int transpose, int nxgrid, int nygrid, double inittau, int niter, char dist, double *** celldata, int clusterid[][2])
Definition at line 4132 of file cluster.c.
References somassign(), and somworker().
somworker()
static void somworker (int nrows, int ncolumns, double ** data, int ** mask, const double weights[], int transpose, int nxgrid, int nygrid, double inittau, double *** celldata, int niter, char dist) static
Definition at line 3849 of file cluster.c.
References setmetric, and uniform().
Referenced by somcluster().
sort()
void sort (int n, const double data[], int index[])
Definition at line 188 of file cluster.c.
References compare(), and sortdata.
Referenced by FeasibilityPump_Decoder::analyzeAndFixVars(), FeasibilityPump_Decoder::buildConstraint2VariableMatrix(), FeasibilityPump_Decoder::determineFixingPercentage(), getrank(), FeasibilityPump_Decoder::getRelaxBinaryValues(), main(), FeasibilityPump_Decoder::objectiveFeasibilityPump(), pca(), dominiqs::CutPool::purge(), dominiqs::CutPool::select(), and BRKGA_ALG::Population::sortFitness().
spearman()
static double spearman (int n, double ** data1, double ** data2, int ** mask1, int ** mask2, const double weight[], int index1, int index2, int transpose) static
Definition at line 1482 of file cluster.c.
References getrank().
svd()
static int svd (int m, int n, double ** u, double w[], double ** vt) static
Definition at line 335 of file cluster.c.
References max, and dominiqs::scale().
Referenced by pca().
treecluster()
Node* treecluster (int nrows, int ncolumns, double ** data, int ** mask, double weight[], int transpose, char dist, char method, double ** distmatrix)
Definition at line 3726 of file cluster.c.
References distancematrix(), palcluster(), pclcluster(), pmlcluster(), and pslcluster().
Referenced by ce_andrade::Clusterator::hierarchicalClustering().
uacorrelation()
static double uacorrelation (int n, double ** data1, double ** data2, int ** mask1, int ** mask2, const double weight[], int index1, int index2, int transpose) static
Definition at line 1387 of file cluster.c.
ucorrelation()
static double ucorrelation (int n, double ** data1, double ** data2, int ** mask1, int ** mask2, const double weight[], int index1, int index2, int transpose) static
Definition at line 1292 of file cluster.c.
uniform()
static double uniform (void) static
Definition at line 1738 of file cluster.c.
References dominiqs::scale().
Referenced by binomial(), randomassign(), and somworker().
Variable Documentation
setmetric
double(*)(int, double**, double**, int**, int**, const double[], int, int, int) setmetric(char dist) static
Definition at line 1720 of file cluster.c.
Referenced by calculate_weights(), clusterdistance(), distancematrix(), kmeans(), kmedians(), pclcluster(), pslcluster(), somassign(), and somworker().
sortdata
const double* sortdata = NULL static
Definition at line 168 of file cluster.c.
Referenced by compare(), and sort().