BRKGA for MIP feasibility: clustering/c_clustering_library/cluster.h File Reference
cluster.h File Reference
Classes
struct Node
Macros
#define min(x, y) ((x) < (y) ? (x) : (y))
#define max(x, y) ((x) > (y) ? (x) : (y))
#define CLUSTERVERSION "1.52a"
Functions
double clusterdistance (int nrows, int ncolumns, double **data, int **mask, double weight[], int n1, int n2, int index1[], int index2[], char dist, char method, int transpose)
double ** distancematrix (int ngenes, int ndata, double **data, int **mask, double *weight, char dist, int transpose)
int getclustercentroids (int nclusters, int nrows, int ncolumns, double **data, int **mask, int clusterid[], double **cdata, int **cmask, int transpose, char method)
void getclustermedoids (int nclusters, int nelements, double **distance, int clusterid[], int centroids[], double errors[])
void kcluster (int nclusters, int ngenes, int ndata, double **data, int **mask, double weight[], int transpose, int npass, char method, char dist, int clusterid[], double *error, int *ifound)
void kmedoids (int nclusters, int nelements, double **distance, int npass, int clusterid[], double *error, int *ifound)
Node * treecluster (int nrows, int ncolumns, double **data, int **mask, double weight[], int transpose, char dist, char method, double **distmatrix)
void cuttree (int nelements, Node *tree, int nclusters, int clusterid[])
void somcluster (int nrows, int ncolumns, double **data, int **mask, const double weight[], int transpose, int nxnodes, int nynodes, double inittau, int niter, char dist, double ***celldata, int clusterid[][2])
int pca (int m, int n, double **u, double **v, double *w)
void sort (int n, const double data[], int index[])
double mean (int n, double x[])
double median (int n, double x[])
double * calculate_weights (int nrows, int ncolumns, double **data, int **mask, double weights[], int transpose, char dist, double cutoff, double exponent)
Macro Definition Documentation
CLUSTERVERSION
#define CLUSTERVERSION "1.52a"
Definition at line 45 of file cluster.h.
max
#define max (x, y) ((x) > (y) ? (x) : (y))
Definition at line 38 of file cluster.h.
min
#define min (x, y) ((x) < (y) ? (x) : (y))
Definition at line 35 of file cluster.h.
Function Documentation
calculate_weights()
double* calculate_weights (int nrows, int ncolumns, double ** data, int ** mask, double weights[], int transpose, char dist, double cutoff, double exponent)
Definition at line 3016 of file cluster.c.
References setmetric.
clusterdistance()
double clusterdistance (int nrows, int ncolumns, double ** data, int ** mask, double weight[], int n1, int n2, int index1[], int index2[], char dist, char method, int transpose)
Definition at line 4245 of file cluster.c.
References median(), and setmetric.
cuttree()
void cuttree (int nelements, Node * tree, int nclusters, int clusterid[])
Definition at line 3118 of file cluster.c.
References Node::left, and Node::right.
distancematrix()
double** distancematrix (int ngenes, int ndata, double ** data, int ** mask, double * weight, char dist, int transpose)
getclustercentroids()
int getclustercentroids (int nclusters, int nrows, int ncolumns, double ** data, int ** mask, int clusterid[], double ** cdata, int ** cmask, int transpose, char method)
Definition at line 2218 of file cluster.c.
References getclustermeans(), and getclustermedians().
getclustermedoids()
void getclustermedoids (int nclusters, int nelements, double ** distance, int clusterid[], int centroids[], double errors[])
Definition at line 2306 of file cluster.c.
Referenced by kmedoids().
kcluster()
void kcluster (int nclusters, int ngenes, int ndata, double ** data, int ** mask, double weight[], int transpose, int npass, char method, char dist, int clusterid[], double * error, int * ifound)
Definition at line 2572 of file cluster.c.
References freedatamask(), kmeans(), kmedians(), and makedatamask().
kmedoids()
void kmedoids (int nclusters, int nelements, double ** distance, int npass, int clusterid[], double * error, int * ifound)
Definition at line 2738 of file cluster.c.
References getclustermedoids(), and randomassign().
mean()
double mean (int n, double x[])
Definition at line 62 of file cluster.c.
Referenced by MTRand::randNorm().
median()
double median (int n, double x[])
Definition at line 72 of file cluster.c.
References max, and min.
Referenced by clusterdistance(), and getclustermedians().
pca()
int pca (int m, int n, double ** u, double ** v, double * w)
Definition at line 817 of file cluster.c.
References sort(), and svd().
somcluster()
void somcluster (int nrows, int ncolumns, double ** data, int ** mask, const double weight[], int transpose, int nxnodes, int nynodes, double inittau, int niter, char dist, double *** celldata, int clusterid[][2])
Definition at line 4132 of file cluster.c.
References somassign(), and somworker().
sort()
void sort (int n, const double data[], int index[])
Definition at line 188 of file cluster.c.
References compare(), and sortdata.
Referenced by FeasibilityPump_Decoder::analyzeAndFixVars(), FeasibilityPump_Decoder::buildConstraint2VariableMatrix(), FeasibilityPump_Decoder::determineFixingPercentage(), getrank(), FeasibilityPump_Decoder::getRelaxBinaryValues(), main(), FeasibilityPump_Decoder::objectiveFeasibilityPump(), pca(), dominiqs::CutPool::purge(), dominiqs::CutPool::select(), and BRKGA_ALG::Population::sortFitness().
treecluster()
Node* treecluster (int nrows, int ncolumns, double ** data, int ** mask, double weight[], int transpose, char dist, char method, double ** distmatrix)
Definition at line 3726 of file cluster.c.
References distancematrix(), palcluster(), pclcluster(), pmlcluster(), and pslcluster().
Referenced by ce_andrade::Clusterator::hierarchicalClustering().