BRKGA for MIP feasibility: fix_and_local_search_random.cpp File Reference
fix_and_local_search_random.cpp File Reference
#include "feasibility_pump_decoder.hpp"
#include "mtrand.hpp"
#include "brkga.hpp"
#include "distance_function_base.hpp"
#include "hamming_distance.hpp"
#include "execution_stopper.hpp"
#include <iostream>
#include <fstream>
#include <iomanip>
#include <stdexcept>
#include <algorithm>
#include <iterator>
#include <limits>
#include <utility>
#include <cstdlib>
#include <cmath>
#include <unordered_set>
#include <vector>
#include "pragma_diagnostic_ignored_header.hpp"
#include <boost/timer/timer.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/filesystem.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include "pragma_diagnostic_ignored_footer.hpp"
Enumerations
enum StopRule {
StopRule::GENERATIONS = 'G', StopRule::TARGET = 'T', StopRule::IMPROVEMENT = 'I', StopRule::GENERATIONS = 'G',
StopRule::TARGET = 'T', StopRule::IMPROVEMENT = 'I', StopRule::GENERATIONS = 'G', StopRule::TARGET = 'T',
StopRule::IMPROVEMENT = 'I'
}
Functions
void show_usage_info (const char *exec_name, bool full)
int main (int argc, char *argv[])
Variables
const double EPS = 1e-6
Enumeration Type Documentation
StopRule
enum StopRule strong
Enumerator
GENERATIONS
TARGET
IMPROVEMENT
GENERATIONS
TARGET
IMPROVEMENT
GENERATIONS
TARGET
IMPROVEMENT
Definition at line 64 of file fix_and_local_search_random.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 195 of file fix_and_local_search_random.cpp.
References FeasibilityPump_Decoder::ALL, FeasibilityPump_Decoder::AUTOMATIC, FeasibilityPump_Decoder::binary_variables_per_thread, FeasibilityPump_Decoder::constraint_filtering_type, FeasibilityPump_Decoder::CONVEX, FeasibilityPump_Decoder::decode(), FeasibilityPump_Decoder::DEFAULT, FeasibilityPump_Decoder::ObjFPparams::delta, FeasibilityPump_Decoder::environment_per_thread, EPS, BRKGA_ALG::Chromosome::feasibility_pump_value, FeasibilityPump_Decoder::feasible_before_var_unfixing, BRKGA_ALG::Chromosome::fractionality, GENERATIONS, FeasibilityPump_Decoder::GEOMETRIC, BRKGA_ALG::Population::getChromosome(), FeasibilityPump_Decoder::getChromosomeSize(), FeasibilityPump_Decoder::getNumBinaryVariables(), FeasibilityPump_Decoder::getNumConstraints(), FeasibilityPump_Decoder::getNumVariables(), BRKGA_ALG::Population::getP(), FeasibilityPump_Decoder::getSense(), IMPROVEMENT, ExecutionStopper::init(), FeasibilityPump_Decoder::init(), FeasibilityPump_Decoder::FPparams::iteration_limit, max, FeasibilityPump_Decoder::MOST_FRACTIONALS, FeasibilityPump_Decoder::MOST_ONES, FeasibilityPump_Decoder::MOST_ZEROS, ExecutionStopper::mustStop(), FeasibilityPump_Decoder::NONZERO_DUALS_NONZERO_SLACKS, FeasibilityPump_Decoder::num_constraints_used, BRKGA_ALG::Chromosome::num_iterations, BRKGA_ALG::Chromosome::num_non_integral_vars, FeasibilityPump_Decoder::OBJECTIVE, FeasibilityPump_Decoder::ONLY_NONZERO_DUALS, FeasibilityPump_Decoder::percentage_ones_initial_relaxation, FeasibilityPump_Decoder::percentage_zeros_initial_relaxation, FeasibilityPump_Decoder::FPparams::perturb_when_cycling, FeasibilityPump_Decoder::ObjFPparams::phi, MTRand::rand(), FeasibilityPump_Decoder::relaxation_time, FeasibilityPump_Decoder::FPparams::rho_lb, FeasibilityPump_Decoder::FPparams::rho_ub, BRKGA_ALG::Chromosome::rounded, FeasibilityPump_Decoder::rounding_cuts, show_usage_info(), FeasibilityPump_Decoder::solved_lps_per_thread, FeasibilityPump_Decoder::FPparams::t, TARGET, ExecutionStopper::timerResume(), ExecutionStopper::timerStart(), ExecutionStopper::timerStop(), BRKGA_ALG::Chromosome::type, FeasibilityPump_Decoder::var_fixing_type, and FeasibilityPump_Decoder::variable_fixing_percentage.
show_usage_info()
void show_usage_info (const char * exec_name, bool full)
Definition at line 68 of file fix_and_local_search_random.cpp.
Referenced by main().
Variable Documentation
EPS
const double EPS = 1e-6
Definition at line 59 of file fix_and_local_search_random.cpp.
Referenced by main().