BRKGA for MIP feasibility: dominiqs Namespace Reference
dominiqs Namespace Reference
Namespaces
details
Classes
class App
Provides a basic commmand-line application logic.
class ArgsParser
class AutoChrono
class AutoSection
class BBLimits
struct Category
struct CategoryPredicate
class Chrono
class Constraint
class CPXApp
Provides a basic Cplex commmand-line application It adds to the basic App the following Cplex-related features:
class CpxPresolver
class Cut
struct CutCmpByScore
struct CutCmpForPurge
struct CutOrthoFilter
class CutPool
struct cutptr_equal
struct cutptr_hash
struct DefaultPredicate
struct DefaultRaiser
class Enforcer
struct Entry
struct EntryPredicate
class Factory
class FeasibilityPump
Basic Feasibility Pump Scheme Accepts custom rounders.
class GlobalAutoChrono
class GlobalAutoSection
class GomorySeparator
class IncrementalGeomMean
class IncrementalMean
class IncrementalVariance
class IniFile
class IniParserContext
class intrusive_weak_ptr
Real intrusive weak pointer.
struct intrusive_weak_ptr_base
class IterationDisplay
class Logger
class ManagedObject
Managed Object.
class ManagedObjectWeak
Managed Object Weak.
class Model
class numarray
Vector replacement for numerical data.
class ObjScopeGuardImpl0
class ObjScopeGuardImpl1
class ObjScopeGuardImpl2
class OptimalFaceFixer
class Path
Path Class Convenience path handling class Its main usage is to recursively create directories. Eventually there will be a portable way to do it...
class PriorityQueue
class ProbInfo
class RandCharGen
class RandGen
class RefHolder
class ResourceUsage
class scoped_ptr_sse2
class ScopeGuardImpl0
class ScopeGuardImpl1
class ScopeGuardImpl2
class ScopeGuardImpl3
class ScopeGuardImplBase
class Serializer
class SingletonHolder
class SolutionTransformer
class SparseVector
class STLRandGen
class Undoable
class UnitRandGen
class Var
class WarmStart
struct XMLCategory
class XMLConfig
class XmlDoc
class XmlNode
Typedefs
typedef int(CPXPUBLIC * BranchCbPtr) (CALLBACK_BRANCH_ARGS)
typedef CPXENVptr Env
typedef CPXCENVptr CEnv
typedef CPXLPptr Prob
typedef CPXCLPptr CProb
typedef boost::shared_ptr< Var > VarPtr
typedef boost::shared_ptr< SolutionTransformer > SolutionTransformerPtr
typedef SingletonHolder< Factory< SolutionTransformer, std::string > > TransformersFactory
typedef std::map< std::string, std::string > ShortcutMap
typedef boost::intrusive_ptr< Cut > CutPtr
typedef std::vector< CutPtr > CutList
typedef char char_t
typedef file_iterator< char_t > iterator_t
typedef scanner< iterator_t > scanner_t
typedef rule< scanner_t > rule_t
typedef std::list< Entry > EntryList
typedef boost::shared_ptr< Category > CategoryPtr
typedef boost::shared_ptr< IniFile > IniFilePtr
typedef boost::shared_ptr< Logger > LoggerPtr
typedef boost::shared_ptr< SparseVector > SparseVectorPtr
typedef boost::shared_ptr< std::vector< int > > IntegerVectorPtr
typedef boost::shared_ptr< std::vector< double > > FloatVectorPtr
typedef boost::intrusive_ptr< Constraint > ConstraintPtr
typedef std::map< std::string, std::string > AttributeMap
typedef const ScopeGuardImplBase & ScopeGuard
typedef boost::shared_ptr< XMLCategory > XMLCategoryPtr
Enumerations
enum ParserStatus { DEFAULT, CONFIG, OVERRIDE, OUTPUT }
Functions
static int infoCB (CEnv env, void *cbdata, int wherefrom, void *cbhandle)
void cpxBB (Env env, Prob lp, double objOffset, dominiqs::CutPool &pool, std::vector< double > &x, BBLimits &limits)
void getVarNames (CEnv env, CProb lp, std::vector< std::string > &names, int begin, int end)
void getConstrNames (CEnv env, CProb lp, std::vector< std::string > &names, int begin, int end)
int getRowSupportLength (CEnv env, CProb lp, int row_idx)
int getColSupportLength (CEnv env, CProb lp, int col_idx)
void addCut (CEnv env, Prob lp, const std::string &name, const int *idx, const double *val, int cnt, char sense, double rhs)
void addCut (CEnv env, Prob lp, const std::string &name, const SparseVector &row, char sense, double rhs)
void addUserCut (CEnv env, Prob lp, const std::string &name, const SparseVector &row, char sense, double rhs)
void addEmptyVar (CEnv env, Prob lp, const std::string &name, char ctype, double lb, double ub, double obj)
void addVar (CEnv env, Prob lp, const std::string &name, const int *idx, const double *val, int cnt, char ctype, double lb, double ub, double obj)
void addVar (CEnv env, Prob lp, const std::string &name, const SparseVector &col, char ctype, double lb, double ub, double obj)
void getCut (CEnv env, CProb lp, int row_idx, SparseVector &row, char &sense, double &rhs)
void getCut (CEnv env, CProb lp, const std::string &row_name, SparseVector &row, char &sense, double &rhs)
void getVar (CEnv env, CProb lp, int col_idx, SparseVector &col, char &type, double &lb, double &ub, double &obj)
void getVar (CEnv env, CProb lp, const std::string &col_name, SparseVector &col, char &type, double &lb, double &ub, double &obj)
void delCut (CEnv env, Prob lp, const std::string &row_name)
void delCut (CEnv env, Prob lp, int row_idx)
void delVar (CEnv env, Prob lp, int col_idx)
void addMIPStart (CEnv env, Prob lp, const double *sol, int cnt)
static int branchCB (CALLBACK_BRANCH_ARGS)
void delVar (CEnv env, Prob lp, const std::string &col_name)
void lexMin (Env env, Prob lp, bool isMin, bool skipOrigObj, int *rank, int rankCnt)
static double GMIcoef (double alpha, char type, double f0, double ratio, double eps)
void printCut (std::ostream &out, const Model &m, const Cut &c)
template<class T >
std::ostream & operator<< (std::ostream &out, const std::vector< T > &v)
static void userSignalBreak (int signum)
void mergeConfig (const ArgsParser &args, XMLConfig &config, const ShortcutMap &shortcuts)
ptrdiff_t b64_encode (const uint8_t *begin, const uint8_t *end, uint8_t *out, size_t out_size)
void b64_encode (const uint8_t *begin, const uint8_t *end, std::string &out)
ptrdiff_t b64_decode (const uint8_t *begin, const uint8_t *end, uint8_t *out, size_t out_size)
ptrdiff_t b64_decode (const std::string &in, uint8_t *out, size_t out_size)
template<class T >
void b64_encode (const T &obj, std::string &out)
template<class T >
ptrdiff_t b64_decode (const std::string &in, T &out)
Chrono & gChrono ()
template<class P , class R , typename T >
Enforcer< const T &, P, R > MakeEnforcer (const T &t, const char *locus)
template<class P , class R , typename T >
Enforcer< T &, P, R > MakeEnforcer (T &t, const char *locus)
template<typename BaseClassType , typename ClassType , typename... Args>
BaseClassType * Creator (Args... args)
bool equal (double x, double y, double eps=defaultEPS)
bool relEqual (double x, double y, double eps=defaultEPS)
bool different (double x, double y, double eps=defaultEPS)
bool lessThan (double x, double y, double eps=defaultEPS)
bool greaterThan (double x, double y, double eps=defaultEPS)
bool lessEqualThan (double x, double y, double eps=defaultEPS)
bool greaterEqualThan (double x, double y, double eps=defaultEPS)
bool isNegative (double x, double eps=defaultEPS)
bool isPositive (double x, double eps=defaultEPS)
bool isNull (double x, double eps=defaultEPS)
bool isNotNull (double x, double eps=defaultEPS)
double floorEps (double x, double eps=defaultEPS)
double ceilEps (double x, double eps=defaultEPS)
double fractionalPart (double x, double eps=defaultEPS)
double integralityViolation (double x, double eps=defaultEPS)
bool isInteger (double x, double eps=defaultEPS)
template<class int_type >
int_type double2int (double x)
std::ostream & operator<< (std::ostream &out, const Category &c)
IniFile & gConfig2 ()
template<class T , class U >
bool operator== (const intrusive_weak_ptr< T > &a, const intrusive_weak_ptr< U > &b)
template<class T , class U >
bool operator!= (const intrusive_weak_ptr< T > &a, const intrusive_weak_ptr< U > &b)
template<class T , class U >
bool operator< (const intrusive_weak_ptr< T > &a, const intrusive_weak_ptr< U > &b)
template<class T , class U >
intrusive_weak_ptr< T > static_pointer_cast (const intrusive_weak_ptr< U > &p)
template<class T , class U >
intrusive_weak_ptr< T > dynamic_pointer_cast (const intrusive_weak_ptr< U > &p)
Logger & gLog ()
void * mallocSSE2 (std::size_t size)
void freeSSE2 (void *ptr)
double getPhysicalMemory ()
double getAvailableMemory ()
int getNumPhysicalCores ()
int getNumLogicalCores ()
void intrusive_ptr_add_ref (ManagedObjectWeak *obj)
void intrusive_ptr_release (ManagedObjectWeak *obj)
intrusive_weak_ptr_base * intrusive_weak_ptr_get_head (ManagedObjectWeak *obj)
void intrusive_weak_ptr_set_head (ManagedObjectWeak *obj, intrusive_weak_ptr_base *ptr)
void accumulate (double *v, const double *w, int n, double lambda)
void accumulate (double *v, const int *wIdx, const double *wCoef, int n, double lambda)
void scale (double *v, int n, double lambda)
double dotProduct (const double *x, const double *y, int n)
double dotProduct (const int *idx, const double *x, int n, const double *y)
bool disjoint (const double *x, const double *y, int n)
double euclidianNorm (const double *v, int n)
double euclidianDistance (const double *a1, const double *a2, int n)
int lexComp (const double *s1, const double *s2, int n)
template<typename ForwardIterator , typename T >
void iota (ForwardIterator first, ForwardIterator last, T value)
void accumulate (double *v, const SparseVector &w, double lambda=1.0)
double dotProduct (const SparseVector &a1, const double *a2)
template<typename ForwardIterator >
double variance (ForwardIterator first, ForwardIterator last, bool fromSample=false)
template<typename ForwardIterator >
double geomMean (ForwardIterator first, ForwardIterator last)
template<typename ForwardIterator >
double mean (ForwardIterator first, ForwardIterator last)
template<class T >
T getTextContent (const XmlNode &node, const T &defValue)
template<class T >
T getBase64Content (const XmlNode &node, const T &defValue)
double getMachineEps ()
bool float2frac (double r, double mindelta, double maxdelta, int maxden, int &n, int &d)
bool float2simplefrac (double r, double mindelta, double maxdelta, int maxden, int &n, int &d)
bool findFrac (double lb, double ub, int maxden, int &n, int &d)
template<typename IntType >
IntType gcd (IntType n, IntType m)
template<typename IntType >
IntType lcm (IntType n, IntType m)
template<typename IntType >
double choose (IntType m, IntType n)
std::string getCwd ()
Get The Current Working Directory Convenience wrapper around getcwd.
std::string getProbName (const std::string &fileName, const std::vector< std::string > &exts)
Get the problem name from a LP/MPS file.
std::string getProbName (const std::string &fileName)
uint64_t generateSeed (uint64_t seed)
double getLoadAvg ()
template<class T >
RefHolder< T > ByRef (T &t)
template<typename F >
ScopeGuardImpl0< F > MakeGuard (F fun)
template<typename F , typename P1 >
ScopeGuardImpl1< F, P1 > MakeGuard (F fun, P1 p1)
template<typename F , typename P1 , typename P2 >
ScopeGuardImpl2< F, P1, P2 > MakeGuard (F fun, P1 p1, P2 p2)
template<typename F , typename P1 , typename P2 , typename P3 >
ScopeGuardImpl3< F, P1, P2, P3 > MakeGuard (F fun, P1 p1, P2 p2, P3 p3)
template<class Obj , typename MemFun >
ObjScopeGuardImpl0< Obj, MemFun > MakeObjGuard (Obj &obj, MemFun memFun)
template<typename Ret , class Obj1 , class Obj2 >
ObjScopeGuardImpl0< Obj1, Ret(Obj2::*)()> MakeGuard (Ret(Obj2::*memFun)(), Obj1 &obj)
template<typename Ret , class Obj1 , class Obj2 >
ObjScopeGuardImpl0< Obj1, Ret(Obj2::*)()> MakeGuard (Ret(Obj2::*memFun)(), Obj1 *obj)
template<class Obj , typename MemFun , typename P1 >
ObjScopeGuardImpl1< Obj, MemFun, P1 > MakeObjGuard (Obj &obj, MemFun memFun, P1 p1)
template<typename Ret , class Obj1 , class Obj2 , typename P1a , typename P1b >
ObjScopeGuardImpl1< Obj1, Ret(Obj2::*)(P1a), P1b > MakeGuard (Ret(Obj2::*memFun)(P1a), Obj1 &obj, P1b p1)
template<typename Ret , class Obj1 , class Obj2 , typename P1a , typename P1b >
ObjScopeGuardImpl1< Obj1, Ret(Obj2::*)(P1a), P1b > MakeGuard (Ret(Obj2::*memFun)(P1a), Obj1 *obj, P1b p1)
template<class Obj , typename MemFun , typename P1 , typename P2 >
ObjScopeGuardImpl2< Obj, MemFun, P1, P2 > MakeObjGuard (Obj &obj, MemFun memFun, P1 p1, P2 p2)
template<typename Ret , class Obj1 , class Obj2 , typename P1a , typename P1b , typename P2a , typename P2b >
ObjScopeGuardImpl2< Obj1, Ret(Obj2::*)(P1a, P2a), P1b, P2b > MakeGuard (Ret(Obj2::*memFun)(P1a, P2a), Obj1 &obj, P1b p1, P2b p2)
template<typename Ret , class Obj1 , class Obj2 , typename P1a , typename P1b , typename P2a , typename P2b >
ObjScopeGuardImpl2< Obj1, Ret(Obj2::*)(P1a, P2a), P1b, P2b > MakeGuard (Ret(Obj2::*memFun)(P1a, P2a), Obj1 *obj, P1b p1, P2b p2)
template<typename T , typename StrictWeakOrdering >
void shellSort (T *v, size_t n, StrictWeakOrdering comp)
Sort a given vector in place using a modified Shell Sort algorithm O(n^(3/2))
template<typename T >
void shellSort (T *v, size_t n)
Syntactic sugar for using operator< as default comparison operator.
template<typename T , typename StrictWeakOrdering >
void shellSort (T &v, StrictWeakOrdering comp)
Syntactic sugar for std::vectors.
template<typename T >
void shellSort (T &v)
Syntactic sugar for std::vectors and operator< as comparison operator.
template<typename T , typename P , typename StrictWeakOrdering >
void permShellSort (const T *v, P *perm, size_t n, StrictWeakOrdering comp, bool inputPerm=false)
Sort a given vector using a modified Shell Sort algorithm O(n^(3/2))
template<typename T , typename P >
void permute (T *v, const P *perm, size_t n)
Permute the elements of a vector according to a given permutation.
template<typename InputIterator >
void xmlEscape (InputIterator first, InputIterator end, std::ostream &out)
template<typename BidirectionalIter >
void printList (std::ostream &out, BidirectionalIter first, BidirectionalIter last, std::streamsize precision=15, bool nl=false)
template<typename BidirectionalIter >
std::string list2str (BidirectionalIter first, BidirectionalIter last, std::streamsize precision=15)
template<typename BidirectionalIter >
void printMap (std::ostream &out, BidirectionalIter first, BidirectionalIter last, std::streamsize precision=15, bool nl=false)
XMLConfig & gConfig ()
Variables
static const bool PRESOLVE_DEF = false
static const double TIME_LIMIT_DEF = 10000.0
static const double LINEAR_EPS_DEF = 1e-6
static const int NUM_THREADS_DEF = 0
int status
char errmsg [BUF_SIZE]
const unsigned int BUF_SIZE = 4096
static const double bigRange = 1e4
static const double MIN_VIOLATION_DEF = 0.001
static const double MAX_SUPPORT_DEF = 1.0
static const double MAX_DYNAMISM_DEF = 1E+10
static const int MAX_RANK_DEF = 1000
static const bool FORCE_REFACTOR_DEF = true
static const int MAX_GMI_DEF = 200
static const bool ONLY_VIOLATED_DEF = false
static const double ONLY_VIOL_BAD_DEF = 0.20
static const double DEF_TIME_LIMIT = 7200.0
static const int DEF_S1_ITER_LIMIT = 10000
static const int DEF_ITER_LIMIT = 2000
static const int DEF_S1_MAX_MISSED_DECREASE = 30
static const int DEF_MAX_MISSED_DECREASE = 50
static const int DEF_MAX_RESTARTS = 100
static const int DEF_AVG_FLIPS = 20
static const double DEF_INTEGRALITY_EPS = 1e-6
static const uint64_t DEF_SEED = 120507
static const double DEF_SIGMA_THR = 0.02
static const bool DEF_PERTURBE_FROM_TRANSFORMER_OUTPUT = true
static const double DEF_ALPHA = 0.0
static const double DEF_ALPHA_FACTOR = 0.9
static const double DEF_ALPHA_DIST = 0.005
static const bool DEF_DO_STAGE_3 = true
static const char DEF_FIRST_OPT_METHOD = 'S'
static const int DEF_OPT_ITER_LIMIT = -1
static const char DEF_REOPT_METHOD = 'S'
static const int DEF_REOPT_ITER_LIMIT = -1
static const bool DEF_LOG_PERTURBATION = false
static const bool DEF_LOG_DETAILS = false
static const bool DEF_LOG_ITERATION = false
static const bool DEF_LOG_TIME = false
static const bool DEF_LOG_LP = false
static const int EXTENDED_PRECISION = 4
static const double GEOM_FACTOR = 0.85
static const double BIGM = 1e9
static const double BIGBIGM = 1e15
int UserBreak = 0
static const char to_table []
static const char from_table []
static const int MAX_SEPARATED_DEF = 100
static const double MIN_EFFICACY_DEF = 0.0001
static const double MIN_ORTHO_DEF = 0.1
static const double MAX_MEMORY_DEF = 1E+9
static const int MAX_SIZE_DEF = 1000000
const double defaultEPS = 1e-6
static const double simpledens [] = {1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 25.0, -1.0}
Typedef Documentation
AttributeMap
typedef std::map<std::string, std::string> dominiqs::AttributeMap
Definition at line 23 of file myxml.h.
BranchCbPtr
typedef int(CPXPUBLIC* dominiqs::BranchCbPtr) (CALLBACK_BRANCH_ARGS)
Definition at line 447 of file cpxutils.cpp.
CategoryPtr
typedef boost::shared_ptr<Category> dominiqs::CategoryPtr
Definition at line 49 of file ini_spirit.h.
CEnv
typedef CPXCENVptr dominiqs::CEnv
Definition at line 33 of file cpxutils.h.
char_t
typedef char dominiqs::char_t
Definition at line 26 of file ini_spirit.cpp.
ConstraintPtr
typedef boost::intrusive_ptr<Constraint> dominiqs::ConstraintPtr
Definition at line 152 of file maths.h.
CProb
typedef CPXCLPptr dominiqs::CProb
Definition at line 35 of file cpxutils.h.
CutList
typedef std::vector<CutPtr> dominiqs::CutList
A list of cuts
Definition at line 106 of file cutpool.h.
CutPtr
typedef boost::intrusive_ptr<Cut> dominiqs::CutPtr
Definition at line 81 of file cutpool.h.
EntryList
typedef std::list<Entry> dominiqs::EntryList
Definition at line 29 of file ini_spirit.h.
Env
typedef CPXENVptr dominiqs::Env
typedefs of basic Callable Library entities, i.e. environment (Env) and problem pointers (Prob).
Definition at line 32 of file cpxutils.h.
FloatVectorPtr
typedef boost::shared_ptr< std::vector<double> > dominiqs::FloatVectorPtr
Definition at line 108 of file maths.h.
IniFilePtr
typedef boost::shared_ptr<IniFile> dominiqs::IniFilePtr
Definition at line 74 of file ini_spirit.h.
IntegerVectorPtr
typedef boost::shared_ptr< std::vector<int> > dominiqs::IntegerVectorPtr
Definition at line 106 of file maths.h.
iterator_t
typedef file_iterator<char_t> dominiqs::iterator_t
Definition at line 27 of file ini_spirit.cpp.
LoggerPtr
typedef boost::shared_ptr<Logger> dominiqs::LoggerPtr
Definition at line 102 of file logger.h.
Prob
typedef CPXLPptr dominiqs::Prob
Definition at line 34 of file cpxutils.h.
rule_t
typedef rule<scanner_t> dominiqs::rule_t
Definition at line 29 of file ini_spirit.cpp.
scanner_t
typedef scanner<iterator_t> dominiqs::scanner_t
Definition at line 28 of file ini_spirit.cpp.
ScopeGuard
typedef const ScopeGuardImplBase& dominiqs::ScopeGuard
Definition at line 82 of file scopeguard.h.
ShortcutMap
typedef std::map<std::string, std::string> dominiqs::ShortcutMap
Reads all config INI files (from left to right) specified in the command line and merge into a single one. Then it overrides some config values according to the command line It optionally uses a string shortcut map while doing command line overrides
Definition at line 43 of file args_parser.h.
SolutionTransformerPtr
typedef boost::shared_ptr<SolutionTransformer> dominiqs::SolutionTransformerPtr
Definition at line 50 of file fp_interface.h.
SparseVectorPtr
typedef boost::shared_ptr<SparseVector> dominiqs::SparseVectorPtr
Definition at line 104 of file maths.h.
TransformersFactory
typedef SingletonHolder< Factory<SolutionTransformer, std::string> > dominiqs::TransformersFactory
Definition at line 52 of file fp_interface.h.
VarPtr
typedef boost::shared_ptr<Var> dominiqs::VarPtr
Definition at line 171 of file cpxutils.h.
XMLCategoryPtr
typedef boost::shared_ptr<XMLCategory> dominiqs::XMLCategoryPtr
Definition at line 35 of file xmlconfig.h.
Enumeration Type Documentation
ParserStatus
enum dominiqs::ParserStatus
Enumerator
DEFAULT
CONFIG
OVERRIDE
OUTPUT
Definition at line 43 of file args_parser.cpp.
Function Documentation
accumulate() [1/3]
void dominiqs::accumulate (double * v, const double * w, int n, double lambda = 1.0)
Performe the operation: v <- v + lambda w where both v and w are dense vectors and lambda is a scalar
Definition at line 136 of file maths.cpp.
Referenced by accumulate(), dominiqs::GomorySeparator::backSubstitute(), dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
accumulate() [2/3]
void dominiqs::accumulate (double * v, const int * wIdx, const double * wCoef, int n, double lambda = 1.0)
Performe the operation: v <- v + lambda w where v is a dense vector, w is sparse and lambda is a scalar
Definition at line 142 of file maths.cpp.
accumulate() [3/3]
void dominiqs::accumulate (double * v, const SparseVector & w, double lambda = 1.0) inline
Definition at line 184 of file maths.h.
References accumulate(), dominiqs::SparseVector::coef(), dominiqs::SparseVector::idx(), and dominiqs::SparseVector::size().
addCut() [1/2]
void dominiqs::addCut (CEnv env, Prob lp, const std::string & name, const int * idx, const double * val, int cnt, char sense, double rhs)
Add A Single Cut (Row)
Definition at line 86 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
Referenced by dominiqs::Model::addCut(), dominiqs::FeasibilityPump::stage2(), and dominiqs::FeasibilityPump::stage3().
addCut() [2/2]
void dominiqs::addCut (CEnv env, Prob lp, const std::string & name, const SparseVector & row, char sense, double rhs)
Definition at line 93 of file cpxutils.cpp.
References dominiqs::SparseVector::coef(), dominiqs::SparseVector::idx(), and dominiqs::SparseVector::size().
Referenced by dominiqs::ProbInfo::write().
addEmptyVar()
void dominiqs::addEmptyVar (CEnv env, Prob lp, const std::string & name, char ctype, double lb, double ub, double obj)
Add A Single Var (Column)
Definition at line 105 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
Referenced by dominiqs::Model::addVar(), and dominiqs::ProbInfo::write().
addMIPStart()
void dominiqs::addMIPStart (CEnv env, Prob lp, const double * sol, int cnt)
Add A Single Cut (Row)
Definition at line 215 of file cpxutils.cpp.
References CHECKED_CPX_CALL, and iota().
addUserCut()
void dominiqs::addUserCut (CEnv env, Prob lp, const std::string & name, const SparseVector & row, char sense, double rhs)
Definition at line 98 of file cpxutils.cpp.
References CHECKED_CPX_CALL, dominiqs::SparseVector::coef(), dominiqs::SparseVector::idx(), and dominiqs::SparseVector::size().
addVar() [1/2]
void dominiqs::addVar (CEnv env, Prob lp, const std::string & name, const int * idx, const double * val, int cnt, char ctype, double lb, double ub, double obj)
Definition at line 111 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
addVar() [2/2]
void dominiqs::addVar (CEnv env, Prob lp, const std::string & name, const SparseVector & col, char ctype, double lb, double ub, double obj)
Definition at line 127 of file cpxutils.cpp.
References dominiqs::SparseVector::coef(), dominiqs::SparseVector::idx(), and dominiqs::SparseVector::size().
b64_decode() [1/3]
template<class T > ptrdiff_t dominiqs::b64_decode (const std::string & in, T & out)
Definition at line 57 of file base64.h.
References b64_decode().
b64_decode() [2/3]
ptrdiff_t dominiqs::b64_decode (const uint8_t * begin, const uint8_t * end, uint8_t * out, size_t out_size)
Decode a binary range [begin, end) into buffer out of size out_size
Returns
the number of bytes written (if successful) If out_size is to small return -need_size There cannot be bad characters in the stream (e.g. newlines, spaces, etc...): no checks!
Definition at line 110 of file base64.cpp.
References from_table.
Referenced by b64_decode(), and getBase64Content().
b64_decode() [3/3]
ptrdiff_t dominiqs::b64_decode (const std::string & in, uint8_t * out, size_t out_size)
Convenience functions accepting std::string for input and custom types in output (beware: use only PODs)
Definition at line 163 of file base64.cpp.
References b64_decode().
b64_encode() [1/3]
template<class T > void dominiqs::b64_encode (const T & obj, std::string & out)
Definition at line 34 of file base64.h.
References b64_encode().
b64_encode() [2/3]
ptrdiff_t dominiqs::b64_encode (const uint8_t * begin, const uint8_t * end, uint8_t * out, size_t out_size)
Encode a binary range [begin, end) into a buffer out of size out_size
Returns
the number of characters written (if successful) If out_size is to small return -need_size
Definition at line 51 of file base64.cpp.
References to_table.
Referenced by b64_encode(), and dominiqs::Serializer::serialize().
b64_encode() [3/3]
void dominiqs::b64_encode (const uint8_t * begin, const uint8_t * end, std::string & out)
Convenience functions accepting std::string for output and custom types in input (beware: use only PODs)
Definition at line 103 of file base64.cpp.
References b64_encode().
branchCB()
static int dominiqs::branchCB (CALLBACK_BRANCH_ARGS) static
Definition at line 449 of file cpxutils.cpp.
References dominiqs::CpxPresolver::addedCuts, dominiqs::CpxPresolver::afterRootLp, CHECKED_CPX_CALL, CLONE_PROB, DOMINIQS_ASSERT, dotProduct(), dominiqs::CpxPresolver::incumbent, dominiqs::CpxPresolver::incumbentValue, and dominiqs::CpxPresolver::presolvedLp.
Referenced by dominiqs::CpxPresolver::exec().
ByRef()
template<class T > RefHolder<T> dominiqs::ByRef (T & t) inline
Use this method to pass objects by reference to a ScopeGuard
Definition at line 40 of file scopeguard.h.
ceilEps()
double dominiqs::ceilEps (double x, double eps = defaultEPS) inline
Definition at line 83 of file floats.h.
Referenced by CardinalityProp::CardinalityProp(), VarLowerBoundProp::propagate(), LinearProp::propagate(), and KnapsackProp::propagate().
choose()
template<typename IntType > double dominiqs::choose (IntType m, IntType n)
Calculate the binomial coefficient (n choose m)
Returns
the binomial coefficient
Definition at line 96 of file numbers.h.
cpxBB()
void dominiqs::cpxBB (Env env, Prob lp, double objOffset, dominiqs::CutPool & pool, std::vector< double > & x, BBLimits & limits)
Definition at line 47 of file cpxbb.cpp.
References dominiqs::CutPool::begin(), CHECKED_CPX_CALL, DOMINIQS_ASSERT, dominiqs::BBLimits::enableCuts, dominiqs::BBLimits::enablePresolve, dominiqs::CutPool::end(), dominiqs::Logger::endSection(), gLog(), infoCB(), iota(), dominiqs::Logger::logItem(), dominiqs::BBLimits::memLimit, dominiqs::BBLimits::nodeLimit, dominiqs::CutPool::size(), dominiqs::Logger::startSection(), and dominiqs::BBLimits::timeLimit.
Creator()
template<typename BaseClassType , typename ClassType , typename... Args> BaseClassType* dominiqs::Creator (Args... args)
Definition at line 17 of file factory.h.
Referenced by dominiqs::Factory< BaseClassType, UniqueIdType, Args >::registerClass().
delCut() [1/2]
void dominiqs::delCut (CEnv env, Prob lp, const std::string & row_name)
Delete a Single Constraint (Row)
Definition at line 198 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
delCut() [2/2]
void dominiqs::delCut (CEnv env, Prob lp, int row_idx)
Definition at line 205 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
delVar() [1/2]
void dominiqs::delVar (CEnv env, Prob lp, const std::string & col_name)
Delete a Single Var (Column)
delVar() [2/2]
void dominiqs::delVar (CEnv env, Prob lp, int col_idx)
Definition at line 210 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
different()
bool dominiqs::different (double x, double y, double eps = defaultEPS) inline
Definition at line 31 of file floats.h.
Referenced by CardinalityFactory::analyze(), areSolutionsEqual(), dominiqs::OptimalFaceFixer::exec(), SimpleRounding::init(), dominiqs::SparseVector::operator==(), dominiqs::Model::reducedCostFixing(), and dominiqs::FeasibilityPump::restart().
disjoint()
bool dominiqs::disjoint (const double * a1, const double * a2, int n)
Checks if two dense vectors have disjoint support
Definition at line 229 of file maths.cpp.
References isPositive().
dotProduct() [1/3]
double dominiqs::dotProduct (const double * a1, const double * a2, int n)
Dot Product between dense vectors (manual loop unrolling)
Definition at line 154 of file maths.cpp.
Referenced by branchCB(), dominiqs::GomorySeparator::calculateTableauRow(), dotProduct(), dominiqs::FeasibilityPump::init(), main(), dominiqs::FeasibilityPump::pump(), dominiqs::CutPool::select(), dominiqs::GomorySeparator::setX(), dominiqs::FeasibilityPump::solveInitialLP(), dominiqs::FeasibilityPump::stage1(), dominiqs::FeasibilityPump::stage2(), dominiqs::OptimalFaceFixer::undo(), and dominiqs::Constraint::violation().
dotProduct() [2/3]
double dominiqs::dotProduct (const int * idx1, const double * a1, int n, const double * a2)
Dot Product between a sparse and a dense vector
Definition at line 198 of file maths.cpp.
dotProduct() [3/3]
double dominiqs::dotProduct (const SparseVector & a1, const double * a2) inline
Definition at line 207 of file maths.h.
References dominiqs::SparseVector::coef(), dotProduct(), dominiqs::SparseVector::idx(), and dominiqs::SparseVector::size().
double2int()
template<class int_type > int_type dominiqs::double2int (double x) inline
Definition at line 108 of file floats.h.
References isNull().
dynamic_pointer_cast()
template<class T , class U > intrusive_weak_ptr<T> dominiqs::dynamic_pointer_cast (const intrusive_weak_ptr< U > & p)
Definition at line 157 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::get().
equal()
bool dominiqs::equal (double x, double y, double eps = defaultEPS) inline
Definition at line 19 of file floats.h.
Referenced by dominiqs::Model::addVar(), LogicFactory::analyze(), CardinalityProp::CardinalityProp(), LexLessEqualProp::decreaseBeta(), dominiqs::Model::extract(), Domain::fixBinDown(), Domain::fixBinUp(), dominiqs::FeasibilityPump::init(), LexLessEqualProp::LexLessEqualProp(), dominiqs::cutptr_equal::operator()(), dominiqs::FeasibilityPump::perturbe(), Domain::pushVar(), dominiqs::FeasibilityPump::restart(), dominiqs::FeasibilityPump::stage1(), dominiqs::FeasibilityPump::stage2(), dominiqs::FeasibilityPump::stage3(), LexLessEqualProp::updateState(), and EquivProp::updateState().
euclidianDistance()
double dominiqs::euclidianDistance (const double * a1, const double * a2, int n)
Euclidian distance between two dense vectors
Definition at line 256 of file maths.cpp.
euclidianNorm()
double dominiqs::euclidianNorm (const double * v, int n)
Euclidian norm on a dense vector
Definition at line 248 of file maths.cpp.
Referenced by dominiqs::Cut::digest().
findFrac()
bool dominiqs::findFrac (double lb, double ub, int maxden, int & n, int & d)
Find a fraction n/d in the (very small) range [lb, ub] auch that d <= maxden
Returns
true if successful, false otherwise
Definition at line 96 of file numbers.cpp.
References float2frac().
float2frac()
bool dominiqs::float2frac (double r, double mindelta, double maxdelta, int maxden, int & n, int & d)
Compute the best approximating fraction n/d to the value r such that mindelta <= r - n/d <= maxdelta and d <= maxden
Returns
true in case of success, false otherwise
Definition at line 29 of file numbers.cpp.
References min.
Referenced by findFrac().
float2simplefrac()
bool dominiqs::float2simplefrac (double r, double mindelta, double maxdelta, int maxden, int & n, int & d)
Compute a simple fraction n/d approximating the value r such that mindelta <= r - n/d <= maxdelta and d <= maxden
Returns
true in case of success, false otherwise
Definition at line 67 of file numbers.cpp.
References gcd(), and simpledens.
floorEps()
double dominiqs::floorEps (double x, double eps = defaultEPS) inline
Definition at line 76 of file floats.h.
Referenced by CardinalityProp::CardinalityProp(), fractionalPart(), LinearProp::propagate(), VarUpperBoundProp::propagate(), and KnapsackProp::propagate().
fractionalPart()
double dominiqs::fractionalPart (double x, double eps = defaultEPS) inline
Definition at line 90 of file floats.h.
References floorEps(), and max.
Referenced by dominiqs::GomorySeparator::applyGMI(), dominiqs::GomorySeparator::calculateTableauRow(), GMIcoef(), integralityViolation(), and isInteger().
freeSSE2()
void dominiqs::freeSSE2 (void * ptr) inline
Free a 16-aligned memmory block allocated by mallocSSE2
Definition at line 51 of file machine_utils.h.
Referenced by dominiqs::SparseVector::reserve(), dominiqs::SparseVector::resize(), dominiqs::numarray< bool >::resize(), dominiqs::numarray< bool >::~numarray(), dominiqs::scoped_ptr_sse2< T >::~scoped_ptr_sse2(), and dominiqs::SparseVector::~SparseVector().
gcd()
template<typename IntType > IntType dominiqs::gcd (IntType n, IntType m)
calculate the greatest common divisor of two integral types n and m
Definition at line 29 of file numbers.h.
References DOMINIQS_ASSERT, and min.
Referenced by float2simplefrac().
gChrono()
Chrono & dominiqs::gChrono ()
Global Stopwatch
Definition at line 52 of file chrono.cpp.
Referenced by dominiqs::GlobalAutoChrono::GlobalAutoChrono(), main(), dominiqs::FeasibilityPump::reset(), and dominiqs::GlobalAutoChrono::stop().
gConfig()
XMLConfig & dominiqs::gConfig ()
Global Config File
Definition at line 111 of file xmlconfig.cpp.
Referenced by main(), dominiqs::App::parseArgsAndConfig(), dominiqs::FeasibilityPump::readConfig(), dominiqs::CPXApp::readConfig(), SimpleRounding::readConfig(), PropagatorRounding::readConfig(), FractionalityRanker::readConfig(), RandomRanker::readConfig(), and dominiqs::App::run().
gConfig2()
IniFile & dominiqs::gConfig2 ()
Global Config File
Definition at line 262 of file ini_spirit.cpp.
generateSeed()
uint64_t dominiqs::generateSeed (uint64_t seed) inline
Generate a seed for the generator based on user input If user input is not null, use it as seed Otherwise use current timestamp
Definition at line 26 of file randgen.h.
Referenced by main(), and dominiqs::UnitRandGen::setSeed().
geomMean()
template<typename ForwardIterator > double dominiqs::geomMean (ForwardIterator first, ForwardIterator last)
Return the geometric mean of a list of postive numbers
Definition at line 321 of file maths.h.
getAvailableMemory()
double dominiqs::getAvailableMemory () inline
Return the amount of available memory of the system in bytes
Definition at line 118 of file machine_utils.h.
getBase64Content()
template<class T > T dominiqs::getBase64Content (const XmlNode & node, const T & defValue)
Read data content of node
Parameters
node and convert it to an element of type
Template Parameters
T The text data of the node is interpreted as a base64 encoding of binary data representation of an object of type T
Returns
the converted value or
Parameters
defValue if node is empty or conversion fails
Definition at line 107 of file myxml.h.
References b64_decode(), dominiqs::XmlNode::data(), and dominiqs::XmlNode::isNull().
getColSupportLength()
int dominiqs::getColSupportLength (CEnv env, CProb lp, int col_idx)
Definition at line 78 of file cpxutils.cpp.
getConstrNames()
void dominiqs::getConstrNames (CEnv env, CProb lp, std::vector< std::string > & names, int begin = 0, int end = -1)
Get constraints names as a vector of strings
Definition at line 46 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
Referenced by dominiqs::Model::extract(), and dominiqs::ProbInfo::read().
getCut() [1/2]
void dominiqs::getCut (CEnv env, CProb lp, int row_idx, SparseVector & row, char & sense, double & rhs)
Get a Single Constraint (Row) Available in two version: get row by idx and by name
Definition at line 132 of file cpxutils.cpp.
References CHECKED_CPX_CALL, dominiqs::SparseVector::clear(), dominiqs::SparseVector::coef(), dominiqs::SparseVector::idx(), and dominiqs::SparseVector::resize().
getCut() [2/2]
void dominiqs::getCut (CEnv env, CProb lp, const std::string & row_name, SparseVector & row, char & sense, double & rhs)
Definition at line 156 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
getCwd()
std::string dominiqs::getCwd ()
Get The Current Working Directory Convenience wrapper around getcwd.
Definition at line 29 of file path.cpp.
Referenced by dominiqs::Path::getAbsolutePath().
getLoadAvg()
double dominiqs::getLoadAvg () inline
Get Average Load of the system
Definition at line 21 of file rusage.h.
getMachineEps()
double dominiqs::getMachineEps ()
returns the smallest number eps > 0, for which 1.0 + eps > 1.0 on the current machine
Definition at line 15 of file numbers.cpp.
getNumLogicalCores()
int dominiqs::getNumLogicalCores () inline
Return the number of logical cores in the system
Definition at line 157 of file machine_utils.h.
getNumPhysicalCores()
int dominiqs::getNumPhysicalCores () inline
Return the number of physical cores in the system This number may be the same as the number of logical cores, depending on hyper-threading. The returned number is accured on Mac platforms (less so on Linux, where we resort to sysconf)
Definition at line 141 of file machine_utils.h.
getPhysicalMemory()
double dominiqs::getPhysicalMemory () inline
Return the amount of physical memory of the system in bytes
Definition at line 99 of file machine_utils.h.
getProbName() [1/2]
std::string dominiqs::getProbName (const std::string & fileName, const std::vector< std::string > & exts)
Get the problem name from a LP/MPS file.
Definition at line 186 of file path.cpp.
References dominiqs::Path::getBasename().
Referenced by getProbName(), dominiqs::CPXApp::readConfig(), and dominiqs::App::run().
getProbName() [2/2]
std::string dominiqs::getProbName (const std::string & fileName)
Definition at line 193 of file path.cpp.
References getProbName().
getRowSupportLength()
int dominiqs::getRowSupportLength (CEnv env, CProb lp, int row_idx)
Get Row/Col Support Length (# of coefficents != 0)
Definition at line 70 of file cpxutils.cpp.
getTextContent()
template<class T > T dominiqs::getTextContent (const XmlNode & node, const T & defValue)
Read data content of node
Parameters
node and convert it to an element of type
Template Parameters
T
Returns
the converted value or
Parameters
defValue if node is empty or conversion fails
Definition at line 91 of file myxml.h.
References dominiqs::XmlNode::data(), and dominiqs::XmlNode::isNull().
getVar() [1/2]
void dominiqs::getVar (CEnv env, CProb lp, int col_idx, SparseVector & col, char & type, double & lb, double & ub, double & obj)
Get a Single Variable (Column) Available in two version: get col by idx and by name
Definition at line 163 of file cpxutils.cpp.
References CHECKED_CPX_CALL, dominiqs::SparseVector::clear(), dominiqs::SparseVector::coef(), dominiqs::SparseVector::idx(), dominiqs::SparseVector::resize(), and status.
getVar() [2/2]
void dominiqs::getVar (CEnv env, CProb lp, const std::string & col_name, SparseVector & col, char & type, double & lb, double & ub, double & obj)
Definition at line 191 of file cpxutils.cpp.
References CHECKED_CPX_CALL.
Referenced by dominiqs::ProbInfo::read().
getVarNames()
void dominiqs::getVarNames (CEnv env, CProb lp, std::vector< std::string > & names, int begin = 0, int end = -1)
Get var names as a vector of strings
Definition at line 22 of file cpxutils.cpp.
References CHECKED_CPX_CALL, and DOMINIQS_ASSERT.
Referenced by dominiqs::Model::extract(), main(), and dominiqs::ProbInfo::read().
gLog()
Logger & dominiqs::gLog ()
Global Logger
Definition at line 90 of file logger.cpp.
Referenced by SimpleRounding::apply(), dominiqs::GlobalAutoSection::close(), cpxBB(), dominiqs::FeasibilityPump::foundIncumbent(), dominiqs::GlobalAutoSection::GlobalAutoSection(), infoCB(), dominiqs::FeasibilityPump::init(), dominiqs::GomorySeparator::logStats(), main(), dominiqs::FeasibilityPump::perturbe(), dominiqs::FeasibilityPump::pump(), dominiqs::GomorySeparator::readConfig(), dominiqs::FeasibilityPump::readConfig(), dominiqs::CutPool::readConfig(), dominiqs::FeasibilityPump::restart(), dominiqs::App::run(), dominiqs::FeasibilityPump::solveInitialLP(), dominiqs::FeasibilityPump::stage1(), dominiqs::FeasibilityPump::stage2(), and dominiqs::FeasibilityPump::stage3().
GMIcoef()
static double dominiqs::GMIcoef (double alpha, char type, double f0, double ratio, double eps) inline static
Definition at line 30 of file gomory.cpp.
References fractionalPart(), and isNegative().
Referenced by dominiqs::GomorySeparator::calculateTableauRow().
greaterEqualThan()
bool dominiqs::greaterEqualThan (double x, double y, double eps = defaultEPS) inline
Definition at line 51 of file floats.h.
Referenced by PropagatorRounding::apply(), LexLessEqualProp::propagate(), LinearProp::propagate(), LinearProp::updateState(), and KnapsackProp::updateState().
greaterThan()
bool dominiqs::greaterThan (double x, double y, double eps = defaultEPS) inline
Definition at line 41 of file floats.h.
Referenced by SimpleRounding::apply(), PositiveLinearAdvisor::fixedDown(), KnapsackAdvisor::fixedDown(), NegativeLinearAdvisor::fixedUp(), PropagatorRounding::init(), dominiqs::Model::isLinearFeasible(), lexComp(), LexLessEqualProp::LexLessEqualProp(), LinearProp::LinearProp(), dominiqs::FeasibilityPump::perturbe(), KnapsackProp::print(), LexLessEqualProp::propagate(), VarLowerBoundProp::propagate(), LinearProp::propagate(), KnapsackProp::propagate(), dominiqs::Model::reducedCostFixing(), dominiqs::GomorySeparator::setX(), PropagationEngine::tightenedLb(), Domain::tightenLb(), NegativeLinearAdvisor::tightenLb(), PositiveLinearAdvisor::tightenUb(), KnapsackAdvisor::tightenUb(), LexLessEqualProp::updateState(), LinearProp::updateState(), and KnapsackProp::updateState().
infoCB()
static int dominiqs::infoCB (CEnv env, void * cbdata, int wherefrom, void * cbhandle) static
Definition at line 18 of file cpxbb.cpp.
References CHECKED_CPX_CALL, dominiqs::GlobalAutoSection::close(), dominiqs::Logger::flush(), gLog(), and dominiqs::Logger::logItem().
Referenced by cpxBB().
integralityViolation()
double dominiqs::integralityViolation (double x, double eps = defaultEPS) inline
Definition at line 96 of file floats.h.
References fractionalPart(), and min.
Referenced by dominiqs::GomorySeparator::calculateTableauRow(), dominiqs::GomorySeparator::separateGMI(), and FractionalityRanker::setCurrentState().
intrusive_ptr_add_ref()
void dominiqs::intrusive_ptr_add_ref (ManagedObjectWeak * obj) inline
Definition at line 70 of file managed_object_weak.h.
References dominiqs::ManagedObjectWeak::ref_cnt.
intrusive_ptr_release()
void dominiqs::intrusive_ptr_release (ManagedObjectWeak * obj) inline
Definition at line 71 of file managed_object_weak.h.
References dominiqs::ManagedObjectWeak::ref_cnt.
intrusive_weak_ptr_get_head()
intrusive_weak_ptr_base * dominiqs::intrusive_weak_ptr_get_head (ManagedObjectWeak * obj) inline
Definition at line 72 of file managed_object_weak.h.
References dominiqs::ManagedObjectWeak::wptr_head.
Referenced by dominiqs::intrusive_weak_ptr< T >::insertIntoList().
intrusive_weak_ptr_set_head()
void dominiqs::intrusive_weak_ptr_set_head (ManagedObjectWeak * obj, intrusive_weak_ptr_base * ptr) inline
Definition at line 73 of file managed_object_weak.h.
References dominiqs::ManagedObjectWeak::wptr_head.
Referenced by dominiqs::intrusive_weak_ptr< T >::insertIntoList(), and dominiqs::intrusive_weak_ptr< T >::removeFromList().
iota()
template<typename ForwardIterator , typename T > void dominiqs::iota (ForwardIterator first, ForwardIterator last, T value)
Initialize the range [first,last) of elements with consecutive elements, starting from
Parameters
value iota is not part of the C++ standard (it is an GNU extension), hence this implementation
Template Parameters
ForwardIterator iterator type
T value type
Parameters
first first element of the range
last one past last element of the range
value starting value
Definition at line 165 of file maths.h.
Referenced by addMIPStart(), cpxBB(), dominiqs::OptimalFaceFixer::init(), dominiqs::numarray< bool >::iota(), permShellSort(), dominiqs::FeasibilityPump::pump(), RandomRanker::setCurrentState(), dominiqs::FeasibilityPump::stage1(), dominiqs::FeasibilityPump::stage2(), and dominiqs::FeasibilityPump::stage3().
isInteger()
bool dominiqs::isInteger (double x, double eps = defaultEPS) inline
Definition at line 102 of file floats.h.
References fractionalPart(), and isNull().
Referenced by dominiqs::GomorySeparator::applyGMI(), dominiqs::Model::calculateSlackType(), dominiqs::Model::isIntegerFeasible(), isSolutionInteger(), and solutionNumFractional().
isNegative()
bool dominiqs::isNegative (double x, double eps = defaultEPS) inline
Definition at line 56 of file floats.h.
Referenced by VarBoundFactory::analyze(), KnapsackFactory::analyze(), dominiqs::GomorySeparator::applyGMI(), VarLowerBoundPropAdvisor::fixedDown(), VarUpperBoundPropAdvisor::fixedUp(), GMIcoef(), dominiqs::Constraint::isSlack(), VarUpperBoundPropAdvisor::tightenLb(), and VarLowerBoundPropAdvisor::tightenUb().
isNotNull()
bool dominiqs::isNotNull (double x, double eps = defaultEPS) inline
Definition at line 71 of file floats.h.
Referenced by dominiqs::GomorySeparator::calculateTableauRow(), dominiqs::OptimalFaceFixer::exec(), dominiqs::SparseVector::gather(), main(), dominiqs::GomorySeparator::printRow(), dominiqs::GomorySeparator::separateOneGMI(), and FractionalityRanker::setCurrentState().
isNull()
bool dominiqs::isNull (double x, double eps = defaultEPS) inline
Definition at line 66 of file floats.h.
Referenced by dominiqs::Model::addVar(), LogicFactory::analyze(), dominiqs::GomorySeparator::applyGMI(), CardinalityProp::CardinalityProp(), double2int(), dominiqs::Model::extract(), ImpliesProp::ImpliesProp(), isInteger(), KnapsackProp::KnapsackProp(), LinearProp::LinearProp(), EquivProp::propagate(), PropagationEngine::propagate(), dominiqs::FeasibilityPump::pump(), dominiqs::FeasibilityPump::restart(), dominiqs::FeasibilityPump::stage1(), dominiqs::FeasibilityPump::stage2(), dominiqs::FeasibilityPump::stage3(), Domain::tightenLb(), Domain::tightenUb(), VarLowerBoundProp::VarLowerBoundProp(), and VarUpperBoundProp::VarUpperBoundProp().
isPositive()
bool dominiqs::isPositive (double x, double eps = defaultEPS) inline
Definition at line 61 of file floats.h.
Referenced by dominiqs::Model::computeLocks(), disjoint(), VarUpperBoundPropAdvisor::fixedDown(), VarLowerBoundPropAdvisor::fixedUp(), dominiqs::Constraint::satisfiedBy(), dominiqs::CutPool::select(), dominiqs::GomorySeparator::setX(), VarLowerBoundPropAdvisor::tightenLb(), and VarUpperBoundPropAdvisor::tightenUb().
lcm()
template<typename IntType > IntType dominiqs::lcm (IntType n, IntType m)
calculates the least common multiple of two integral types n and m
Definition at line 61 of file numbers.h.
lessEqualThan()
bool dominiqs::lessEqualThan (double x, double y, double eps = defaultEPS) inline
Definition at line 46 of file floats.h.
Referenced by PropagatorRounding::apply(), LexLessEqualProp::checkLex(), LexLessEqualProp::propagate(), LinearProp::propagate(), KnapsackProp::propagate(), LinearProp::updateState(), and KnapsackProp::updateState().
lessThan()
bool dominiqs::lessThan (double x, double y, double eps = defaultEPS) inline
Definition at line 36 of file floats.h.
Referenced by KnapsackFactory::analyze(), SimpleRounding::apply(), dominiqs::GomorySeparator::calculateTableauRow(), LexLessEqualProp::checkLex(), NegativeLinearAdvisor::fixedDown(), PositiveLinearAdvisor::fixedUp(), KnapsackAdvisor::fixedUp(), dominiqs::Model::isLinearFeasible(), lexComp(), LinearProp::LinearProp(), dominiqs::FeasibilityPump::perturbe(), KnapsackProp::print(), LexLessEqualProp::propagate(), LinearProp::propagate(), VarUpperBoundProp::propagate(), KnapsackProp::propagate(), dominiqs::GomorySeparator::setX(), dominiqs::FeasibilityPump::stage3(), PropagationEngine::tightenedUb(), PositiveLinearAdvisor::tightenLb(), KnapsackAdvisor::tightenLb(), Domain::tightenUb(), NegativeLinearAdvisor::tightenUb(), LinearProp::updateState(), and KnapsackProp::updateState().
lexComp()
int dominiqs::lexComp (const double * s1, const double * s2, int n)
Lexicographically compare two array of doubles
Parameters
s1 first array
s2 second array
n arrays size
Returns
comparison result {-1, 0, 1} if {<, =, >} respectively
Definition at line 264 of file maths.cpp.
References greaterThan(), and lessThan().
lexMin()
void dominiqs::lexMin (Env env, Prob lp, bool isMin, bool skipOrigObj, int * rank, int rankCnt)
Lex Opt
list2str()
template<typename BidirectionalIter > std::string dominiqs::list2str (BidirectionalIter first, BidirectionalIter last, std::streamsize precision = 15)
Convert range [first,last) of a container to a string with a Python-like syntax
Parameters
first beginnning of the range
last end of the range
precision precision for numeric values
Returns
string encoding of the range
Definition at line 119 of file str_utils.h.
References printList().
MakeEnforcer() [1/2]
template<class P , class R , typename T > Enforcer<const T&, P, R> dominiqs::MakeEnforcer (const T & t, const char * locus) inline
Definition at line 62 of file enforce.h.
MakeEnforcer() [2/2]
template<class P , class R , typename T > Enforcer<T&, P, R> dominiqs::MakeEnforcer (T & t, const char * locus) inline
Definition at line 69 of file enforce.h.
MakeGuard() [1/10]
template<typename F > ScopeGuardImpl0<F> dominiqs::MakeGuard (F fun) inline
Definition at line 110 of file scopeguard.h.
References dominiqs::ScopeGuardImpl0< F >::MakeGuard().
MakeGuard() [2/10]
template<typename F , typename P1 > ScopeGuardImpl1<F, P1> dominiqs::MakeGuard (F fun, P1 p1) inline
Definition at line 142 of file scopeguard.h.
References dominiqs::ScopeGuardImpl1< F, P1 >::MakeGuard().
MakeGuard() [3/10]
template<typename F , typename P1 , typename P2 > ScopeGuardImpl2<F, P1, P2> dominiqs::MakeGuard (F fun, P1 p1, P2 p2) inline
Definition at line 175 of file scopeguard.h.
References dominiqs::ScopeGuardImpl2< F, P1, P2 >::MakeGuard().
MakeGuard() [4/10]
template<typename F , typename P1 , typename P2 , typename P3 > ScopeGuardImpl3<F, P1, P2, P3> dominiqs::MakeGuard (F fun, P1 p1, P2 p2, P3 p3) inline
Definition at line 209 of file scopeguard.h.
References dominiqs::ScopeGuardImpl3< F, P1, P2, P3 >::MakeGuard().
MakeGuard() [5/10]
template<typename Ret , class Obj1 , class Obj2 > ObjScopeGuardImpl0<Obj1,Ret(Obj2::*)()> dominiqs::MakeGuard (Ret(Obj2::*)() memFun, Obj1 & obj) inline
Definition at line 248 of file scopeguard.h.
References MakeObjGuard().
MakeGuard() [6/10]
template<typename Ret , class Obj1 , class Obj2 > ObjScopeGuardImpl0<Obj1,Ret(Obj2::*)()> dominiqs::MakeGuard (Ret(Obj2::*)() memFun, Obj1 * obj) inline
Definition at line 254 of file scopeguard.h.
References MakeObjGuard().
MakeGuard() [7/10]
template<typename Ret , class Obj1 , class Obj2 , typename P1a , typename P1b > ObjScopeGuardImpl1<Obj1,Ret(Obj2::*)(P1a),P1b> dominiqs::MakeGuard (Ret(Obj2::*)(P1a) memFun, Obj1 & obj, P1b p1) inline
Definition at line 294 of file scopeguard.h.
References MakeObjGuard().
MakeGuard() [8/10]
template<typename Ret , class Obj1 , class Obj2 , typename P1a , typename P1b > ObjScopeGuardImpl1<Obj1,Ret(Obj2::*)(P1a),P1b> dominiqs::MakeGuard (Ret(Obj2::*)(P1a) memFun, Obj1 * obj, P1b p1) inline
Definition at line 300 of file scopeguard.h.
References MakeObjGuard().
MakeGuard() [9/10]
template<typename Ret , class Obj1 , class Obj2 , typename P1a , typename P1b , typename P2a , typename P2b > ObjScopeGuardImpl2<Obj1,Ret(Obj2::*)(P1a,P2a),P1b,P2b> dominiqs::MakeGuard (Ret(Obj2::*)(P1a, P2a) memFun, Obj1 & obj, P1b p1, P2b p2) inline
Definition at line 341 of file scopeguard.h.
References MakeObjGuard().
MakeGuard() [10/10]
template<typename Ret , class Obj1 , class Obj2 , typename P1a , typename P1b , typename P2a , typename P2b > ObjScopeGuardImpl2<Obj1,Ret(Obj2::*)(P1a,P2a),P1b,P2b> dominiqs::MakeGuard (Ret(Obj2::*)(P1a, P2a) memFun, Obj1 * obj, P1b p1, P2b p2) inline
Definition at line 347 of file scopeguard.h.
References MakeObjGuard().
MakeObjGuard() [1/3]
template<class Obj , typename MemFun > ObjScopeGuardImpl0<Obj, MemFun> dominiqs::MakeObjGuard (Obj & obj, MemFun memFun) inline
Definition at line 242 of file scopeguard.h.
References dominiqs::ObjScopeGuardImpl0< Obj, MemFun >::MakeObjGuard().
Referenced by MakeGuard().
MakeObjGuard() [2/3]
template<class Obj , typename MemFun , typename P1 > ObjScopeGuardImpl1<Obj, MemFun, P1> dominiqs::MakeObjGuard (Obj & obj, MemFun memFun, P1 p1) inline
Definition at line 288 of file scopeguard.h.
References dominiqs::ObjScopeGuardImpl1< Obj, MemFun, P1 >::MakeObjGuard().
MakeObjGuard() [3/3]
template<class Obj , typename MemFun , typename P1 , typename P2 > ObjScopeGuardImpl2<Obj, MemFun, P1, P2> dominiqs::MakeObjGuard (Obj & obj, MemFun memFun, P1 p1, P2 p2) inline
Definition at line 335 of file scopeguard.h.
References dominiqs::ObjScopeGuardImpl2< Obj, MemFun, P1, P2 >::MakeObjGuard().
mallocSSE2()
void* dominiqs::mallocSSE2 (std::size_t size) inline
Allocate
Parameters
size bytes of memory The returned block is guaranteed to be 16-aligned (to play nicely with SSE2)
Returns
a pointer to the allocated block
Definition at line 35 of file machine_utils.h.
References DOMINIQS_ASSERT.
Referenced by dominiqs::numarray< bool >::numarray(), dominiqs::SparseVector::reserve(), and dominiqs::SparseVector::SparseVector().
mean()
template<typename ForwardIterator > double dominiqs::mean (ForwardIterator first, ForwardIterator last)
Return the arithmetic mean of a list of postive numbers
Definition at line 351 of file maths.h.
Referenced by variance().
mergeConfig()
void dominiqs::mergeConfig (const ArgsParser & args, XMLConfig & config, const ShortcutMap & shortcuts)
Definition at line 78 of file args_parser.cpp.
References dominiqs::ArgsParser::config, DOMINIQS_ASSERT, dominiqs::XMLConfig::load(), dominiqs::ArgsParser::overrides, and dominiqs::XMLConfig::set().
Referenced by main(), and dominiqs::App::parseArgsAndConfig().
operator!=()
template<class T , class U > bool dominiqs::operator!= (const intrusive_weak_ptr< T > & a, const intrusive_weak_ptr< U > & b) inline
Definition at line 142 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::get().
operator<()
template<class T , class U > bool dominiqs::operator< (const intrusive_weak_ptr< T > & a, const intrusive_weak_ptr< U > & b) inline
Definition at line 147 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::get().
operator<<() [1/2]
template<class T > std::ostream& dominiqs::operator<< (std::ostream & out, const std::vector< T > & v)
Print vector of numbers
Definition at line 90 of file feaspump.cpp.
operator<<() [2/2]
std::ostream & dominiqs::operator<< (std::ostream & out, const Category & c)
Definition at line 114 of file ini_spirit.cpp.
References dominiqs::Category::begin(), dominiqs::Category::end(), and dominiqs::Category::name.
operator==()
template<class T , class U > bool dominiqs::operator== (const intrusive_weak_ptr< T > & a, const intrusive_weak_ptr< U > & b) inline
Definition at line 137 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::get().
permShellSort()
template<typename T , typename P , typename StrictWeakOrdering > void dominiqs::permShellSort (const T * v, P * perm, size_t n, StrictWeakOrdering comp, bool inputPerm = false)
Sort a given vector using a modified Shell Sort algorithm O(n^(3/2))
The algorithm does not rearrange the vector items, rather it computes the permutation that does the sorting
Template Parameters
T value type of vector
P value type of permutation vector
StrictWeakOrdering comparison operator
Parameters
v input vector (passed as C array)
perm permutation vector (passed as C array of the appropriate size!)
n vectors size (both input and permutation)
comp operator instance
inputPerm if true perm stores a starting permutation of v if false perm is initialized with the identity permutation [0, 1, ..., |v| - 1]
Definition at line 121 of file sorting.h.
References iota().
Referenced by dominiqs::GomorySeparator::separateGMI(), and FractionalityRanker::setCurrentState().
permute()
template<typename T , typename P > void dominiqs::permute (T * v, const P * perm, size_t n)
Permute the elements of a vector according to a given permutation.
Template Parameters
T value type of vector
P value type of permutation vector
Parameters
v input/output vector (passed as C array)
perm permutation vector (passed as C array of the appropriate size!)
n vectors size (both vector and permutation)
Definition at line 160 of file sorting.h.
printCut()
void dominiqs::printCut (std::ostream & out, const Model & m, const Cut & c)
Definition at line 46 of file gomory.cpp.
References dominiqs::SparseVector::coef(), dominiqs::SparseVector::idx(), dominiqs::Constraint::name, dominiqs::Constraint::rhs, dominiqs::Constraint::row, dominiqs::Constraint::sense, dominiqs::SparseVector::size(), and dominiqs::Model::xNames.
printList()
template<typename BidirectionalIter > void dominiqs::printList (std::ostream & out, BidirectionalIter first, BidirectionalIter last, std::streamsize precision = 15, bool nl = false)
Print range [first,last) of a container as a Python-like unnested list
Parameters
out output stream
first beginnning of the range
last end of the range
precision precision for numeric values
nl true to add a newline at the end, false (default) otherwise
Definition at line 82 of file str_utils.h.
Referenced by list2str().
printMap()
template<typename BidirectionalIter > void dominiqs::printMap (std::ostream & out, BidirectionalIter first, BidirectionalIter last, std::streamsize precision = 15, bool nl = false)
Print range [first,last) of an associative container as a Python-like map
Parameters
out output stream
first beginnning of the range
last end of the range
precision precision for numeric values
nl true to add a newline at the end, false (default) otherwise
Definition at line 137 of file str_utils.h.
relEqual()
bool dominiqs::relEqual (double x, double y, double eps = defaultEPS) inline
Definition at line 24 of file floats.h.
References max.
Referenced by main(), and dominiqs::OptimalFaceFixer::undo().
scale()
void dominiqs::scale (double * v, int n, double lambda = 1.0)
Scale a dense vector v multiplying it by lambda: v <- lambda v
Definition at line 148 of file maths.cpp.
Referenced by svd(), and uniform().
shellSort() [1/4]
template<typename T , typename StrictWeakOrdering > void dominiqs::shellSort (T * v, size_t n, StrictWeakOrdering comp)
Sort a given vector in place using a modified Shell Sort algorithm O(n^(3/2))
Template Parameters
T vector value type
StrictWeakOrdering comparison operator
Parameters
v input vector (passed as C array)
n vector size
comp operator instance
Definition at line 31 of file sorting.h.
Referenced by shellSort().
shellSort() [2/4]
template<typename T > void dominiqs::shellSort (T * v, size_t n)
Syntactic sugar for using operator< as default comparison operator.
Template Parameters
T vector type
Parameters
v input vector
Definition at line 67 of file sorting.h.
References shellSort().
shellSort() [3/4]
template<typename T , typename StrictWeakOrdering > void dominiqs::shellSort (T & v, StrictWeakOrdering comp)
Syntactic sugar for std::vectors.
Template Parameters
T vector type
StrictWeakOrdering comparison operator
Parameters
v input vector
comp operator instance
Definition at line 83 of file sorting.h.
References shellSort().
shellSort() [4/4]
template<typename T > void dominiqs::shellSort (T & v)
Syntactic sugar for std::vectors and operator< as comparison operator.
Template Parameters
T vector type
Parameters
v input vector
Definition at line 97 of file sorting.h.
References shellSort().
static_pointer_cast()
template<class T , class U > intrusive_weak_ptr<T> dominiqs::static_pointer_cast (const intrusive_weak_ptr< U > & p)
Definition at line 152 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::get().
userSignalBreak()
static void dominiqs::userSignalBreak (int signum) static
Definition at line 21 of file app.cpp.
References UserBreak.
Referenced by dominiqs::FeasibilityPump::pump(), and dominiqs::App::run().
variance()
template<typename ForwardIterator > double dominiqs::variance (ForwardIterator first, ForwardIterator last, bool fromSample = false)
Return the variance of a list of numbers The flag fromSample decides if the variance was from the entire population or a subset of observation, i.e. if fromSample is true the sum of squares is divided by n - 1, otherwise by n
Definition at line 275 of file maths.h.
References mean().
xmlEscape()
template<typename InputIterator > void dominiqs::xmlEscape (InputIterator first, InputIterator end, std::ostream & out)
Escape character data, replacing &<>"' with the corresponding XML entities
Definition at line 25 of file str_utils.h.
Referenced by dominiqs::Logger::logBinaryItem(), and dominiqs::Logger::logMsg().
Variable Documentation
BIGBIGM
const double dominiqs::BIGBIGM = 1e15 static
Definition at line 125 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::restart().
BIGM
const double dominiqs::BIGM = 1e9 static
Definition at line 124 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::restart().
bigRange
const double dominiqs::bigRange = 1e4 static
Definition at line 28 of file gomory.cpp.
Referenced by dominiqs::GomorySeparator::GomorySeparator().
BUF_SIZE
const unsigned int dominiqs::BUF_SIZE = 4096
Definition at line 24 of file cpxmacro.h.
DEF_ALPHA
const double dominiqs::DEF_ALPHA = 0.0 static
Definition at line 108 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_ALPHA_DIST
const double dominiqs::DEF_ALPHA_DIST = 0.005 static
Definition at line 110 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_ALPHA_FACTOR
const double dominiqs::DEF_ALPHA_FACTOR = 0.9 static
Definition at line 109 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_AVG_FLIPS
const int dominiqs::DEF_AVG_FLIPS = 20 static
Definition at line 103 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_DO_STAGE_3
const bool dominiqs::DEF_DO_STAGE_3 = true static
Definition at line 111 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_FIRST_OPT_METHOD
const char dominiqs::DEF_FIRST_OPT_METHOD = 'S' static
Definition at line 112 of file feaspump.cpp.
DEF_INTEGRALITY_EPS
const double dominiqs::DEF_INTEGRALITY_EPS = 1e-6 static
Definition at line 104 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_ITER_LIMIT
const int dominiqs::DEF_ITER_LIMIT = 2000 static
Definition at line 99 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_LOG_DETAILS
const bool dominiqs::DEF_LOG_DETAILS = false static
Definition at line 117 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_LOG_ITERATION
const bool dominiqs::DEF_LOG_ITERATION = false static
Definition at line 118 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_LOG_LP
const bool dominiqs::DEF_LOG_LP = false static
Definition at line 120 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_LOG_PERTURBATION
const bool dominiqs::DEF_LOG_PERTURBATION = false static
Definition at line 116 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_LOG_TIME
const bool dominiqs::DEF_LOG_TIME = false static
Definition at line 119 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_MAX_MISSED_DECREASE
const int dominiqs::DEF_MAX_MISSED_DECREASE = 50 static
Definition at line 101 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_MAX_RESTARTS
const int dominiqs::DEF_MAX_RESTARTS = 100 static
Definition at line 102 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_OPT_ITER_LIMIT
const int dominiqs::DEF_OPT_ITER_LIMIT = -1 static
Definition at line 113 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_PERTURBE_FROM_TRANSFORMER_OUTPUT
const bool dominiqs::DEF_PERTURBE_FROM_TRANSFORMER_OUTPUT = true static
Definition at line 107 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_REOPT_ITER_LIMIT
const int dominiqs::DEF_REOPT_ITER_LIMIT = -1 static
Definition at line 115 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_REOPT_METHOD
const char dominiqs::DEF_REOPT_METHOD = 'S' static
Definition at line 114 of file feaspump.cpp.
DEF_S1_ITER_LIMIT
const int dominiqs::DEF_S1_ITER_LIMIT = 10000 static
Definition at line 98 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_S1_MAX_MISSED_DECREASE
const int dominiqs::DEF_S1_MAX_MISSED_DECREASE = 30 static
Definition at line 100 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_SEED
const uint64_t dominiqs::DEF_SEED = 120507 static
Definition at line 105 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_SIGMA_THR
const double dominiqs::DEF_SIGMA_THR = 0.02 static
Definition at line 106 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
DEF_TIME_LIMIT
const double dominiqs::DEF_TIME_LIMIT = 7200.0 static
Definition at line 97 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::readConfig().
defaultEPS
const double dominiqs::defaultEPS = 1e-6
Definition at line 17 of file floats.h.
errmsg
char dominiqs::errmsg
Definition at line 17 of file cpxmacro.cpp.
EXTENDED_PRECISION
const int dominiqs::EXTENDED_PRECISION = 4 static
Definition at line 122 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::stage1(), and dominiqs::FeasibilityPump::stage2().
FORCE_REFACTOR_DEF
const bool dominiqs::FORCE_REFACTOR_DEF = true static
Definition at line 65 of file gomory.cpp.
Referenced by dominiqs::GomorySeparator::readConfig().
from_table
const char dominiqs::from_table[] static
Initial value:
=
{
                -1, -1, -1, -1, -1, -1, -1, -1,
                -1, -1, -1, -1, -1, -1, -1, -1,
                -1, -1, -1, -1, -1, -1, -1, -1,
                -1, -1, -1, -1, -1, -1, -1, -1,
                -1, -1, -1, -1, -1, -1, -1, -1,
                -1, -1, -1, 62, -1, -1, -1, 63,
                52, 53, 54, 55, 56, 57, 58, 59,
                60, 61, -1, -1, -1,  0, -1, -1,
                -1,  0,  1,  2,  3,  4,  5,  6,
                7,  8,  9, 10, 11, 12, 13, 14,
                15, 16, 17, 18, 19, 20, 21, 22,
                23, 24, 25, -1, -1, -1, -1, -1,
                -1, 26, 27, 28, 29, 30, 31, 32,
                33, 34, 35, 36, 37, 38, 39, 40,
                41, 42, 43, 44, 45, 46, 47, 48,
                49, 50, 51, -1, -1, -1, -1, -1
}
Definition at line 31 of file base64.cpp.
Referenced by b64_decode().
GEOM_FACTOR
const double dominiqs::GEOM_FACTOR = 0.85 static
Definition at line 123 of file feaspump.cpp.
Referenced by dominiqs::FeasibilityPump::restart().
LINEAR_EPS_DEF
const double dominiqs::LINEAR_EPS_DEF = 1e-6 static
Definition at line 18 of file cpxapp.cpp.
Referenced by dominiqs::CPXApp::readConfig().
MAX_DYNAMISM_DEF
const double dominiqs::MAX_DYNAMISM_DEF = 1E+10 static
Definition at line 63 of file gomory.cpp.
Referenced by dominiqs::GomorySeparator::readConfig().
MAX_GMI_DEF
const int dominiqs::MAX_GMI_DEF = 200 static
Definition at line 66 of file gomory.cpp.
Referenced by dominiqs::GomorySeparator::readConfig().
MAX_MEMORY_DEF
const double dominiqs::MAX_MEMORY_DEF = 1E+9 static
Definition at line 91 of file cutpool.cpp.
Referenced by dominiqs::CutPool::readConfig().
MAX_RANK_DEF
const int dominiqs::MAX_RANK_DEF = 1000 static
Definition at line 64 of file gomory.cpp.
Referenced by dominiqs::GomorySeparator::readConfig().
MAX_SEPARATED_DEF
const int dominiqs::MAX_SEPARATED_DEF = 100 static
Class CutPool
Definition at line 88 of file cutpool.cpp.
Referenced by dominiqs::CutPool::readConfig().
MAX_SIZE_DEF
const int dominiqs::MAX_SIZE_DEF = 1000000 static
Definition at line 92 of file cutpool.cpp.
Referenced by dominiqs::CutPool::readConfig().
MAX_SUPPORT_DEF
const double dominiqs::MAX_SUPPORT_DEF = 1.0 static
Definition at line 62 of file gomory.cpp.
Referenced by dominiqs::GomorySeparator::readConfig().
MIN_EFFICACY_DEF
const double dominiqs::MIN_EFFICACY_DEF = 0.0001 static
Definition at line 89 of file cutpool.cpp.
Referenced by dominiqs::CutPool::readConfig().
MIN_ORTHO_DEF
const double dominiqs::MIN_ORTHO_DEF = 0.1 static
Definition at line 90 of file cutpool.cpp.
Referenced by dominiqs::CutPool::readConfig().
MIN_VIOLATION_DEF
const double dominiqs::MIN_VIOLATION_DEF = 0.001 static
Definition at line 61 of file gomory.cpp.
Referenced by dominiqs::GomorySeparator::readConfig().
NUM_THREADS_DEF
const int dominiqs::NUM_THREADS_DEF = 0 static
Definition at line 19 of file cpxapp.cpp.
Referenced by dominiqs::CPXApp::readConfig().
ONLY_VIOL_BAD_DEF
const double dominiqs::ONLY_VIOL_BAD_DEF = 0.20 static
Definition at line 68 of file gomory.cpp.
Referenced by dominiqs::GomorySeparator::readConfig().
ONLY_VIOLATED_DEF
const bool dominiqs::ONLY_VIOLATED_DEF = false static
Definition at line 67 of file gomory.cpp.
Referenced by dominiqs::GomorySeparator::readConfig().
PRESOLVE_DEF
const bool dominiqs::PRESOLVE_DEF = false static
Definition at line 16 of file cpxapp.cpp.
Referenced by dominiqs::CPXApp::readConfig().
simpledens
const double dominiqs::simpledens[] = {1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 25.0, -1.0} static
Definition at line 65 of file numbers.cpp.
Referenced by float2simplefrac().
status
int dominiqs::status
Definition at line 15 of file cpxmacro.cpp.
Referenced by getVar(), and dominiqs::ArgsParser::parse().
TIME_LIMIT_DEF
const double dominiqs::TIME_LIMIT_DEF = 10000.0 static
Definition at line 17 of file cpxapp.cpp.
Referenced by dominiqs::CPXApp::readConfig().
to_table
const char dominiqs::to_table[] static
Initial value:
=
{
                'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
                'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
                'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
                'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
                'w', 'x', 'y', 'z', '0', '1', '2', '3',
                '4', '5', '6', '7', '8', '9', '+', '/'
}
Base64 Conversion Tables
Definition at line 19 of file base64.cpp.
Referenced by b64_encode().
UserBreak
int dominiqs::UserBreak = 0
Ctrl-C handling
Definition at line 19 of file app.cpp.
Referenced by dominiqs::App::run(), dominiqs::CPXApp::startup(), and userSignalBreak().