BRKGA for MIP feasibility: dominiqs::intrusive_weak_ptr_base Struct Reference
dominiqs::intrusive_weak_ptr_base Struct Reference abstract
#include <intrusive_weak_ptr.h>
Public Member Functions
intrusive_weak_ptr_base ()
virtual ~intrusive_weak_ptr_base ()
virtual void reset ()=0
void insertIntoList (intrusive_weak_ptr_base *head)
void removeFromList ()
Public Attributes
intrusive_weak_ptr_base * next
intrusive_weak_ptr_base * prev
Detailed Description
Base Class to handle weak pointers list
Definition at line 20 of file intrusive_weak_ptr.h.
Constructor & Destructor Documentation
intrusive_weak_ptr_base()
dominiqs::intrusive_weak_ptr_base::intrusive_weak_ptr_base () inline
Definition at line 23 of file intrusive_weak_ptr.h.
~intrusive_weak_ptr_base()
virtual dominiqs::intrusive_weak_ptr_base::~intrusive_weak_ptr_base () inline virtual
Definition at line 24 of file intrusive_weak_ptr.h.
Member Function Documentation
insertIntoList()
void dominiqs::intrusive_weak_ptr_base::insertIntoList (intrusive_weak_ptr_base * head) inline
Definition at line 28 of file intrusive_weak_ptr.h.
References next, and prev.
Referenced by dominiqs::intrusive_weak_ptr< T >::insertIntoList().
removeFromList()
void dominiqs::intrusive_weak_ptr_base::removeFromList () inline
Definition at line 34 of file intrusive_weak_ptr.h.
References next, and prev.
Referenced by dominiqs::intrusive_weak_ptr< T >::operator=(), dominiqs::intrusive_weak_ptr< T >::removeFromList(), and dominiqs::intrusive_weak_ptr< T >::~intrusive_weak_ptr().
reset()
virtual void dominiqs::intrusive_weak_ptr_base::reset () pure virtual
Implemented in dominiqs::intrusive_weak_ptr< T >.
Referenced by dominiqs::intrusive_weak_ptr< T >::release().
Member Data Documentation
next
intrusive_weak_ptr_base* dominiqs::intrusive_weak_ptr_base::next
Definition at line 25 of file intrusive_weak_ptr.h.
Referenced by insertIntoList(), dominiqs::intrusive_weak_ptr< T >::release(), removeFromList(), and dominiqs::intrusive_weak_ptr< T >::removeFromList().
prev
intrusive_weak_ptr_base* dominiqs::intrusive_weak_ptr_base::prev
Definition at line 26 of file intrusive_weak_ptr.h.
Referenced by insertIntoList(), removeFromList(), and dominiqs::intrusive_weak_ptr< T >::removeFromList().
The documentation for this struct was generated from the following file:
FP2/utils/intrusive_weak_ptr.h