BRKGA for MIP feasibility: test_fp2_propagator.cpp File Reference
test_fp2_propagator.cpp File Reference
#include <iostream>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <stdexcept>
#include <bitset>
#include <cstdlib>
#include "mtrand.hpp"
#include "pragma_diagnostic_ignored_header.hpp"
#include <boost/timer/timer.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/filesystem.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <ilcplex/ilocplex.h>
#include <ilcp/cp.h>
#include "cpxutils.h"
#include "fp_interface.h"
#include "transformers.h"
#include "logger.h"
#include "pragma_diagnostic_ignored_footer.hpp"
Functions
ILOSTLBEGIN int main (int argc, char *argv[])
Variables
const double EPS = 1e-6
Function Documentation
main()
ILOSTLBEGIN int main (int argc, char * argv[])
Definition at line 62 of file test_fp2_propagator.cpp.
References DOMINIQS_ASSERT, dominiqs::Model::extract(), dominiqs::SingletonHolder< T >::getInstance(), dominiqs::gLog(), dominiqs::Logger::open(), and MTRand::rand().
Variable Documentation
EPS
const double EPS = 1e-6
Definition at line 56 of file test_fp2_propagator.cpp.