BRKGA for MIP feasibility: KnapsackAdvisor Class Reference
KnapsackAdvisor Class Reference
Public Member Functions
KnapsackAdvisor (KnapsackProp *p, int j, double coef)
void fixedUp ()
void fixedDown ()
void tightenLb (double delta, bool decreaseInfCnt, bool propagate)
void tightenUb (double delta, bool decreaseInfCnt, bool propagate)
std::ostream & print (std::ostream &out) const
Public Member Functions inherited from AdvisorI
AdvisorI (Propagator *p, int j)
virtual ~AdvisorI ()
Propagator * getPropagator () const
int getVar () const
Protected Attributes
double a
Protected Attributes inherited from AdvisorI
Propagator * prop
int var
Additional Inherited Members
Protected Member Functions inherited from AdvisorI
template<class T >
T * getMyProp ()
Detailed Description
Definition at line 785 of file linear_propagator.cpp.
Constructor & Destructor Documentation
KnapsackAdvisor()
KnapsackAdvisor::KnapsackAdvisor (KnapsackProp * p, int j, double coef) inline
Definition at line 788 of file linear_propagator.cpp.
Member Function Documentation
fixedDown()
void KnapsackAdvisor::fixedDown () inline virtual
Reimplemented from AdvisorI.
Definition at line 797 of file linear_propagator.cpp.
References a, CSTATE_UNKNOWN, Propagator::dirty, Propagator::getState(), dominiqs::greaterThan(), INFBOUND, KnapsackProp::lhs, KnapsackProp::maxAct, and AdvisorI::prop.
fixedUp()
void KnapsackAdvisor::fixedUp () inline virtual
events for binary variables
Reimplemented from AdvisorI.
Definition at line 790 of file linear_propagator.cpp.
References a, CSTATE_UNKNOWN, Propagator::dirty, Propagator::getState(), INFBOUND, dominiqs::lessThan(), KnapsackProp::minAct, AdvisorI::prop, and KnapsackProp::rhs.
print()
std::ostream& KnapsackAdvisor::print (std::ostream & out) const inline virtual
Reimplemented from AdvisorI.
Definition at line 820 of file linear_propagator.cpp.
References a, Propagator::getName(), AdvisorI::prop, and AdvisorI::var.
tightenLb()
void KnapsackAdvisor::tightenLb (double delta, bool decreaseInfCnt, bool propagate) inline virtual
events for other (general integer and continuous) variables
Parameters
delta bound increase (if it was finite) or new value if tightening from infinite
decreaseInfCnt (this flag is true if the previous value for the bound was infinite)
propagate mask to trigger or not constraint propagation
Reimplemented from AdvisorI.
Definition at line 805 of file linear_propagator.cpp.
References a, CSTATE_UNKNOWN, Propagator::dirty, Propagator::getState(), INFBOUND, dominiqs::lessThan(), KnapsackProp::minAct, AdvisorI::prop, and KnapsackProp::rhs.
tightenUb()
void KnapsackAdvisor::tightenUb (double delta, bool decreaseInfCnt, bool propagate) inline virtual
Reimplemented from AdvisorI.
Definition at line 812 of file linear_propagator.cpp.
References a, CSTATE_UNKNOWN, Propagator::dirty, Propagator::getState(), dominiqs::greaterThan(), INFBOUND, KnapsackProp::lhs, KnapsackProp::maxAct, and AdvisorI::prop.
Member Data Documentation
a
double KnapsackAdvisor::a protected
Definition at line 825 of file linear_propagator.cpp.
Referenced by fixedDown(), fixedUp(), print(), tightenLb(), and tightenUb().
The documentation for this class was generated from the following file:
FP2/propagator/linear_propagator.cpp