BRKGA for MIP feasibility: dominiqs::Cut Class Reference
dominiqs::Cut Class Reference
#include <cutpool.h>
Public Member Functions
Cut ()
Cut (const Constraint &other, char sType)
Cut * clone () const
double score ()
double purgeScore ()
double dynamism () const
void digest ()
int memoryUsed () const
Public Member Functions inherited from dominiqs::Constraint
Constraint * clone () const
bool satisfiedBy (const double *x, double eps=defaultEPS) const
double violation (const double *x) const
bool isSlack (const double *x, double eps=defaultEPS) const
Public Attributes
char slackType
bool removable
bool inUse
uint8_t age
uint8_t separator
int rank
double efficacy
double ortho
std::size_t sig
double norm
Public Attributes inherited from dominiqs::Constraint
std::string name
SparseVector row
double rhs
char sense
Detailed Description
This represent a row (cut) in the constraint matrix Ax ~ b
Definition at line 29 of file cutpool.h.
Constructor & Destructor Documentation
Cut() [1/2]
dominiqs::Cut::Cut () inline
Definition at line 32 of file cutpool.h.
Referenced by clone(), and memoryUsed().
Cut() [2/2]
dominiqs::Cut::Cut (const Constraint & other, char sType) inline
Definition at line 34 of file cutpool.h.
Member Function Documentation
clone()
Cut * dominiqs::Cut::clone () const
Class Cut
Definition at line 21 of file cutpool.cpp.
References Cut().
digest()
void dominiqs::Cut::digest ()
Computes signatures and norm of the cut
Definition at line 39 of file cutpool.cpp.
References dominiqs::SparseVector::coef(), dominiqs::euclidianNorm(), dominiqs::SparseVector::idx(), norm, dominiqs::Constraint::row, sig, and dominiqs::SparseVector::size().
dynamism()
double dominiqs::Cut::dynamism () const
Computes the dynamism of the cut
Definition at line 26 of file cutpool.cpp.
References dominiqs::SparseVector::coef(), max, min, dominiqs::Constraint::row, and dominiqs::SparseVector::size().
memoryUsed()
int dominiqs::Cut::memoryUsed () const
Compute memory occupation of the cut
Definition at line 45 of file cutpool.cpp.
References dominiqs::SparseVector::capacity(), Cut(), and dominiqs::Constraint::row.
purgeScore()
double dominiqs::Cut::purgeScore () inline
Get the score of the cut for purging (function of efficacy and age) (the highest the score, the worst the cut!)
Definition at line 63 of file cutpool.h.
References age, efficacy, and inUse.
score()
double dominiqs::Cut::score () inline
Get the score of the cut (function of efficacy and ortho)
Definition at line 55 of file cutpool.h.
References efficacy, and ortho.
Member Data Documentation
age
uint8_t dominiqs::Cut::age
Definition at line 41 of file cutpool.h.
Referenced by purgeScore().
efficacy
double dominiqs::Cut::efficacy
Definition at line 44 of file cutpool.h.
Referenced by purgeScore(), and score().
inUse
bool dominiqs::Cut::inUse
Definition at line 40 of file cutpool.h.
Referenced by purgeScore().
norm
double dominiqs::Cut::norm
Definition at line 47 of file cutpool.h.
Referenced by digest().
ortho
double dominiqs::Cut::ortho
Definition at line 45 of file cutpool.h.
Referenced by score().
rank
int dominiqs::Cut::rank
Definition at line 43 of file cutpool.h.
removable
bool dominiqs::Cut::removable
Definition at line 39 of file cutpool.h.
separator
uint8_t dominiqs::Cut::separator
Definition at line 42 of file cutpool.h.
sig
std::size_t dominiqs::Cut::sig
Definition at line 46 of file cutpool.h.
Referenced by digest().
slackType
char dominiqs::Cut::slackType
Definition at line 38 of file cutpool.h.
The documentation for this class was generated from the following files:
FP2/utils/cutpool.h
FP2/utils/cutpool.cpp