BRKGA for MIP feasibility: VarUpperBoundPropAdvisor Class Reference
VarUpperBoundPropAdvisor Class Reference
Public Member Functions
VarUpperBoundPropAdvisor (VarUpperBoundProp *p, int j)
void fixedUp ()
void fixedDown ()
void tightenLb (double delta, bool decreaseInfCnt, bool propagate)
void tightenUb (double delta, bool decreaseInfCnt, bool propagate)
std::ostream & print (std::ostream &out) const
Public Member Functions inherited from AdvisorI
AdvisorI (Propagator *p, int j)
virtual ~AdvisorI ()
Propagator * getPropagator () const
int getVar () const
Additional Inherited Members
Protected Member Functions inherited from AdvisorI
template<class T >
T * getMyProp ()
Protected Attributes inherited from AdvisorI
Propagator * prop
int var
Detailed Description
Definition at line 134 of file varbound_propagator.cpp.
Constructor & Destructor Documentation
VarUpperBoundPropAdvisor()
VarUpperBoundPropAdvisor::VarUpperBoundPropAdvisor (VarUpperBoundProp * p, int j) inline
Definition at line 137 of file varbound_propagator.cpp.
Member Function Documentation
fixedDown()
void VarUpperBoundPropAdvisor::fixedDown () inline virtual
Reimplemented from AdvisorI.
Definition at line 147 of file varbound_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::getState(), dominiqs::isPositive(), min, VarUpperBoundProp::pendingUb, AdvisorI::prop, VarUpperBoundProp::ub, and VarUpperBoundProp::yCoef.
fixedUp()
void VarUpperBoundPropAdvisor::fixedUp () inline virtual
events for binary variables
Reimplemented from AdvisorI.
Definition at line 139 of file varbound_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::getState(), dominiqs::isNegative(), min, VarUpperBoundProp::pendingUb, AdvisorI::prop, VarUpperBoundProp::ub, and VarUpperBoundProp::yCoef.
print()
std::ostream& VarUpperBoundPropAdvisor::print (std::ostream & out) const inline virtual
Reimplemented from AdvisorI.
Definition at line 173 of file varbound_propagator.cpp.
References Propagator::getName(), and AdvisorI::prop.
tightenLb()
void VarUpperBoundPropAdvisor::tightenLb (double delta, bool decreaseInfCnt, bool propagate) inline virtual
events for other (general integer and continuous) variables
Parameters
delta bound increase (if it was finite) or new value if tightening from infinite
decreaseInfCnt (this flag is true if the previous value for the bound was infinite)
propagate mask to trigger or not constraint propagation
Reimplemented from AdvisorI.
Definition at line 156 of file varbound_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::domain, Propagator::getState(), dominiqs::isNegative(), min, VarUpperBoundProp::pendingUb, AdvisorI::prop, VarUpperBoundProp::ub, Domain::varLb(), VarUpperBoundProp::yCoef, and VarUpperBoundProp::yIdx.
tightenUb()
void VarUpperBoundPropAdvisor::tightenUb (double delta, bool decreaseInfCnt, bool propagate) inline virtual
Reimplemented from AdvisorI.
Definition at line 164 of file varbound_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, Propagator::domain, Propagator::getState(), dominiqs::isPositive(), min, VarUpperBoundProp::pendingUb, AdvisorI::prop, VarUpperBoundProp::ub, Domain::varUb(), VarUpperBoundProp::yCoef, and VarUpperBoundProp::yIdx.
The documentation for this class was generated from the following file:
FP2/propagator/varbound_propagator.cpp