BRKGA for MIP feasibility: dominiqs::CpxPresolver Class Reference
dominiqs::CpxPresolver Class Reference
#include <cpxutils.h>
Public Member Functions
CpxPresolver ()
void exec (Env env, Prob lp, const std::string &solFile="")
Public Attributes
bool preserveBinary
bool rootNodeProcessing
int cutEmphasis
Prob presolvedLp
Prob afterRootLp
double objOffset
int addedCuts
std::vector< double > incumbent
double incumbentValue
double presolveTime
bool isOptimal
Detailed Description
Let Cplex generate a presolved problem (and perform root node processing if cuts are needed)
Parameters
env cplex environment
lp problem to presolve
objOffset get objective offset due to presolve
preservebinary disable binary variables aggregation
rootNodeProcessing do full root node processing
Definition at line 217 of file cpxutils.h.
Constructor & Destructor Documentation
CpxPresolver()
dominiqs::CpxPresolver::CpxPresolver () inline
Definition at line 220 of file cpxutils.h.
Member Function Documentation
exec()
void dominiqs::CpxPresolver::exec (Env env, Prob lp, const std::string & solFile = "")
Definition at line 477 of file cpxutils.cpp.
References dominiqs::branchCB(), CHECKED_CPX_CALL, CLONE_PROB, DOMINIQS_ASSERT, FREE_PROB, dominiqs::Chrono::getTotal(), dominiqs::Chrono::start(), and dominiqs::Chrono::stop().
Referenced by dominiqs::CPXApp::startup().
Member Data Documentation
addedCuts
int dominiqs::CpxPresolver::addedCuts
Definition at line 232 of file cpxutils.h.
Referenced by dominiqs::branchCB().
afterRootLp
Prob dominiqs::CpxPresolver::afterRootLp
Definition at line 230 of file cpxutils.h.
Referenced by dominiqs::branchCB().
cutEmphasis
int dominiqs::CpxPresolver::cutEmphasis
Definition at line 227 of file cpxutils.h.
incumbent
std::vector<double> dominiqs::CpxPresolver::incumbent
Definition at line 233 of file cpxutils.h.
Referenced by dominiqs::branchCB().
incumbentValue
double dominiqs::CpxPresolver::incumbentValue
Definition at line 234 of file cpxutils.h.
Referenced by dominiqs::branchCB().
isOptimal
bool dominiqs::CpxPresolver::isOptimal
Definition at line 236 of file cpxutils.h.
objOffset
double dominiqs::CpxPresolver::objOffset
Definition at line 231 of file cpxutils.h.
Referenced by dominiqs::CPXApp::startup().
preserveBinary
bool dominiqs::CpxPresolver::preserveBinary
Definition at line 225 of file cpxutils.h.
presolvedLp
Prob dominiqs::CpxPresolver::presolvedLp
Definition at line 229 of file cpxutils.h.
Referenced by dominiqs::branchCB(), and dominiqs::CPXApp::startup().
presolveTime
double dominiqs::CpxPresolver::presolveTime
Definition at line 235 of file cpxutils.h.
rootNodeProcessing
bool dominiqs::CpxPresolver::rootNodeProcessing
Definition at line 226 of file cpxutils.h.
The documentation for this class was generated from the following files:
FP2/cpxutils/cpxutils.h
FP2/cpxutils/cpxutils.cpp