BRKGA for MIP feasibility: PositiveLinearAdvisor Class Reference
PositiveLinearAdvisor Class Reference
Public Member Functions
PositiveLinearAdvisor (LinearProp *p, int j, double coef)
void fixedUp ()
void fixedDown ()
void tightenLb (double delta, bool decreaseInfCnt, bool propagate)
void tightenUb (double delta, bool decreaseInfCnt, bool propagate)
std::ostream & print (std::ostream &out) const
Public Member Functions inherited from AdvisorI
AdvisorI (Propagator *p, int j)
virtual ~AdvisorI ()
Propagator * getPropagator () const
int getVar () const
Protected Attributes
double a
Protected Attributes inherited from AdvisorI
Propagator * prop
int var
Additional Inherited Members
Protected Member Functions inherited from AdvisorI
template<class T >
T * getMyProp ()
Detailed Description
Linear Constraint PropagatorAdvise for changes in a variable appearing in the constraint with a positive coefficient
Definition at line 34 of file linear_propagator.cpp.
Constructor & Destructor Documentation
PositiveLinearAdvisor()
PositiveLinearAdvisor::PositiveLinearAdvisor (LinearProp * p, int j, double coef) inline
Definition at line 37 of file linear_propagator.cpp.
Member Function Documentation
fixedDown()
void PositiveLinearAdvisor::fixedDown () inline virtual
Reimplemented from AdvisorI.
Definition at line 46 of file linear_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, dominiqs::greaterThan(), INFBOUND, LinearProp::lhs, LinearProp::maxAct, and LinearProp::maxActInfCnt.
fixedUp()
void PositiveLinearAdvisor::fixedUp () inline virtual
events for binary variables
Reimplemented from AdvisorI.
Definition at line 39 of file linear_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, INFBOUND, dominiqs::lessThan(), LinearProp::minAct, LinearProp::minActInfCnt, and LinearProp::rhs.
print()
std::ostream& PositiveLinearAdvisor::print (std::ostream & out) const inline virtual
Reimplemented from AdvisorI.
Definition at line 73 of file linear_propagator.cpp.
tightenLb()
void PositiveLinearAdvisor::tightenLb (double delta, bool decreaseInfCnt, bool propagate) inline virtual
events for other (general integer and continuous) variables
Parameters
delta bound increase (if it was finite) or new value if tightening from infinite
decreaseInfCnt (this flag is true if the previous value for the bound was infinite)
propagate mask to trigger or not constraint propagation
Reimplemented from AdvisorI.
Definition at line 54 of file linear_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, INFBOUND, dominiqs::lessThan(), LinearProp::minAct, LinearProp::minActInfCnt, LinearProp::minActInfIdx, and LinearProp::rhs.
tightenUb()
void PositiveLinearAdvisor::tightenUb (double delta, bool decreaseInfCnt, bool propagate) inline virtual
Reimplemented from AdvisorI.
Definition at line 63 of file linear_propagator.cpp.
References CSTATE_UNKNOWN, Propagator::dirty, dominiqs::greaterThan(), INFBOUND, LinearProp::lhs, LinearProp::maxAct, LinearProp::maxActInfCnt, and LinearProp::maxActInfIdx.
Member Data Documentation
a
double PositiveLinearAdvisor::a protected
Definition at line 78 of file linear_propagator.cpp.
The documentation for this class was generated from the following file:
FP2/propagator/linear_propagator.cpp