BRKGA for MIP feasibility: PropagationEngine Class Reference
PropagationEngine Class Reference
#include <prop_engine.h>
Public Member Functions
PropagationEngine ()
virtual ~PropagationEngine ()
Domain * getDomain ()
void setDomain (Domain *d)
virtual void pushPropagator (Propagator *prop)
virtual bool propagate ()
virtual bool propagate (int var, double value)
virtual bool propagate (const std::vector< int > &vars, const std::vector< double > &values)
const std::vector< int > & getLastFixed () const
bool failed () const
StatePtr getStateMgr ()
virtual void clear ()
Public Attributes
bool stopPropagationIfFailed
Protected Types
typedef std::map< int, std::deque< int > > Queue
Protected Member Functions
void fixedBinUp (int j)
void fixedBinDown (int j)
void tightenedLb (int j, double newValue, double oldValue)
void tightenedUb (int j, double newValue, double oldValue)
Propagator * top ()
Protected Attributes
Domain * domain
std::vector< int > vPropLbCount
std::vector< int > vPropUbCount
std::vector< std::list< AdvisorI * > > advisors
std::vector< Propagator * > propagators
Queue queue
std::vector< Decision > decisions
std::vector< int > lastFixed
bool hasFailed
Friends
class PropagationEngineState
Detailed Description
Propagation Engine Coordinates propagators actions, advisors and store the var domains
Definition at line 46 of file prop_engine.h.
Member Typedef Documentation
Queue
typedef std::map<int, std::deque<int> > PropagationEngine::Queue protected
Definition at line 80 of file prop_engine.h.
Constructor & Destructor Documentation
PropagationEngine()
PropagationEngine::PropagationEngine () inline
Definition at line 49 of file prop_engine.h.
~PropagationEngine()
PropagationEngine::~PropagationEngine () virtual
Definition at line 62 of file prop_engine.cpp.
Member Function Documentation
clear()
void PropagationEngine::clear () virtual
Definition at line 187 of file prop_engine.cpp.
Referenced by PropagatorRounding::clear().
failed()
bool PropagationEngine::failed () const inline
Definition at line 58 of file prop_engine.h.
References hasFailed.
fixedBinDown()
void PropagationEngine::fixedBinDown (int j) protected
Definition at line 267 of file prop_engine.cpp.
References Propagator::failed(), Propagator::getID(), and Propagator::pending().
Referenced by setDomain().
fixedBinUp()
void PropagationEngine::fixedBinUp (int j) protected
Definition at line 254 of file prop_engine.cpp.
References Propagator::failed(), Propagator::getID(), and Propagator::pending().
Referenced by setDomain().
getDomain()
Domain* PropagationEngine::getDomain () inline
Definition at line 51 of file prop_engine.h.
References domain.
getLastFixed()
const std::vector<int>& PropagationEngine::getLastFixed () const inline
Definition at line 57 of file prop_engine.h.
References lastFixed.
Referenced by PropagatorRounding::apply().
getStateMgr()
StatePtr PropagationEngine::getStateMgr ()
Definition at line 182 of file prop_engine.cpp.
Referenced by PropagatorRounding::init().
propagate() [1/3]
bool PropagationEngine::propagate () virtual
Definition at line 97 of file prop_engine.cpp.
References Propagator::failed(), Propagator::pending(), and Propagator::propagate().
Referenced by PropagatorRounding::apply().
propagate() [2/3]
bool PropagationEngine::propagate (int var, double value) virtual
Definition at line 112 of file prop_engine.cpp.
References dominiqs::isNull(), Propagator::pending(), and Propagator::propagate().
propagate() [3/3]
bool PropagationEngine::propagate (const std::vector< int > & vars, const std::vector< double > & values) virtual
Definition at line 143 of file prop_engine.cpp.
References DOMINIQS_ASSERT, dominiqs::isNull(), Propagator::pending(), and Propagator::propagate().
pushPropagator()
void PropagationEngine::pushPropagator (Propagator * prop) virtual
Definition at line 85 of file prop_engine.cpp.
References Propagator::createAdvisors(), DOMINIQS_ASSERT, Propagator::getDomain(), Propagator::getID(), Propagator::pending(), and Propagator::setID().
Referenced by PropagatorRounding::init().
setDomain()
void PropagationEngine::setDomain (Domain * d)
Definition at line 67 of file prop_engine.cpp.
References DOMINIQS_ASSERT, Domain::emitFixedBinUp, fixedBinDown(), fixedBinUp(), tightenedLb(), and tightenedUb().
Referenced by PropagatorRounding::init().
tightenedLb()
void PropagationEngine::tightenedLb (int j, double newValue, double oldValue) protected
Definition at line 212 of file prop_engine.cpp.
References Propagator::failed(), Propagator::getID(), dominiqs::greaterThan(), INFBOUND, and Propagator::pending().
Referenced by setDomain().
tightenedUb()
void PropagationEngine::tightenedUb (int j, double newValue, double oldValue) protected
Definition at line 233 of file prop_engine.cpp.
References Propagator::failed(), Propagator::getID(), INFBOUND, dominiqs::lessThan(), and Propagator::pending().
Referenced by setDomain().
top()
Propagator * PropagationEngine::top () protected
Definition at line 280 of file prop_engine.cpp.
Friends And Related Function Documentation
PropagationEngineState
friend class PropagationEngineState friend
Definition at line 72 of file prop_engine.h.
Member Data Documentation
advisors
std::vector< std::list<AdvisorI*> > PropagationEngine::advisors protected
Definition at line 77 of file prop_engine.h.
decisions
std::vector<Decision> PropagationEngine::decisions protected
Definition at line 83 of file prop_engine.h.
domain
Domain* PropagationEngine::domain protected
Definition at line 74 of file prop_engine.h.
Referenced by getDomain().
hasFailed
bool PropagationEngine::hasFailed protected
Definition at line 85 of file prop_engine.h.
Referenced by failed().
lastFixed
std::vector<int> PropagationEngine::lastFixed protected
Definition at line 84 of file prop_engine.h.
Referenced by getLastFixed().
propagators
std::vector<Propagator*> PropagationEngine::propagators protected
Definition at line 79 of file prop_engine.h.
queue
Queue PropagationEngine::queue protected
Definition at line 81 of file prop_engine.h.
stopPropagationIfFailed
bool PropagationEngine::stopPropagationIfFailed
Definition at line 64 of file prop_engine.h.
vPropLbCount
std::vector<int> PropagationEngine::vPropLbCount protected
Definition at line 75 of file prop_engine.h.
vPropUbCount
std::vector<int> PropagationEngine::vPropUbCount protected
Definition at line 76 of file prop_engine.h.
The documentation for this class was generated from the following files:
FP2/propagator/prop_engine.h
FP2/propagator/prop_engine.cpp