BRKGA for MIP feasibility: dominiqs::CutPool Class Reference
dominiqs::CutPool Class Reference
#include <cutpool.h>
Public Types
typedef boost::unordered_set< CutPtr, cutptr_hash, cutptr_equal >::const_iterator const_iterator
Public Member Functions
CutPool ()
void readConfig (XMLConfig &config, const std::string &root)
bool push (CutPtr cut)
void merge (CutPool &other)
bool isViolated (const double *x) const
int numViolated (const double *x) const
bool select (const std::vector< double > &x, CutList &cuts)
int purge (const std::vector< double > &x)
void clear ()
unsigned int size () const
unsigned int numAdded () const
unsigned int numDuplicate () const
double memoryUsed () const
const_iterator begin () const
const_iterator end () const
Public Attributes
std::string name
unsigned int maxSeparated
double minEfficacy
double minOrtho
double maxMemory
unsigned int maxSize
bool logConfig
Protected Member Functions
bool isDuplicate (CutPtr cut) const
Protected Attributes
boost::unordered_set< CutPtr, cutptr_hash, cutptr_equal > pool
unsigned int nadded
unsigned int nduplicate
double mem
Detailed Description
This class implements a cut pool, with a corresponding selection strategy
Definition at line 112 of file cutpool.h.
Member Typedef Documentation
const_iterator
typedef boost::unordered_set<CutPtr, cutptr_hash, cutptr_equal>::const_iterator dominiqs::CutPool::const_iterator
Definition at line 129 of file cutpool.h.
Constructor & Destructor Documentation
CutPool()
dominiqs::CutPool::CutPool ()
Definition at line 94 of file cutpool.cpp.
Member Function Documentation
begin()
const_iterator dominiqs::CutPool::begin () const inline
Definition at line 130 of file cutpool.h.
References pool.
Referenced by dominiqs::cpxBB().
clear()
void dominiqs::CutPool::clear () inline
Definition at line 123 of file cutpool.h.
References mem, nadded, nduplicate, and pool.
Referenced by merge().
end()
const_iterator dominiqs::CutPool::end () const inline
Definition at line 131 of file cutpool.h.
References pool.
Referenced by dominiqs::cpxBB().
isDuplicate()
bool dominiqs::CutPool::isDuplicate (CutPtr cut) const protected
Definition at line 217 of file cutpool.cpp.
References DOMINIQS_ASSERT, and pool.
Referenced by push().
isViolated()
bool dominiqs::CutPool::isViolated (const double * x) const
Definition at line 121 of file cutpool.cpp.
References minEfficacy, and pool.
memoryUsed()
double dominiqs::CutPool::memoryUsed () const inline
Definition at line 127 of file cutpool.h.
References mem.
Referenced by purge().
merge()
void dominiqs::CutPool::merge (CutPool & other)
Definition at line 112 of file cutpool.cpp.
References clear(), pool, and push().
numAdded()
unsigned int dominiqs::CutPool::numAdded () const inline
Definition at line 125 of file cutpool.h.
References nadded.
numDuplicate()
unsigned int dominiqs::CutPool::numDuplicate () const inline
Definition at line 126 of file cutpool.h.
References nduplicate.
numViolated()
int dominiqs::CutPool::numViolated (const double * x) const
Definition at line 131 of file cutpool.cpp.
References minEfficacy, and pool.
purge()
int dominiqs::CutPool::purge (const std::vector< double > & x)
Definition at line 194 of file cutpool.cpp.
References maxMemory, maxSize, mem, memoryUsed(), pool, size(), and sort().
push()
bool dominiqs::CutPool::push (CutPtr cut)
Definition at line 99 of file cutpool.cpp.
References isDuplicate(), mem, nadded, nduplicate, and pool.
Referenced by merge(), and dominiqs::GomorySeparator::separateGMI().
readConfig()
void dominiqs::CutPool::readConfig (XMLConfig & config, const std::string & root)
Definition at line 223 of file cutpool.cpp.
References dominiqs::XMLConfig::get(), dominiqs::gLog(), logConfig, dominiqs::Logger::logItem(), dominiqs::MAX_MEMORY_DEF, dominiqs::MAX_SEPARATED_DEF, dominiqs::MAX_SIZE_DEF, maxMemory, maxSeparated, maxSize, dominiqs::MIN_EFFICACY_DEF, dominiqs::MIN_ORTHO_DEF, minEfficacy, minOrtho, and name.
select()
bool dominiqs::CutPool::select (const std::vector< double > & x, CutList & cuts)
Definition at line 142 of file cutpool.cpp.
References dominiqs::dotProduct(), dominiqs::isPositive(), maxSeparated, min, minEfficacy, minOrtho, pool, dominiqs::numarray< T >::push_back(), and sort().
size()
unsigned int dominiqs::CutPool::size () const inline
Definition at line 124 of file cutpool.h.
References pool.
Referenced by dominiqs::cpxBB(), and purge().
Member Data Documentation
logConfig
bool dominiqs::CutPool::logConfig
Definition at line 139 of file cutpool.h.
Referenced by readConfig().
maxMemory
double dominiqs::CutPool::maxMemory
Definition at line 137 of file cutpool.h.
Referenced by purge(), and readConfig().
maxSeparated
unsigned int dominiqs::CutPool::maxSeparated
Definition at line 134 of file cutpool.h.
Referenced by readConfig(), and select().
maxSize
unsigned int dominiqs::CutPool::maxSize
Definition at line 138 of file cutpool.h.
Referenced by purge(), and readConfig().
mem
double dominiqs::CutPool::mem protected
Definition at line 144 of file cutpool.h.
Referenced by clear(), memoryUsed(), purge(), and push().
minEfficacy
double dominiqs::CutPool::minEfficacy
Definition at line 135 of file cutpool.h.
Referenced by isViolated(), numViolated(), readConfig(), and select().
minOrtho
double dominiqs::CutPool::minOrtho
Definition at line 136 of file cutpool.h.
Referenced by readConfig(), and select().
nadded
unsigned int dominiqs::CutPool::nadded protected
Definition at line 142 of file cutpool.h.
Referenced by clear(), numAdded(), and push().
name
std::string dominiqs::CutPool::name
Definition at line 133 of file cutpool.h.
Referenced by readConfig().
nduplicate
unsigned int dominiqs::CutPool::nduplicate protected
Definition at line 143 of file cutpool.h.
Referenced by clear(), numDuplicate(), and push().
pool
boost::unordered_set<CutPtr, cutptr_hash, cutptr_equal> dominiqs::CutPool::pool protected
Definition at line 141 of file cutpool.h.
Referenced by begin(), clear(), end(), isDuplicate(), isViolated(), merge(), numViolated(), purge(), push(), select(), and size().
The documentation for this class was generated from the following files:
FP2/utils/cutpool.h
FP2/utils/cutpool.cpp