BRKGA for MIP feasibility: dominiqs::IniFile Class Reference
dominiqs::IniFile Class Reference
#include <ini_spirit.h>
Public Member Functions
bool load (const std::string &filename)
void save (std::ostream &out) const
void save (const std::string &filename) const
CategoryPtr addCategory (const std::string &name)
void addCategory (CategoryPtr cat)
CategoryPtr getCategory (const std::string &name) const
void deleteCategory (const std::string &name)
std::string get (const std::string &cat, const std::string &entry, const std::string &defValue) const
void set (const std::string &cat, const std::string &entry, const std::string &value)
Protected Types
typedef std::list< CategoryPtr > CategoryList
Protected Attributes
CategoryList categories
Detailed Description
Definition at line 55 of file ini_spirit.h.
Member Typedef Documentation
CategoryList
typedef std::list<CategoryPtr> dominiqs::IniFile::CategoryList protected
Definition at line 70 of file ini_spirit.h.
Member Function Documentation
addCategory() [1/2]
CategoryPtr dominiqs::IniFile::addCategory (const std::string & name)
Definition at line 212 of file ini_spirit.cpp.
References categories, DOMINIQS_ASSERT, and getCategory().
Referenced by dominiqs::IniParserContext::addCategory(), dominiqs::IniParserContext::addEntry(), and set().
addCategory() [2/2]
void dominiqs::IniFile::addCategory (CategoryPtr cat)
Definition at line 224 of file ini_spirit.cpp.
References categories, deleteCategory(), and DOMINIQS_ASSERT.
deleteCategory()
void dominiqs::IniFile::deleteCategory (const std::string & name)
Definition at line 238 of file ini_spirit.cpp.
References categories.
Referenced by addCategory().
get()
std::string dominiqs::IniFile::get (const std::string & cat, const std::string & entry, const std::string & defValue) const
Definition at line 243 of file ini_spirit.cpp.
References getCategory().
getCategory()
CategoryPtr dominiqs::IniFile::getCategory (const std::string & name) const
Definition at line 231 of file ini_spirit.cpp.
References categories.
Referenced by addCategory(), dominiqs::IniParserContext::addEntry(), get(), and set().
load()
bool dominiqs::IniFile::load (const std::string & filename)
Definition at line 127 of file ini_spirit.cpp.
References dominiqs::IniParserContext::addCategory(), dominiqs::IniParserContext::addEntry(), and dominiqs::IniParserContext::addValue().
save() [1/2]
void dominiqs::IniFile::save (std::ostream & out) const
Definition at line 192 of file ini_spirit.cpp.
References categories.
Referenced by save().
save() [2/2]
void dominiqs::IniFile::save (const std::string & filename) const
Definition at line 186 of file ini_spirit.cpp.
References save().
set()
void dominiqs::IniFile::set (const std::string & cat, const std::string & entry, const std::string & value)
Definition at line 250 of file ini_spirit.cpp.
References addCategory(), and getCategory().
Referenced by dominiqs::IniParserContext::addValue().
Member Data Documentation
categories
CategoryList dominiqs::IniFile::categories protected
Definition at line 71 of file ini_spirit.h.
Referenced by addCategory(), deleteCategory(), getCategory(), and save().
The documentation for this class was generated from the following files:
FP2/utils/ini_spirit.h
FP2/utils/ini_spirit.cpp