BRKGA for MIP feasibility: dominiqs::intrusive_weak_ptr< T > Class Template Reference
dominiqs::intrusive_weak_ptr< T > Class Template Reference
Real intrusive weak pointer.
#include <intrusive_weak_ptr.h>
Public Member Functions
intrusive_weak_ptr (T *o=0)
template<class U >
intrusive_weak_ptr (intrusive_weak_ptr< U > &rhs)
template<class U >
intrusive_weak_ptr (boost::intrusive_ptr< U > &rhs)
template<class U >
intrusive_weak_ptr & operator= (intrusive_weak_ptr< U > &rhs)
template<class U >
intrusive_weak_ptr & operator= (boost::intrusive_ptr< U > &rhs)
~intrusive_weak_ptr ()
T * get () const
T * operator-> () const
bool expired () const
operator bool () const
void reset ()
Static Public Member Functions
static void release (intrusive_weak_ptr_base *head)
Public Attributes
T * obj
Protected Member Functions
void insertIntoList (T *obj)
void removeFromList (T *obj)
Additional Inherited Members
Private Member Functions inherited from dominiqs::intrusive_weak_ptr_base
intrusive_weak_ptr_base ()
virtual ~intrusive_weak_ptr_base ()
void insertIntoList (intrusive_weak_ptr_base *head)
void removeFromList ()
Private Attributes inherited from dominiqs::intrusive_weak_ptr_base
intrusive_weak_ptr_base * next
intrusive_weak_ptr_base * prev
Detailed Description
template<class T>
class dominiqs::intrusive_weak_ptr< T >
Real intrusive weak pointer.
The user must provide 4 functions for cooperation between object (type T) and pointer (that is what intrusive means...)
void intrusive_ptr_add_ref(T* obj): increases reference count of obj void intrusive_ptr_release(T* obj): decreases reference count and eventually delete obj intrusive_weak_ptr_base* intrusive_weak_ptr_get_head(T* obj): get list head of obj void intrusive_weak_ptr_set_head(T* obj, intrusive_weak_ptr_base* ptr): set list head of obj
(each object keeps a list of weak ptrs to itself and, in the destructor, calls intrusive_weak_ptr<T>::release(head) to reset pointers)
Definition at line 55 of file intrusive_weak_ptr.h.
Constructor & Destructor Documentation
intrusive_weak_ptr() [1/3]
template<class T> dominiqs::intrusive_weak_ptr< T >::intrusive_weak_ptr (T * o = 0) inline
Definition at line 58 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::insertIntoList(), and dominiqs::intrusive_weak_ptr< T >::obj.
intrusive_weak_ptr() [2/3]
template<class T> template<class U > dominiqs::intrusive_weak_ptr< T >::intrusive_weak_ptr (intrusive_weak_ptr< U > & rhs) inline
Definition at line 62 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::insertIntoList(), and dominiqs::intrusive_weak_ptr< T >::obj.
intrusive_weak_ptr() [3/3]
template<class T> template<class U > dominiqs::intrusive_weak_ptr< T >::intrusive_weak_ptr (boost::intrusive_ptr< U > & rhs) inline
Definition at line 67 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::insertIntoList(), and dominiqs::intrusive_weak_ptr< T >::obj.
~intrusive_weak_ptr()
template<class T> dominiqs::intrusive_weak_ptr< T >::~intrusive_weak_ptr () inline
Definition at line 89 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::obj, and dominiqs::intrusive_weak_ptr_base::removeFromList().
Member Function Documentation
expired()
template<class T> bool dominiqs::intrusive_weak_ptr< T >::expired () const inline
Definition at line 101 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::obj.
get()
template<class T> T* dominiqs::intrusive_weak_ptr< T >::get () const inline
Definition at line 93 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::obj.
Referenced by dominiqs::dynamic_pointer_cast(), dominiqs::operator!=(), dominiqs::operator<(), dominiqs::operator==(), and dominiqs::static_pointer_cast().
insertIntoList()
template<class T> void dominiqs::intrusive_weak_ptr< T >::insertIntoList (T * obj) inline protected
Definition at line 123 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr_base::insertIntoList(), dominiqs::intrusive_weak_ptr_get_head(), dominiqs::intrusive_weak_ptr_set_head(), and dominiqs::intrusive_weak_ptr< T >::obj.
Referenced by dominiqs::intrusive_weak_ptr< T >::intrusive_weak_ptr(), and dominiqs::intrusive_weak_ptr< T >::operator=().
operator bool()
template<class T> dominiqs::intrusive_weak_ptr< T >::operator bool () const inline
Definition at line 105 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::obj.
operator->()
template<class T> T* dominiqs::intrusive_weak_ptr< T >::operator-> () const inline
Definition at line 97 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::obj.
operator=() [1/2]
template<class T> template<class U > intrusive_weak_ptr& dominiqs::intrusive_weak_ptr< T >::operator= (intrusive_weak_ptr< U > & rhs) inline
Definition at line 72 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::insertIntoList(), dominiqs::intrusive_weak_ptr< T >::obj, and dominiqs::intrusive_weak_ptr_base::removeFromList().
operator=() [2/2]
template<class T> template<class U > intrusive_weak_ptr& dominiqs::intrusive_weak_ptr< T >::operator= (boost::intrusive_ptr< U > & rhs) inline
Definition at line 82 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::insertIntoList(), dominiqs::intrusive_weak_ptr< T >::obj, and dominiqs::intrusive_weak_ptr_base::removeFromList().
release()
template<class T> static void dominiqs::intrusive_weak_ptr< T >::release (intrusive_weak_ptr_base * head) inline static
Definition at line 113 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr_base::next, and dominiqs::intrusive_weak_ptr_base::reset().
Referenced by dominiqs::ManagedObjectWeak::~ManagedObjectWeak().
removeFromList()
template<class T> void dominiqs::intrusive_weak_ptr< T >::removeFromList (T * obj) inline protected
Definition at line 129 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr_set_head(), dominiqs::intrusive_weak_ptr_base::next, dominiqs::intrusive_weak_ptr< T >::obj, dominiqs::intrusive_weak_ptr_base::prev, and dominiqs::intrusive_weak_ptr_base::removeFromList().
reset()
template<class T> void dominiqs::intrusive_weak_ptr< T >::reset () inline virtual
Implements dominiqs::intrusive_weak_ptr_base.
Definition at line 109 of file intrusive_weak_ptr.h.
References dominiqs::intrusive_weak_ptr< T >::obj.
Member Data Documentation
obj
template<class T> T* dominiqs::intrusive_weak_ptr< T >::obj
Definition at line 121 of file intrusive_weak_ptr.h.
Referenced by dominiqs::intrusive_weak_ptr< T >::expired(), dominiqs::intrusive_weak_ptr< T >::get(), dominiqs::intrusive_weak_ptr< T >::insertIntoList(), dominiqs::intrusive_weak_ptr< T >::intrusive_weak_ptr(), dominiqs::intrusive_weak_ptr< T >::operator bool(), dominiqs::intrusive_weak_ptr< T >::operator->(), dominiqs::intrusive_weak_ptr< T >::operator=(), dominiqs::intrusive_weak_ptr< T >::removeFromList(), dominiqs::intrusive_weak_ptr< T >::reset(), and dominiqs::intrusive_weak_ptr< T >::~intrusive_weak_ptr().
The documentation for this class was generated from the following file:
FP2/utils/intrusive_weak_ptr.h