BRKGA for MIP feasibility: CardinalityProp Class Reference
CardinalityProp Class Reference
Propagator for the cardinality constraint lhs <= e x <= rhs, all x_j binary.
#include <linear_propagator.h>
Public Member Functions
CardinalityProp (Domain *d, PropagatorFactory *fact, dominiqs::Constraint *c)
void createAdvisors (std::list< AdvisorI * > &advisors)
void propagate ()
StatePtr getStateMgr ()
std::ostream & print (std::ostream &out) const
Public Member Functions inherited from Propagator
Propagator (Domain *d, PropagatorFactory *fact=0)
virtual ~Propagator ()
void setName (const std::string &n)
const std::string & getName () const
int getID () const
void setID (int _id)
int getPriority () const
void setPriority (int p)
Domain * getDomain () const
void setPending ()
bool pending () const
PropagatorState getState () const
bool failed () const
Protected Member Functions
void updateState ()
Protected Attributes
int lhs
int rhs
std::vector< int > idx
int minAct
int maxAct
Protected Attributes inherited from Propagator
Domain * domain
PropagatorFactory * factory
int id
int priority
bool dirty
PropagatorState state
std::string name
Friends
class CardinalityAdvisor
class CardinalityPropState
Detailed Description
Propagator for the cardinality constraint lhs <= e x <= rhs, all x_j binary.
Covers set covering/packing/partitioning as special cases
Definition at line 79 of file linear_propagator.h.
Constructor & Destructor Documentation
CardinalityProp()
CardinalityProp::CardinalityProp (Domain * d, PropagatorFactory * fact, dominiqs::Constraint * c)
Definition at line 621 of file linear_propagator.cpp.
References CARDINALITY_DEFAULT_PRIORITY, dominiqs::ceilEps(), Propagator::domain, DOMINIQS_ASSERT, dominiqs::equal(), dominiqs::floorEps(), dominiqs::SparseVector::idx(), idx, dominiqs::isNull(), lhs, maxAct, minAct, Propagator::name, dominiqs::Constraint::name, rhs, dominiqs::Constraint::rhs, dominiqs::Constraint::row, dominiqs::Constraint::sense, Propagator::setPriority(), dominiqs::SparseVector::size(), updateState(), Domain::varLb(), and Domain::varUb().
Member Function Documentation
createAdvisors()
void CardinalityProp::createAdvisors (std::list< AdvisorI * > & advisors) virtual
Create the advisors needed to effectively propagate and return them
Reimplemented from Propagator.
Definition at line 662 of file linear_propagator.cpp.
References CardinalityAdvisor, and idx.
getStateMgr()
StatePtr CardinalityProp::getStateMgr () virtual
Reimplemented from Propagator.
Definition at line 705 of file linear_propagator.cpp.
References CardinalityPropState.
print()
std::ostream & CardinalityProp::print (std::ostream & out) const virtual
Reimplemented from Propagator.
Definition at line 710 of file linear_propagator.cpp.
References lhs, maxAct, minAct, Propagator::name, PropagatorStateName, rhs, and Propagator::state.
propagate()
void CardinalityProp::propagate () virtual
Do a one-pass propagation of the constraint
Implements Propagator.
Definition at line 684 of file linear_propagator.cpp.
References Propagator::dirty, Propagator::domain, PropagatorFactory::domainReductions(), Propagator::factory, Domain::fixBinDown(), Domain::fixBinUp(), idx, Domain::isVarFixed(), lhs, maxAct, minAct, PropagatorFactory::propCalled(), and rhs.
updateState()
void CardinalityProp::updateState () protected virtual
Reimplemented from Propagator.
Definition at line 667 of file linear_propagator.cpp.
References CSTATE_ENTAILED, CSTATE_INFEAS, CSTATE_UNKNOWN, Propagator::dirty, lhs, maxAct, minAct, rhs, and Propagator::state.
Referenced by CardinalityProp().
Friends And Related Function Documentation
CardinalityAdvisor
friend class CardinalityAdvisor friend
Definition at line 89 of file linear_propagator.h.
Referenced by createAdvisors().
CardinalityPropState
friend class CardinalityPropState friend
Definition at line 90 of file linear_propagator.h.
Referenced by getStateMgr().
Member Data Documentation
idx
std::vector<int> CardinalityProp::idx protected
Definition at line 93 of file linear_propagator.h.
Referenced by CardinalityProp(), createAdvisors(), and propagate().
lhs
int CardinalityProp::lhs protected
Definition at line 91 of file linear_propagator.h.
Referenced by CardinalityProp(), CardinalityAdvisor::fixedDown(), print(), propagate(), and updateState().
maxAct
int CardinalityProp::maxAct protected
Definition at line 95 of file linear_propagator.h.
Referenced by CardinalityProp(), CardinalityPropState::dump(), CardinalityAdvisor::fixedDown(), print(), propagate(), CardinalityPropState::restore(), and updateState().
minAct
int CardinalityProp::minAct protected
Definition at line 94 of file linear_propagator.h.
Referenced by CardinalityProp(), CardinalityPropState::dump(), CardinalityAdvisor::fixedUp(), print(), propagate(), CardinalityPropState::restore(), and updateState().
rhs
int CardinalityProp::rhs protected
Definition at line 92 of file linear_propagator.h.
Referenced by CardinalityProp(), CardinalityAdvisor::fixedUp(), print(), propagate(), and updateState().
The documentation for this class was generated from the following files:
FP2/propagator/linear_propagator.h
FP2/propagator/linear_propagator.cpp