BRKGA for MIP feasibility: dominiqs::OptimalFaceFixer Class Reference
dominiqs::OptimalFaceFixer Class Reference
#include <cpxutils.h>
Public Member Functions
void init (dominiqs::CEnv env, dominiqs::Prob lp)
void exec (dominiqs::CEnv env, dominiqs::Prob lp)
void undo (dominiqs::CEnv env, dominiqs::Prob lp)
Protected Attributes
dominiqs::numarray< double > lb
dominiqs::numarray< double > ub
dominiqs::numarray< char > sense
dominiqs::numarray< double > obj
double origObjValue
dominiqs::numarray< int > rowIndices
dominiqs::numarray< int > colIndices
dominiqs::numarray< double > red
dominiqs::numarray< double > x
dominiqs::numarray< double > dual
dominiqs::numarray< int > cstat
dominiqs::numarray< int > rstat
Detailed Description
OptimalFaceFixer class This class provides an (almost) efficient method to fix on the optimal face of a polyhedron (and back!)
Definition at line 123 of file cpxutils.h.
Member Function Documentation
exec()
void dominiqs::OptimalFaceFixer::exec (dominiqs::CEnv env, dominiqs::Prob lp)
Definition at line 276 of file cpxutils.cpp.
References CHECKED_CPX_CALL, dominiqs::different(), and dominiqs::isNotNull().
init()
void dominiqs::OptimalFaceFixer::init (dominiqs::CEnv env, dominiqs::Prob lp)
Definition at line 253 of file cpxutils.cpp.
References CHECKED_CPX_CALL, and dominiqs::iota().
undo()
void dominiqs::OptimalFaceFixer::undo (dominiqs::CEnv env, dominiqs::Prob lp)
Definition at line 306 of file cpxutils.cpp.
References CHECKED_CPX_CALL, DOMINIQS_ASSERT, dominiqs::dotProduct(), and dominiqs::relEqual().
Member Data Documentation
colIndices
dominiqs::numarray<int> dominiqs::OptimalFaceFixer::colIndices protected
Definition at line 137 of file cpxutils.h.
cstat
dominiqs::numarray<int> dominiqs::OptimalFaceFixer::cstat protected
Definition at line 142 of file cpxutils.h.
dual
dominiqs::numarray<double> dominiqs::OptimalFaceFixer::dual protected
Definition at line 141 of file cpxutils.h.
lb
dominiqs::numarray<double> dominiqs::OptimalFaceFixer::lb protected
Definition at line 131 of file cpxutils.h.
obj
dominiqs::numarray<double> dominiqs::OptimalFaceFixer::obj protected
Definition at line 134 of file cpxutils.h.
origObjValue
double dominiqs::OptimalFaceFixer::origObjValue protected
Definition at line 135 of file cpxutils.h.
red
dominiqs::numarray<double> dominiqs::OptimalFaceFixer::red protected
Definition at line 139 of file cpxutils.h.
rowIndices
dominiqs::numarray<int> dominiqs::OptimalFaceFixer::rowIndices protected
Definition at line 136 of file cpxutils.h.
rstat
dominiqs::numarray<int> dominiqs::OptimalFaceFixer::rstat protected
Definition at line 143 of file cpxutils.h.
sense
dominiqs::numarray<char> dominiqs::OptimalFaceFixer::sense protected
Definition at line 133 of file cpxutils.h.
ub
dominiqs::numarray<double> dominiqs::OptimalFaceFixer::ub protected
Definition at line 132 of file cpxutils.h.
x
dominiqs::numarray<double> dominiqs::OptimalFaceFixer::x protected
Definition at line 140 of file cpxutils.h.
The documentation for this class was generated from the following files:
FP2/cpxutils/cpxutils.h
FP2/cpxutils/cpxutils.cpp