BRKGA for MIP feasibility: dominiqs::numarray< T > Class Template Reference
dominiqs::numarray< T > Class Template Reference
Vector replacement for numerical data.
#include <numarray.h>
Public Types
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef ptrdiff_t difference_type
typedef size_t size_type
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
numarray ()
numarray (size_type n)
numarray (const numarray &other)
numarray & operator= (const numarray &other)
~numarray () throw ()
void swap (numarray &other) throw ()
void fill (const value_type &val)
void zero ()
void iota (const value_type &value)
size_type size () const
size_type capacity () const
void resize (size_type newSize)
bool empty () const
void reserve (size_type n)
void clear ()
void push_back (const value_type &val)
void push_back_unsafe (const value_type &val)
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
pointer c_ptr ()
const_pointer c_ptr () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Private Attributes
T * data
size_type length
size_type alloc
Detailed Description
template<typename T>
class dominiqs::numarray< T >
Vector replacement for numerical data.
It has the following "improvements" over std::vectoc:
allocated always memory is properly aligned (enabling SSE2 instructions)
no constructor/destructor calls for elements
fast push_back without size checks (push_back_unsafe method)
explicit conversion to C array (via c_ptr() method)
Template Parameters
T value type of the numarray
Definition at line 33 of file numarray.h.
Member Typedef Documentation
const_iterator
template<typename T> typedef const T* dominiqs::numarray< T >::const_iterator
Definition at line 46 of file numarray.h.
const_pointer
template<typename T> typedef const T* dominiqs::numarray< T >::const_pointer
Definition at line 42 of file numarray.h.
const_reference
template<typename T> typedef const T& dominiqs::numarray< T >::const_reference
Definition at line 40 of file numarray.h.
difference_type
template<typename T> typedef ptrdiff_t dominiqs::numarray< T >::difference_type
Definition at line 43 of file numarray.h.
iterator
template<typename T> typedef T* dominiqs::numarray< T >::iterator
Definition at line 45 of file numarray.h.
pointer
template<typename T> typedef T* dominiqs::numarray< T >::pointer
Definition at line 41 of file numarray.h.
reference
template<typename T> typedef T& dominiqs::numarray< T >::reference
Definition at line 39 of file numarray.h.
size_type
template<typename T> typedef size_t dominiqs::numarray< T >::size_type
Definition at line 44 of file numarray.h.
value_type
template<typename T> typedef T dominiqs::numarray< T >::value_type
Definition at line 38 of file numarray.h.
Constructor & Destructor Documentation
numarray() [1/3]
template<typename T> dominiqs::numarray< T >::numarray () inline
Create an empty numarray
Definition at line 52 of file numarray.h.
numarray() [2/3]
template<typename T> dominiqs::numarray< T >::numarray (size_type n) inline
Create a numarray with n uninitialized elements.
Definition at line 57 of file numarray.h.
numarray() [3/3]
template<typename T> dominiqs::numarray< T >::numarray (const numarray< T > & other) inline
Copy constructor
Definition at line 77 of file numarray.h.
~numarray()
template<typename T> dominiqs::numarray< T >::~numarray () throw () inline
Definition at line 108 of file numarray.h.
Member Function Documentation
back() [1/2]
template<typename T> reference dominiqs::numarray< T >::back () inline
Definition at line 201 of file numarray.h.
back() [2/2]
template<typename T> const_reference dominiqs::numarray< T >::back () const inline
Definition at line 206 of file numarray.h.
begin() [1/2]
template<typename T> iterator dominiqs::numarray< T >::begin () inline
Definition at line 217 of file numarray.h.
begin() [2/2]
template<typename T> const_iterator dominiqs::numarray< T >::begin () const inline
Definition at line 218 of file numarray.h.
c_ptr() [1/2]
template<typename T> pointer dominiqs::numarray< T >::c_ptr () inline
Definition at line 211 of file numarray.h.
Referenced by dominiqs::Model::extract(), dominiqs::GomorySeparator::separateGMI(), and dominiqs::GomorySeparator::separateOneGMI().
c_ptr() [2/2]
template<typename T> const_pointer dominiqs::numarray< T >::c_ptr () const inline
Definition at line 212 of file numarray.h.
capacity()
template<typename T> size_type dominiqs::numarray< T >::capacity () const inline
Definition at line 122 of file numarray.h.
clear()
template<typename T> void dominiqs::numarray< T >::clear () inline
Definition at line 157 of file numarray.h.
Referenced by dominiqs::GomorySeparator::calculateTableauRow(), dominiqs::GomorySeparator::separateOneGMI(), and dominiqs::GomorySeparator::setX().
empty()
template<typename T> bool dominiqs::numarray< T >::empty () const inline
Definition at line 146 of file numarray.h.
end() [1/2]
template<typename T> iterator dominiqs::numarray< T >::end () inline
Definition at line 219 of file numarray.h.
end() [2/2]
template<typename T> const_iterator dominiqs::numarray< T >::end () const inline
Definition at line 220 of file numarray.h.
fill()
template<typename T> void dominiqs::numarray< T >::fill (const value_type & val) inline
Assign a given value to every element in the array
Parameters
val value to assign
Definition at line 228 of file numarray.h.
front() [1/2]
template<typename T> reference dominiqs::numarray< T >::front () inline
Definition at line 191 of file numarray.h.
front() [2/2]
template<typename T> const_reference dominiqs::numarray< T >::front () const inline
Definition at line 196 of file numarray.h.
iota()
template<typename T> void dominiqs::numarray< T >::iota (const value_type & value) inline
Initialize the array with consecutive elements, starting from
Parameters
value
Definition at line 242 of file numarray.h.
operator=()
template<typename T> numarray& dominiqs::numarray< T >::operator= (const numarray< T > & other) inline
assignment operator (swap idiom)
Definition at line 98 of file numarray.h.
operator[]() [1/2]
template<typename T> reference dominiqs::numarray< T >::operator[] (size_type i) inline
Definition at line 189 of file numarray.h.
operator[]() [2/2]
template<typename T> const_reference dominiqs::numarray< T >::operator[] (size_type i) const inline
Definition at line 190 of file numarray.h.
push_back()
template<typename T> void dominiqs::numarray< T >::push_back (const value_type & val) inline
Push a new element to the end of array.
This method checks if there is enough memory for the operation, if not it asks for more.
Parameters
val value to add
Definition at line 169 of file numarray.h.
Referenced by dominiqs::CutPool::select(), and dominiqs::GomorySeparator::setX().
push_back_unsafe()
template<typename T> void dominiqs::numarray< T >::push_back_unsafe (const value_type & val) inline
Push a new element to the end of array.
This method does NOT check if there is enough memory for the operation.
Parameters
val value to add
Definition at line 181 of file numarray.h.
Referenced by dominiqs::GomorySeparator::calculateTableauRow(), and dominiqs::numarray< bool >::push_back().
reserve()
template<typename T> void dominiqs::numarray< T >::reserve (size_type n) inline
Definition at line 147 of file numarray.h.
Referenced by dominiqs::GomorySeparator::calculateTableauRow(), dominiqs::numarray< bool >::push_back(), and dominiqs::numarray< bool >::resize().
resize()
template<typename T> void dominiqs::numarray< T >::resize (size_type newSize) inline
Resize the array
Memory is reallocated only if necessary. In any case, new elements are uninitialized
Parameters
newSize new size
Definition at line 131 of file numarray.h.
Referenced by dominiqs::GomorySeparator::calculateTableauRow(), dominiqs::Model::extract(), and dominiqs::GomorySeparator::separateOneGMI().
size()
template<typename T> size_type dominiqs::numarray< T >::size () const inline
Definition at line 121 of file numarray.h.
Referenced by dominiqs::GomorySeparator::calculateTableauRow(), dominiqs::GomorySeparator::separateOneGMI(), and dominiqs::GomorySeparator::setX().
swap()
template<typename T> void dominiqs::numarray< T >::swap (numarray< T > & other) throw () inline
Definition at line 113 of file numarray.h.
Referenced by dominiqs::numarray< bool >::operator=(), and dominiqs::numarray< bool >::reserve().
zero()
template<typename T> void dominiqs::numarray< T >::zero () inline
Assign the value zero to every element in the array
Definition at line 235 of file numarray.h.
Referenced by dominiqs::GomorySeparator::calculateTableauRow().
Member Data Documentation
alloc
template<typename T> size_type dominiqs::numarray< T >::alloc private
Definition at line 249 of file numarray.h.
Referenced by dominiqs::numarray< bool >::capacity(), dominiqs::numarray< bool >::numarray(), dominiqs::numarray< bool >::push_back(), dominiqs::numarray< bool >::reserve(), dominiqs::numarray< bool >::resize(), and dominiqs::numarray< bool >::swap().
data
template<typename T> T* dominiqs::numarray< T >::data private
Definition at line 247 of file numarray.h.
Referenced by dominiqs::numarray< bool >::back(), dominiqs::numarray< bool >::begin(), dominiqs::numarray< bool >::c_ptr(), dominiqs::numarray< bool >::end(), dominiqs::numarray< bool >::fill(), dominiqs::numarray< bool >::front(), dominiqs::numarray< bool >::iota(), dominiqs::numarray< bool >::numarray(), dominiqs::numarray< bool >::operator[](), dominiqs::numarray< bool >::push_back_unsafe(), dominiqs::numarray< bool >::reserve(), dominiqs::numarray< bool >::resize(), dominiqs::numarray< bool >::swap(), dominiqs::numarray< bool >::zero(), and dominiqs::numarray< bool >::~numarray().
length
template<typename T> size_type dominiqs::numarray< T >::length private
Definition at line 248 of file numarray.h.
Referenced by dominiqs::numarray< bool >::back(), dominiqs::numarray< bool >::clear(), dominiqs::numarray< bool >::empty(), dominiqs::numarray< bool >::end(), dominiqs::numarray< bool >::fill(), dominiqs::numarray< bool >::front(), dominiqs::numarray< bool >::iota(), dominiqs::numarray< bool >::numarray(), dominiqs::numarray< bool >::push_back(), dominiqs::numarray< bool >::push_back_unsafe(), dominiqs::numarray< bool >::reserve(), dominiqs::numarray< bool >::resize(), dominiqs::numarray< bool >::size(), dominiqs::numarray< bool >::swap(), and dominiqs::numarray< bool >::zero().
The documentation for this class was generated from the following file:
FP2/utils/numarray.h