BRKGA for MIP feasibility: dominiqs::FeasibilityPump Class Reference
dominiqs::FeasibilityPump Class Reference
Basic Feasibility Pump Scheme Accepts custom rounders.
#include <feaspump.h>
Public Member Functions
FeasibilityPump ()
void readConfig ()
void init (Env env, Prob lp, const std::vector< char > &ctype=std::vector< char >())
bool pump (const std::vector< double > &xStart=std::vector< double >(), bool pFeas=false)
void getSolution (std::vector< double > &x) const
double getSolutionValue (const std::vector< double > &x) const
int getIterations () const
void reset ()
Public Attributes
boost::function< void(double, double, int)> emitNewIncumbent
boost::function< void(Env env, Prob lp, int stage)> emitSolvedLP
double totalTime
int finalStage
Private Types
typedef std::pair< double, std::vector< double > > AlphaVector
Private Member Functions
void solveInitialLP ()
void perturbe (std::vector< double > &x, bool ignoreGeneralIntegers)
void restart (std::vector< double > &x, bool ignoreGeneralIntegers)
bool stage1 (double &runningAlpha, std::vector< double > &bestPoint)
bool stage2 (double &runningAlpha, std::vector< double > &bestPoint)
bool stage3 (const std::vector< double > &bestPoint)
void foundIncumbent (const std::vector< double > &x, double objval)
bool isInCache (double a, const std::vector< double > &x, bool ignoreGeneralIntegers)
Private Attributes
double timeLimit
int s1IterLimit
int iterLimit
int s1MaxMissedDecrease
int maxMissedDecrease
int maxRestarts
int avgFlips
double integralityEps
uint64_t seed
double sigmaThr
bool perturbeFromTransformerOutput
double alpha
double alphaFactor
double alphaDist
bool doStage3
char firstOptMethod
int optIterLimit
char reOptMethod
int reOptIterLimit
bool logPerturbation
bool logDetails
bool logIteration
bool logTime
bool logLP
Env m_env
Prob m_lp
SolutionTransformerPtr frac2int
std::vector< double > frac_x
int primalFeas
std::vector< double > integer_x
std::list< AlphaVector > lastIntegerX
double relaxationValue
std::vector< double > incumbent
double incumbentValue
UnitRandGen rnd
Model model
bool isPureInteger
bool isBinary
std::vector< double > obj
double objNorm
int objsen
std::vector< bool > fixed
std::vector< int > binaries
std::vector< int > gintegers
std::vector< int > integers
IterationDisplay display
int pertCnt
int restartCnt
int nitr
int lastRestart
int flipsInRestart
int maxFlipsInRestart
Chrono chrono
Chrono lpChrono
Chrono roundChrono
Detailed Description
Basic Feasibility Pump Scheme Accepts custom rounders.
Definition at line 27 of file feaspump.h.
Member Typedef Documentation
AlphaVector
typedef std::pair< double, std::vector<double> > dominiqs::FeasibilityPump::AlphaVector private
Definition at line 88 of file feaspump.h.
Constructor & Destructor Documentation
FeasibilityPump()
dominiqs::FeasibilityPump::FeasibilityPump ()
Definition at line 127 of file feaspump.cpp.
Member Function Documentation
foundIncumbent()
void dominiqs::FeasibilityPump::foundIncumbent (const std::vector< double > & x, double objval) private
Definition at line 979 of file feaspump.cpp.
References chrono, emitNewIncumbent, dominiqs::Logger::endSection(), frac2int, dominiqs::Chrono::getElapsed(), dominiqs::gLog(), incumbent, incumbentValue, lastIntegerX, logDetails, dominiqs::Logger::logItem(), MYLOG, and nitr.
Referenced by pump().
getIterations()
int dominiqs::FeasibilityPump::getIterations () const
Definition at line 237 of file feaspump.cpp.
References nitr.
getSolution()
void dominiqs::FeasibilityPump::getSolution (std::vector< double > & x) const
Definition at line 226 of file feaspump.cpp.
References incumbent.
Referenced by main().
getSolutionValue()
double dominiqs::FeasibilityPump::getSolutionValue (const std::vector< double > & x) const
Definition at line 232 of file feaspump.cpp.
References obj.
init()
void dominiqs::FeasibilityPump::init (Env env, Prob lp, const std::vector< char > & ctype = std::vector<char>())
init algorithm
Parameters
env cplex environment
lp problem object (this is modified by the algorithm: you may want to pass a copy!)
ctype if the problem object is an LP, you can provide variable type info with this vector
Definition at line 267 of file feaspump.cpp.
References binaries, CHECKED_CPX_CALL, DOMINIQS_ASSERT, dominiqs::dotProduct(), dominiqs::equal(), dominiqs::Model::extract(), fixed, frac2int, frac_x, gintegers, dominiqs::gLog(), integer_x, integers, integralityEps, isBinary, isPureInteger, dominiqs::Logger::logItem(), m_env, m_lp, model, obj, objNorm, objsen, reset(), dominiqs::Model::xLb, dominiqs::Model::xType, and dominiqs::Model::xUb.
Referenced by main().
isInCache()
bool dominiqs::FeasibilityPump::isInCache (double a, const std::vector< double > & x, bool ignoreGeneralIntegers) private
Definition at line 993 of file feaspump.cpp.
References alphaDist, areSolutionsEqual(), binaries, integer_x, integers, integralityEps, and lastIntegerX.
Referenced by stage1(), and stage2().
perturbe()
void dominiqs::FeasibilityPump::perturbe (std::vector< double > & x, bool ignoreGeneralIntegers) private
Definition at line 434 of file feaspump.cpp.
References avgFlips, binaries, display, DOMINIQS_ASSERT, dominiqs::Logger::endSection(), dominiqs::equal(), frac_x, dominiqs::UnitRandGen::getFloat(), dominiqs::gLog(), dominiqs::greaterThan(), integers, integralityEps, IT_DISPLAY_SIMPLE_FMT, dominiqs::lessThan(), dominiqs::Logger::logItem(), logPerturbation, model, MYLOG, pertCnt, perturbeFromTransformerOutput, rnd, dominiqs::IterationDisplay::set(), sigmaThr, dominiqs::Model::xLb, and dominiqs::Model::xUb.
Referenced by stage1(), and stage2().
pump()
bool dominiqs::FeasibilityPump::pump (const std::vector< double > & xStart = std::vector<double>(), bool pFeas = false)
pump
Parameters
xStart starting fractional solution (will solve LP if empty)
pFeas primal feasiblity status of supplied vector
Definition at line 311 of file feaspump.cpp.
References AbortOptimization, dominiqs::IterationDisplay::addColumn(), alpha, CHECKED_CPX_CALL, chrono, display, DOMINIQS_ASSERT, doStage3, dominiqs::dotProduct(), finalStage, foundIncumbent(), frac2int, frac_x, dominiqs::Chrono::getTotal(), dominiqs::gLog(), integers, integralityEps, dominiqs::iota(), dominiqs::isNull(), dominiqs::Logger::logItem(), lpChrono, m_env, m_lp, model, nitr, dominiqs::Model::numVars, obj, objNorm, pertCnt, primalFeas, reOptIterLimit, restartCnt, roundChrono, dominiqs::Logger::setConsoleEcho(), solutionNumFractional(), solveInitialLP(), stage1(), stage2(), stage3(), dominiqs::Chrono::start(), dominiqs::Chrono::stop(), totalTime, and dominiqs::userSignalBreak().
Referenced by main().
readConfig()
void dominiqs::FeasibilityPump::readConfig ()
Definition at line 149 of file feaspump.cpp.
References alpha, alphaDist, alphaFactor, avgFlips, dominiqs::DEF_ALPHA, dominiqs::DEF_ALPHA_DIST, dominiqs::DEF_ALPHA_FACTOR, dominiqs::DEF_AVG_FLIPS, dominiqs::DEF_DO_STAGE_3, dominiqs::DEF_INTEGRALITY_EPS, dominiqs::DEF_ITER_LIMIT, dominiqs::DEF_LOG_DETAILS, dominiqs::DEF_LOG_ITERATION, dominiqs::DEF_LOG_LP, dominiqs::DEF_LOG_PERTURBATION, dominiqs::DEF_LOG_TIME, dominiqs::DEF_MAX_MISSED_DECREASE, dominiqs::DEF_MAX_RESTARTS, dominiqs::DEF_OPT_ITER_LIMIT, dominiqs::DEF_PERTURBE_FROM_TRANSFORMER_OUTPUT, dominiqs::DEF_REOPT_ITER_LIMIT, dominiqs::DEF_S1_ITER_LIMIT, dominiqs::DEF_S1_MAX_MISSED_DECREASE, dominiqs::DEF_SEED, dominiqs::DEF_SIGMA_THR, dominiqs::DEF_TIME_LIMIT, display, DOMINIQS_ASSERT, doStage3, dominiqs::Logger::endSection(), firstOptMethod, frac2int, dominiqs::gConfig(), dominiqs::XMLConfig::get(), dominiqs::SingletonHolder< T >::getInstance(), dominiqs::gLog(), dominiqs::IterationDisplay::headerInterval, integralityEps, dominiqs::IterationDisplay::iterationInterval, iterLimit, LOG_CONFIG, logDetails, dominiqs::Logger::logItem(), logIteration, logLP, logPerturbation, logTime, maxMissedDecrease, maxRestarts, optIterLimit, perturbeFromTransformerOutput, READ_FROM_CONFIG, reOptIterLimit, reOptMethod, rnd, s1IterLimit, s1MaxMissedDecrease, seed, dominiqs::UnitRandGen::setSeed(), sigmaThr, dominiqs::Logger::startSection(), timeLimit, and dominiqs::UnitRandGen::warmUp().
Referenced by main().
reset()
void dominiqs::FeasibilityPump::reset ()
Definition at line 242 of file feaspump.cpp.
References binaries, chrono, fixed, flipsInRestart, dominiqs::gChrono(), gintegers, integers, isBinary, isPureInteger, lastIntegerX, lastRestart, lpChrono, m_env, m_lp, maxFlipsInRestart, nitr, pertCnt, dominiqs::Chrono::reset(), restartCnt, roundChrono, and dominiqs::Chrono::setDefaultType().
Referenced by init(), and main().
restart()
void dominiqs::FeasibilityPump::restart (std::vector< double > & x, bool ignoreGeneralIntegers) private
Definition at line 489 of file feaspump.cpp.
References avgFlips, dominiqs::BIGBIGM, dominiqs::BIGM, binaries, dominiqs::different(), DOMINIQS_ASSERT, dominiqs::Logger::endSection(), dominiqs::equal(), flipsInRestart, frac_x, dominiqs::GEOM_FACTOR, dominiqs::UnitRandGen::getFloat(), gintegers, dominiqs::gLog(), integralityEps, dominiqs::isNull(), lastIntegerX, lastRestart, dominiqs::Logger::logItem(), logPerturbation, max, maxFlipsInRestart, min, model, MYLOG, nitr, perturbeFromTransformerOutput, restartCnt, rnd, dominiqs::Model::xLb, and dominiqs::Model::xUb.
Referenced by stage1(), and stage2().
solveInitialLP()
void dominiqs::FeasibilityPump::solveInitialLP () private
Definition at line 405 of file feaspump.cpp.
References CHECKED_CPX_CALL, chrono, dominiqs::dotProduct(), emitSolvedLP, firstOptMethod, frac_x, dominiqs::Chrono::getElapsed(), dominiqs::gLog(), logDetails, dominiqs::Logger::logItem(), logLP, m_env, m_lp, max, model, MYLOG, dominiqs::Model::numVars, obj, optIterLimit, primalFeas, relaxationValue, and timeLimit.
Referenced by pump().
stage1()
bool dominiqs::FeasibilityPump::stage1 (double & runningAlpha, std::vector< double > & bestPoint) private
Definition at line 556 of file feaspump.cpp.
References AbortOptimization, dominiqs::accumulate(), alphaDist, alphaFactor, areSolutionsEqual(), binaries, CHECKED_CPX_CALL, chrono, display, dominiqs::dotProduct(), emitSolvedLP, dominiqs::equal(), dominiqs::EXTENDED_PRECISION, frac2int, frac_x, dominiqs::Chrono::getElapsed(), dominiqs::Chrono::getPartial(), dominiqs::gLog(), integer_x, integers, integralityEps, dominiqs::iota(), isInCache(), dominiqs::isNull(), isSolutionInteger(), IT_DISPLAY_SIMPLE_FLOAT_FMT, IT_DISPLAY_SIMPLE_FMT, lastIntegerX, logDetails, dominiqs::Logger::logItem(), logIteration, logLP, logTime, lpChrono, m_env, m_lp, max, maxRestarts, MYLOG, dominiqs::IterationDisplay::needHeader(), dominiqs::IterationDisplay::needPrint(), nitr, obj, objNorm, perturbe(), primalFeas, dominiqs::IterationDisplay::printHeader(), dominiqs::IterationDisplay::printIteration(), reOptMethod, dominiqs::IterationDisplay::resetIteration(), restart(), restartCnt, roundChrono, s1IterLimit, s1MaxMissedDecrease, dominiqs::IterationDisplay::set(), solutionFractionality(), solutionNumFractional(), solutionsDistance(), dominiqs::Chrono::start(), dominiqs::Chrono::stop(), and timeLimit.
Referenced by pump().
stage2()
bool dominiqs::FeasibilityPump::stage2 (double & runningAlpha, std::vector< double > & bestPoint) private
Definition at line 700 of file feaspump.cpp.
References AbortOptimization, dominiqs::accumulate(), dominiqs::addCut(), alphaDist, alphaFactor, areSolutionsEqual(), binaries, CHECKED_CPX_CALL, chrono, dominiqs::SparseVector::coef(), display, DOMINIQS_ASSERT, dominiqs::dotProduct(), emitSolvedLP, dominiqs::equal(), dominiqs::EXTENDED_PRECISION, frac2int, frac_x, dominiqs::Chrono::getElapsed(), dominiqs::Chrono::getPartial(), gintegers, dominiqs::gLog(), integer_x, integers, integralityEps, dominiqs::iota(), isInCache(), dominiqs::isNull(), isSolutionInteger(), IT_DISPLAY_SIMPLE_FLOAT_FMT, IT_DISPLAY_SIMPLE_FMT, iterLimit, lastIntegerX, logDetails, dominiqs::Logger::logItem(), logIteration, logLP, logTime, lpChrono, m_env, m_lp, max, maxFlipsInRestart, maxMissedDecrease, maxRestarts, model, MYLOG, dominiqs::IterationDisplay::needHeader(), dominiqs::IterationDisplay::needPrint(), nitr, obj, objNorm, perturbe(), primalFeas, dominiqs::IterationDisplay::printHeader(), dominiqs::IterationDisplay::printIteration(), dominiqs::SparseVector::push(), reOptMethod, dominiqs::IterationDisplay::resetIteration(), restart(), restartCnt, roundChrono, dominiqs::IterationDisplay::set(), solutionFractionality(), solutionNumFractional(), solutionsDistance(), dominiqs::Chrono::start(), dominiqs::Chrono::stop(), timeLimit, dominiqs::Model::xLb, dominiqs::Model::xNames, and dominiqs::Model::xUb.
Referenced by pump().
stage3()
bool dominiqs::FeasibilityPump::stage3 (const std::vector< double > & bestPoint) private
Definition at line 874 of file feaspump.cpp.
References AbortOptimization, dominiqs::addCut(), binaries, CHECKED_CPX_CALL, chrono, dominiqs::SparseVector::coef(), DOMINIQS_ASSERT, dominiqs::equal(), frac_x, dominiqs::Chrono::getElapsed(), gintegers, dominiqs::gLog(), integer_x, integers, integralityEps, dominiqs::iota(), dominiqs::isNull(), isSolutionInteger(), dominiqs::lessThan(), logDetails, dominiqs::Logger::logMsg(), m_env, m_lp, max, min, model, MYLOG, obj, primalFeas, dominiqs::SparseVector::push(), timeLimit, dominiqs::Model::xLb, dominiqs::Model::xNames, and dominiqs::Model::xUb.
Referenced by pump().
Member Data Documentation
alpha
double dominiqs::FeasibilityPump::alpha private
Definition at line 66 of file feaspump.h.
Referenced by pump(), and readConfig().
alphaDist
double dominiqs::FeasibilityPump::alphaDist private
Definition at line 68 of file feaspump.h.
Referenced by isInCache(), readConfig(), stage1(), and stage2().
alphaFactor
double dominiqs::FeasibilityPump::alphaFactor private
Definition at line 67 of file feaspump.h.
Referenced by readConfig(), stage1(), and stage2().
avgFlips
int dominiqs::FeasibilityPump::avgFlips private
Definition at line 61 of file feaspump.h.
Referenced by perturbe(), readConfig(), and restart().
binaries
std::vector<int> dominiqs::FeasibilityPump::binaries private
list of binary vars indexes
Definition at line 102 of file feaspump.h.
Referenced by init(), isInCache(), perturbe(), reset(), restart(), stage1(), stage2(), and stage3().
chrono
Chrono dominiqs::FeasibilityPump::chrono private
Definition at line 113 of file feaspump.h.
Referenced by foundIncumbent(), pump(), reset(), solveInitialLP(), stage1(), stage2(), and stage3().
display
IterationDisplay dominiqs::FeasibilityPump::display private
Definition at line 106 of file feaspump.h.
Referenced by perturbe(), pump(), readConfig(), stage1(), and stage2().
doStage3
bool dominiqs::FeasibilityPump::doStage3 private
Definition at line 69 of file feaspump.h.
Referenced by pump(), and readConfig().
emitNewIncumbent
boost::function<void (double, double, int)> dominiqs::FeasibilityPump::emitNewIncumbent
Definition at line 32 of file feaspump.h.
Referenced by foundIncumbent(), and main().
emitSolvedLP
boost::function<void (Env env, Prob lp, int stage)> dominiqs::FeasibilityPump::emitSolvedLP
Definition at line 33 of file feaspump.h.
Referenced by solveInitialLP(), stage1(), and stage2().
finalStage
int dominiqs::FeasibilityPump::finalStage
Definition at line 129 of file feaspump.h.
Referenced by main(), and pump().
firstOptMethod
char dominiqs::FeasibilityPump::firstOptMethod private
Definition at line 71 of file feaspump.h.
Referenced by readConfig(), and solveInitialLP().
fixed
std::vector<bool> dominiqs::FeasibilityPump::fixed private
fixed status in the original formulation (usually due to presolve)
Definition at line 101 of file feaspump.h.
Referenced by init(), and reset().
flipsInRestart
int dominiqs::FeasibilityPump::flipsInRestart private
Definition at line 111 of file feaspump.h.
Referenced by reset(), and restart().
frac2int
SolutionTransformerPtr dominiqs::FeasibilityPump::frac2int private
rounder
Definition at line 84 of file feaspump.h.
Referenced by foundIncumbent(), init(), pump(), readConfig(), stage1(), and stage2().
frac_x
std::vector<double> dominiqs::FeasibilityPump::frac_x private
fractional x^*
Definition at line 85 of file feaspump.h.
Referenced by init(), perturbe(), pump(), restart(), solveInitialLP(), stage1(), stage2(), and stage3().
gintegers
std::vector<int> dominiqs::FeasibilityPump::gintegers private
list of general integer vars indexes
Definition at line 103 of file feaspump.h.
Referenced by init(), reset(), restart(), stage2(), and stage3().
incumbent
std::vector<double> dominiqs::FeasibilityPump::incumbent private
current incumbent
Definition at line 91 of file feaspump.h.
Referenced by foundIncumbent(), and getSolution().
incumbentValue
double dominiqs::FeasibilityPump::incumbentValue private
Definition at line 92 of file feaspump.h.
Referenced by foundIncumbent().
integer_x
std::vector<double> dominiqs::FeasibilityPump::integer_x private
integer x^~
Definition at line 87 of file feaspump.h.
Referenced by init(), isInCache(), stage1(), stage2(), and stage3().
integers
std::vector<int> dominiqs::FeasibilityPump::integers private
list of non continuous vars indexes (binaries + gintegers)
Definition at line 104 of file feaspump.h.
Referenced by init(), isInCache(), perturbe(), pump(), reset(), stage1(), stage2(), and stage3().
integralityEps
double dominiqs::FeasibilityPump::integralityEps private
Definition at line 62 of file feaspump.h.
Referenced by init(), isInCache(), perturbe(), pump(), readConfig(), restart(), stage1(), stage2(), and stage3().
isBinary
bool dominiqs::FeasibilityPump::isBinary private
are there general integers?
Definition at line 97 of file feaspump.h.
Referenced by init(), and reset().
isPureInteger
bool dominiqs::FeasibilityPump::isPureInteger private
is it a mixed linear program?
Definition at line 96 of file feaspump.h.
Referenced by init(), and reset().
iterLimit
int dominiqs::FeasibilityPump::iterLimit private
Definition at line 57 of file feaspump.h.
Referenced by readConfig(), and stage2().
lastIntegerX
std::list< AlphaVector > dominiqs::FeasibilityPump::lastIntegerX private
integer x cache
Definition at line 89 of file feaspump.h.
Referenced by foundIncumbent(), isInCache(), reset(), restart(), stage1(), and stage2().
lastRestart
int dominiqs::FeasibilityPump::lastRestart private
Definition at line 110 of file feaspump.h.
Referenced by reset(), and restart().
logDetails
bool dominiqs::FeasibilityPump::logDetails private
Definition at line 77 of file feaspump.h.
Referenced by foundIncumbent(), readConfig(), solveInitialLP(), stage1(), stage2(), and stage3().
logIteration
bool dominiqs::FeasibilityPump::logIteration private
Definition at line 78 of file feaspump.h.
Referenced by readConfig(), stage1(), and stage2().
logLP
bool dominiqs::FeasibilityPump::logLP private
Definition at line 80 of file feaspump.h.
Referenced by readConfig(), solveInitialLP(), stage1(), and stage2().
logPerturbation
bool dominiqs::FeasibilityPump::logPerturbation private
Definition at line 76 of file feaspump.h.
Referenced by perturbe(), readConfig(), and restart().
logTime
bool dominiqs::FeasibilityPump::logTime private
Definition at line 79 of file feaspump.h.
Referenced by readConfig(), stage1(), and stage2().
lpChrono
Chrono dominiqs::FeasibilityPump::lpChrono private
Definition at line 114 of file feaspump.h.
Referenced by pump(), reset(), stage1(), and stage2().
m_env
Env dominiqs::FeasibilityPump::m_env private
Definition at line 82 of file feaspump.h.
Referenced by init(), pump(), reset(), solveInitialLP(), stage1(), stage2(), and stage3().
m_lp
Prob dominiqs::FeasibilityPump::m_lp private
Definition at line 83 of file feaspump.h.
Referenced by init(), pump(), reset(), solveInitialLP(), stage1(), stage2(), and stage3().
maxFlipsInRestart
int dominiqs::FeasibilityPump::maxFlipsInRestart private
Definition at line 112 of file feaspump.h.
Referenced by reset(), restart(), and stage2().
maxMissedDecrease
int dominiqs::FeasibilityPump::maxMissedDecrease private
Definition at line 59 of file feaspump.h.
Referenced by readConfig(), and stage2().
maxRestarts
int dominiqs::FeasibilityPump::maxRestarts private
Definition at line 60 of file feaspump.h.
Referenced by readConfig(), stage1(), and stage2().
model
Model dominiqs::FeasibilityPump::model private
Definition at line 95 of file feaspump.h.
Referenced by init(), perturbe(), pump(), restart(), solveInitialLP(), stage2(), and stage3().
nitr
int dominiqs::FeasibilityPump::nitr private
pumping iterations
Definition at line 109 of file feaspump.h.
Referenced by foundIncumbent(), getIterations(), pump(), reset(), restart(), stage1(), and stage2().
obj
std::vector<double> dominiqs::FeasibilityPump::obj private
original objective function
Definition at line 98 of file feaspump.h.
Referenced by getSolutionValue(), init(), pump(), solveInitialLP(), stage1(), stage2(), and stage3().
objNorm
double dominiqs::FeasibilityPump::objNorm private
Definition at line 99 of file feaspump.h.
Referenced by init(), pump(), stage1(), and stage2().
objsen
int dominiqs::FeasibilityPump::objsen private
Definition at line 100 of file feaspump.h.
Referenced by init().
optIterLimit
int dominiqs::FeasibilityPump::optIterLimit private
Definition at line 72 of file feaspump.h.
Referenced by readConfig(), and solveInitialLP().
pertCnt
int dominiqs::FeasibilityPump::pertCnt private
Definition at line 107 of file feaspump.h.
Referenced by perturbe(), pump(), and reset().
perturbeFromTransformerOutput
bool dominiqs::FeasibilityPump::perturbeFromTransformerOutput private
Definition at line 65 of file feaspump.h.
Referenced by perturbe(), readConfig(), and restart().
primalFeas
int dominiqs::FeasibilityPump::primalFeas private
is current fractional x^* primal feasible?
Definition at line 86 of file feaspump.h.
Referenced by pump(), solveInitialLP(), stage1(), stage2(), and stage3().
relaxationValue
double dominiqs::FeasibilityPump::relaxationValue private
Definition at line 90 of file feaspump.h.
Referenced by solveInitialLP().
reOptIterLimit
int dominiqs::FeasibilityPump::reOptIterLimit private
Definition at line 74 of file feaspump.h.
Referenced by pump(), and readConfig().
reOptMethod
char dominiqs::FeasibilityPump::reOptMethod private
Definition at line 73 of file feaspump.h.
Referenced by readConfig(), stage1(), and stage2().
restartCnt
int dominiqs::FeasibilityPump::restartCnt private
Definition at line 108 of file feaspump.h.
Referenced by pump(), reset(), restart(), stage1(), and stage2().
rnd
UnitRandGen dominiqs::FeasibilityPump::rnd private
Definition at line 93 of file feaspump.h.
Referenced by perturbe(), readConfig(), and restart().
roundChrono
Chrono dominiqs::FeasibilityPump::roundChrono private
Definition at line 115 of file feaspump.h.
Referenced by pump(), reset(), stage1(), and stage2().
s1IterLimit
int dominiqs::FeasibilityPump::s1IterLimit private
Definition at line 56 of file feaspump.h.
Referenced by readConfig(), and stage1().
s1MaxMissedDecrease
int dominiqs::FeasibilityPump::s1MaxMissedDecrease private
Definition at line 58 of file feaspump.h.
Referenced by readConfig(), and stage1().
seed
uint64_t dominiqs::FeasibilityPump::seed private
Definition at line 63 of file feaspump.h.
Referenced by readConfig().
sigmaThr
double dominiqs::FeasibilityPump::sigmaThr private
Definition at line 64 of file feaspump.h.
Referenced by perturbe(), and readConfig().
timeLimit
double dominiqs::FeasibilityPump::timeLimit private
Definition at line 55 of file feaspump.h.
Referenced by readConfig(), solveInitialLP(), stage1(), stage2(), and stage3().
totalTime
double dominiqs::FeasibilityPump::totalTime
Definition at line 128 of file feaspump.h.
Referenced by main(), and pump().
The documentation for this class was generated from the following files:
FP2/feaspump/feaspump.h
FP2/feaspump/feaspump.cpp