BRKGA for MIP feasibility: dominiqs::ScopeGuardImplBase Class Reference
dominiqs::ScopeGuardImplBase Class Reference
#include <scopeguard.h>
Public Member Functions
ScopeGuardImplBase () throw ()
void Dismiss () const throw ()
Protected Member Functions
~ScopeGuardImplBase ()
ScopeGuardImplBase (const ScopeGuardImplBase &other) throw ()
Static Protected Member Functions
template<typename J >
static void SafeExecute (J &j) throw ()
Protected Attributes
bool dismissed_
Private Member Functions
ScopeGuardImplBase & operator= (const ScopeGuardImplBase &)
Detailed Description
Base class for ScopeGuard
Definition at line 49 of file scopeguard.h.
Constructor & Destructor Documentation
~ScopeGuardImplBase()
dominiqs::ScopeGuardImplBase::~ScopeGuardImplBase () inline protected
Definition at line 53 of file scopeguard.h.
ScopeGuardImplBase() [1/2]
dominiqs::ScopeGuardImplBase::ScopeGuardImplBase (const ScopeGuardImplBase & other) throw () inline protected
Definition at line 54 of file scopeguard.h.
ScopeGuardImplBase() [2/2]
dominiqs::ScopeGuardImplBase::ScopeGuardImplBase () throw () inline
Definition at line 75 of file scopeguard.h.
Member Function Documentation
Dismiss()
void dominiqs::ScopeGuardImplBase::Dismiss () const throw () inline
Definition at line 76 of file scopeguard.h.
References dismissed_.
operator=()
ScopeGuardImplBase& dominiqs::ScopeGuardImplBase::operator= (const ScopeGuardImplBase &) private
SafeExecute()
template<typename J > static void dominiqs::ScopeGuardImplBase::SafeExecute (J & j) throw () inline static protected
Definition at line 60 of file scopeguard.h.
Referenced by dominiqs::ObjScopeGuardImpl0< Obj, MemFun >::~ObjScopeGuardImpl0(), dominiqs::ObjScopeGuardImpl1< Obj, MemFun, P1 >::~ObjScopeGuardImpl1(), dominiqs::ObjScopeGuardImpl2< Obj, MemFun, P1, P2 >::~ObjScopeGuardImpl2(), dominiqs::ScopeGuardImpl0< F >::~ScopeGuardImpl0(), dominiqs::ScopeGuardImpl1< F, P1 >::~ScopeGuardImpl1(), dominiqs::ScopeGuardImpl2< F, P1, P2 >::~ScopeGuardImpl2(), and dominiqs::ScopeGuardImpl3< F, P1, P2, P3 >::~ScopeGuardImpl3().
Member Data Documentation
dismissed_
bool dominiqs::ScopeGuardImplBase::dismissed_ mutable protected
Definition at line 73 of file scopeguard.h.
Referenced by Dismiss().
The documentation for this class was generated from the following file:
FP2/utils/scopeguard.h