BRKGA for MIP feasibility: ce_andrade::PlainRaggedMatrix< DataType, IndexType > Class Template Reference
ce_andrade::PlainRaggedMatrix< DataType, IndexType > Class Template Reference
Plain Ragged Matrix.
#include <plain_ragged_matrix.hpp>
Public Member Functions
Constructor and Destructor
PlainRaggedMatrix ()
Default constructor.
PlainRaggedMatrix (const IndexType _size)
Build constructor.
PlainRaggedMatrix (const PlainRaggedMatrix &other)
Copy constructor.
~PlainRaggedMatrix ()
Destructor.
Re-dimensioning
void resize (const IndexType _size)
Accessors
DataType & operator() (const IndexType row, const IndexType col)
Access the matrix element-wise. Note the m(x,y) = m(y,x).
DataType ** rawData () const
Return a pointer to the raw data stored. Note that we may change the values stored there but not the pointer themselves. THIS IS A DANGEROUS METHOD. DO NOT MODIFY THE POINTERS (modify the data is OK). USE WITH VERY CARE.
IndexType getSize () const
Returns the number of rows.
Protected Member Functions
void deallocate ()
Deallocate data.
Protected Attributes
IndexType size
The dimension size.
DataType ** data
The data.
Private Member Functions
PlainRaggedMatrix & operator= (const PlainRaggedMatrix &)=delete
No assignment operators.
Friends
std::ostream & operator<< (std::ostream &os, const PlainRaggedMatrix &matrix)
Print the instance on ostream output.
Detailed Description
template<typename DataType, typename IndexType>
class ce_andrade::PlainRaggedMatrix< DataType, IndexType >
Plain Ragged Matrix.
Author
Carlos Eduardo de Andrade ce.an.nosp@m.drad.nosp@m.e@gma.nosp@m.il.c.nosp@m.om
Date
2015
This class represents a plain ragged matrix used in the clustering algorithm. This is bottom-left triangular symmetric matrix.
Note
We DO NOT CHECK types or use traits in this template;
DataType must have a simple constructor;
IndexType must be a countable type admitting initialization from zero, pre-increment operator, and less_than operator. Usually, IndexType will be a integer type.
Definition at line 55 of file plain_ragged_matrix.hpp.
Constructor & Destructor Documentation
PlainRaggedMatrix() [1/3]
template<typename DataType, typename IndexType> ce_andrade::PlainRaggedMatrix< DataType, IndexType >::PlainRaggedMatrix () inline
Default constructor.
Definition at line 60 of file plain_ragged_matrix.hpp.
PlainRaggedMatrix() [2/3]
template<typename DataType, typename IndexType> ce_andrade::PlainRaggedMatrix< DataType, IndexType >::PlainRaggedMatrix (const IndexType _size) inline explicit
Build constructor.
Parameters
_size the matrix's dimension.
Definition at line 65 of file plain_ragged_matrix.hpp.
PlainRaggedMatrix() [3/3]
template<typename DataType, typename IndexType> ce_andrade::PlainRaggedMatrix< DataType, IndexType >::PlainRaggedMatrix (const PlainRaggedMatrix< DataType, IndexType > & other) inline
Copy constructor.
Parameters
other the matrix to be copied.
Definition at line 72 of file plain_ragged_matrix.hpp.
~PlainRaggedMatrix()
template<typename DataType, typename IndexType> ce_andrade::PlainRaggedMatrix< DataType, IndexType >::~PlainRaggedMatrix () inline
Destructor.
Definition at line 79 of file plain_ragged_matrix.hpp.
Member Function Documentation
deallocate()
template<typename DataType, typename IndexType> void ce_andrade::PlainRaggedMatrix< DataType, IndexType >::deallocate () inline protected
Deallocate data.
Helper methods
Definition at line 141 of file plain_ragged_matrix.hpp.
Referenced by ce_andrade::PlainRaggedMatrix< double, IloInt >::resize(), and ce_andrade::PlainRaggedMatrix< double, IloInt >::~PlainRaggedMatrix().
getSize()
template<typename DataType, typename IndexType> IndexType ce_andrade::PlainRaggedMatrix< DataType, IndexType >::getSize () const inline
Returns the number of rows.
Definition at line 122 of file plain_ragged_matrix.hpp.
operator()()
template<typename DataType, typename IndexType> DataType& ce_andrade::PlainRaggedMatrix< DataType, IndexType >::operator() (const IndexType row, const IndexType col) inline
Access the matrix element-wise. Note the m(x,y) = m(y,x).
Parameters
row the row to be access.
col the column to be access.
Definition at line 106 of file plain_ragged_matrix.hpp.
operator=()
template<typename DataType, typename IndexType> PlainRaggedMatrix& ce_andrade::PlainRaggedMatrix< DataType, IndexType >::operator= (const PlainRaggedMatrix< DataType, IndexType > &) private delete
No assignment operators.
rawData()
template<typename DataType, typename IndexType> DataType** ce_andrade::PlainRaggedMatrix< DataType, IndexType >::rawData () const inline
Return a pointer to the raw data stored. Note that we may change the values stored there but not the pointer themselves. THIS IS A DANGEROUS METHOD. DO NOT MODIFY THE POINTERS (modify the data is OK). USE WITH VERY CARE.
Definition at line 117 of file plain_ragged_matrix.hpp.
Referenced by ce_andrade::Clusterator::hierarchicalClustering().
resize()
template<typename DataType, typename IndexType> void ce_andrade::PlainRaggedMatrix< DataType, IndexType >::resize (const IndexType _size) inline
Resize the matrix.
Parameters
_size the new dimensions.
Definition at line 89 of file plain_ragged_matrix.hpp.
Referenced by ce_andrade::Clusterator::buildIncidenceMatrices(), ce_andrade::Clusterator::computeL1Distance(), ce_andrade::Clusterator::computeL2Distance(), and ce_andrade::PlainRaggedMatrix< double, IloInt >::PlainRaggedMatrix().
Friends And Related Function Documentation
operator<<
template<typename DataType, typename IndexType> std::ostream& operator<< (std::ostream & os, const PlainRaggedMatrix< DataType, IndexType > & matrix) friend
Print the instance on ostream output.
Definition at line 154 of file plain_ragged_matrix.hpp.
Member Data Documentation
data
template<typename DataType, typename IndexType> DataType** ce_andrade::PlainRaggedMatrix< DataType, IndexType >::data protected
The data.
Definition at line 135 of file plain_ragged_matrix.hpp.
Referenced by ce_andrade::PlainRaggedMatrix< double, IloInt >::PlainRaggedMatrix(), ce_andrade::PlainRaggedMatrix< double, IloInt >::rawData(), and ce_andrade::PlainRaggedMatrix< double, IloInt >::resize().
size
template<typename DataType, typename IndexType> IndexType ce_andrade::PlainRaggedMatrix< DataType, IndexType >::size protected
The dimension size.
The data
Definition at line 134 of file plain_ragged_matrix.hpp.
Referenced by ce_andrade::PlainRaggedMatrix< double, IloInt >::getSize(), ce_andrade::PlainRaggedMatrix< double, IloInt >::PlainRaggedMatrix(), and ce_andrade::PlainRaggedMatrix< double, IloInt >::resize().
The documentation for this class was generated from the following file:
clustering/plain_ragged_matrix.hpp