BRKGA for MIP feasibility: dominiqs::Path Class Reference
dominiqs::Path Class Reference
Path Class Convenience path handling class Its main usage is to recursively create directories. Eventually there will be a portable way to do it...
#include <path.h>
Public Member Functions
Path ()
Path (const char *path)
Path (const std::string &path)
void read (const char *path)
void read (const std::string &path)
Path operator/ (const std::string &chunk)
void operator/= (const std::string &chunk)
void mkdir (bool recursive=true)
bool isEmpty () const
bool isAbsolute () const
bool isRelative () const
std::string getPath () const
std::string getAbsolutePath () const
std::string getBasename () const
Protected Member Functions
void cleanPath (std::string &path) const
Protected Attributes
std::string data
Detailed Description
Path Class Convenience path handling class Its main usage is to recursively create directories. Eventually there will be a portable way to do it...
Definition at line 30 of file path.h.
Constructor & Destructor Documentation
Path() [1/3]
dominiqs::Path::Path () inline
Definition at line 33 of file path.h.
Path() [2/3]
dominiqs::Path::Path (const char * path) inline
Definition at line 34 of file path.h.
References read().
Path() [3/3]
dominiqs::Path::Path (const std::string & path) inline
Definition at line 35 of file path.h.
References read().
Member Function Documentation
cleanPath()
void dominiqs::Path::cleanPath (std::string & path) const protected
Definition at line 142 of file path.cpp.
References data, and isEmpty().
Referenced by getAbsolutePath(), operator/=(), and read().
getAbsolutePath()
std::string dominiqs::Path::getAbsolutePath () const
Get absolute path corresponding to current path
Definition at line 125 of file path.cpp.
References cleanPath(), data, dominiqs::getCwd(), and isAbsolute().
getBasename()
std::string dominiqs::Path::getBasename () const
Get basename (including extensions if present) of current path
Definition at line 134 of file path.cpp.
References data, and isEmpty().
Referenced by dominiqs::getProbName(), and main().
getPath()
std::string dominiqs::Path::getPath () const inline
Definition at line 60 of file path.h.
References data.
Referenced by dominiqs::Logger::open().
isAbsolute()
bool dominiqs::Path::isAbsolute () const
Definition at line 115 of file path.cpp.
References data, and isEmpty().
Referenced by getAbsolutePath().
isEmpty()
bool dominiqs::Path::isEmpty () const
Test methods
Definition at line 110 of file path.cpp.
References data.
Referenced by cleanPath(), getBasename(), isAbsolute(), and isRelative().
isRelative()
bool dominiqs::Path::isRelative () const
Definition at line 120 of file path.cpp.
References data, and isEmpty().
mkdir()
void dominiqs::Path::mkdir (bool recursive = true)
Make directory from path (optionally recursive)
Definition at line 81 of file path.cpp.
References data.
Referenced by dominiqs::Logger::open().
operator/()
Path dominiqs::Path::operator/ (const std::string & chunk)
Concatenate current path with chunk
Parameters
chunk
Returns
new path
Definition at line 64 of file path.cpp.
References data.
operator/=()
void dominiqs::Path::operator/= (const std::string & chunk)
Concatenate current path with chunk
Parameters
chunk inplace
Definition at line 71 of file path.cpp.
References cleanPath(), and data.
read() [1/2]
void dominiqs::Path::read (const char * path)
Read path from C-string or std::string
Definition at line 52 of file path.cpp.
References cleanPath(), and data.
Referenced by Path().
read() [2/2]
void dominiqs::Path::read (const std::string & path)
Definition at line 58 of file path.cpp.
References cleanPath(), and data.
Member Data Documentation
data
std::string dominiqs::Path::data protected
Definition at line 73 of file path.h.
Referenced by cleanPath(), getAbsolutePath(), getBasename(), getPath(), isAbsolute(), isEmpty(), isRelative(), mkdir(), operator/(), operator/=(), and read().
The documentation for this class was generated from the following files:
FP2/utils/path.h
FP2/utils/path.cpp