BRKGA for MIP feasibility: FP2/feaspump/transformers.h File Reference
transformers.h File Reference
Solution Transformers (a.k.a. rounders) Header.
#include <utils/randgen.h>
#include <propagator/domain.h>
#include <propagator/prop_engine.h>
#include "fp_interface.h"
#include "ranking.h"
Classes
class SimpleRounding
class PropagatorRounding
Functions
void doRound (const double &in, double &out, const double &thr)
double getRoundingThreshold (bool isRandom, dominiqs::UnitRandGen &gen)
Detailed Description
Solution Transformers (a.k.a. rounders) Header.
Author
Domenico Salvagnin <dominiqs at="" gmail="" dot="" com>=""> 2008
Definition in file transformers.h.
Function Documentation
doRound()
void doRound (const double & in, double & out, const double & thr) inline
Rounding helpers
Definition at line 24 of file transformers.h.
Referenced by SimpleRounding::apply(), and PropagatorRounding::apply().
getRoundingThreshold()
double getRoundingThreshold (bool isRandom, dominiqs::UnitRandGen & gen) inline
Definition at line 26 of file transformers.h.
References dominiqs::UnitRandGen::getFloat().
Referenced by SimpleRounding::apply(), and PropagatorRounding::apply().